import * as THREE from 'three';
import {SCENARIOS,scenarioById} from './scenarios.js';
import {SiegeSimulation,workPoint,clamp} from './simulation.js';
import {SiegePhysics} from './physics.js';
import {MiniatureScene} from './scene.js';
const $=id=>document.getElementById(id),canvas=$('scene'),SAVE='siegeworks-worlds-v1';let sim,physics,view,paused=false,speed=1,tool='orbit',selected=null,then=performance.now(),accumulator=0,lastSave=0,lastUI=0,toastTimer,drag=null,storageOK=true,pauseBeforeDialog=false,modalCount=0;let saves={version:1,last:'masada',worlds:{}};
try{const raw=localStorage.getItem(SAVE);if(raw&&raw.length<1800000){const s=JSON.parse(raw);if(s.version===1&&s.worlds&&typeof s.worlds==='object')saves=s;}}catch{storageOK=false;}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(),hitPoint=new THREE.Vector3();
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2500);}
function save(){if(!sim)return;saves.last=sim.config.id;saves.worlds[sim.config.id]={simulation:sim.exportState(),physics:physics.exportState(),paused:modalCount>0?pauseBeforeDialog:paused,speed,camera:view.camera.position.toArray(),target:view.controls.target.toArray(),selected};try{localStorage.setItem(SAVE,JSON.stringify(saves));$('save-status').textContent='Saved in this browser';}catch{if(storageOK)toast('Storage is unavailable. Your world stays in this session.');storageOK=false;$('save-status').textContent='This session only';}}
function setPause(value){paused=value;$('pause').setAttribute('aria-pressed',String(value));$('pause').setAttribute('aria-label',value?'Resume simulation':'Pause simulation');$('pause').textContent=value?'▷':'Ⅱ';document.querySelector('.live-dot').style.opacity=value?'.4':'1';}
function setSpeed(value){speed=value;document.querySelectorAll('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.speed)===speed)));}
function setTool(value){if(drag)drop({x:0,y:0,z:0});tool=value;view.controls.enabled=value==='orbit';document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===value)));$('hint').textContent=value==='grab'?'Hold a person to lift · Flick to throw · Scroll to raise · Esc to drop':value==='blast'?'Click the ground for a shockwave · People recover and resume their jobs':'Drag to orbit · Scroll to zoom · Click a person to inspect';canvas.style.cursor=value==='grab'?'grab':value==='blast'?'crosshair':'default';}
function inspect(id){selected=id;$('inspector').hidden=id===null;if(id!==null){const a=sim.agents[id];$('person-title').textContent=(a.role==='worker'?'Worker':a.role==='soldier'?'Soldier':a.role==='relief'?'Relief soldier':'Defender')+' '+String(id+1).padStart(2,'0');}updateUI();}
function openDialog(id){if(modalCount===0){pauseBeforeDialog=paused;setPause(true);}modalCount++;$(id).showModal();}
function updateUI(){if(!sim)return;const s=sim.config,p=Math.round(sim.progress*100);$('progress').textContent=p+'%';$('progress-fill').style.width=p+'%';$('stage').textContent=sim.stage;$('loads').textContent=sim.completedLoads;$('population').textContent=sim.agents.length;$('clock').textContent=Math.floor(sim.clock/60)+':'+String(Math.floor(sim.clock%60)).padStart(2,'0');if(selected!==null){const a=sim.agents[selected];$('person-job').textContent=a.job+(a.carrying?' · carrying a basket':'');$('person-health').textContent=Math.round(a.health*100)+'%';}}
function choose(id,restore=true){if(sim)save();if(view)view.dispose();sim=new SiegeSimulation(id);const stored=restore?saves.worlds[id]:null;if(stored&&!sim.restoreState(stored.simulation)){toast('That save could not be restored. A fresh siege is ready.');}physics=new SiegePhysics(sim);if(stored)physics.restoreState(stored.physics);view=new MiniatureScene(canvas,sim,physics);setPause(stored?.paused===true);setSpeed([1,4,12].includes(stored?.speed)?stored.speed:1);setTool('orbit');inspect(null);const s=sim.config;$('current-name').textContent=s.name;$('siege-title').textContent=s.name;$('region').textContent=s.region.toUpperCase();$('date').textContent=s.faction.toUpperCase()+' · '+s.date;$('focus').textContent=s.focus;$('work-name').textContent=s.work;document.querySelectorAll('[data-siege]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.siege===id)));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view==='overview')));$('history-title').textContent=s.name+' · '+s.date;$('history-fact').textContent=s.fact;$('history-limit').textContent=s.limit;$('sources').replaceChildren(...s.sources.map(([label,url])=>{const li=document.createElement('li'),a=document.createElement('a');a.href=url;a.textContent=label;a.target='_blank';a.rel='noopener noreferrer';li.append(a);return li;}));if(stored&&[stored.camera,stored.target].every(a=>Array.isArray(a)&&a.length===3&&a.every(v=>Number.isFinite(v)&&Math.abs(v)<500))){view.camera.position.fromArray(stored.camera);view.controls.target.fromArray(stored.target);view.controls.update();}if(matchMedia('(max-width:700px), (max-height:570px)').matches)$('overview').classList.add('collapsed');syncCollapse();accumulator=0;updateUI();save();}
function thumbnail(s){const city=s.kind==='rings'?'<ellipse cx="100" cy="50" rx="64" ry="32" fill="none" stroke="#9d9979" stroke-width="3"/><ellipse cx="100" cy="50" rx="48" ry="23" fill="none" stroke="#9d9979" stroke-width="2"/>':s.kind==='causeway'?'<path d="M20 66H115" stroke="#c9bc96" stroke-width="10"/>':s.kind==='trenches'?'<path d="M25 73l15-13-8-13 20-12-8-11 28-9" fill="none" stroke="#aa9477" stroke-width="5"/>':'<path d="M25 75 88 44l8 9-65 30z" fill="#bca57d"/>';const houses=Array.from({length:9},(_,i)=>`<rect x="${98+i%3*12}" y="${24+Math.floor(i/3)*11}" width="8" height="8" fill="${i%2?'#ded5bc':'#cdb797'}"/>`).join('');return `<svg viewBox="0 0 200 100" aria-hidden="true"><rect width="200" height="100" fill="${s.theme==='coast'?'#afc9c1':s.theme==='green'?'#bbc7a6':'#ddd0ad'}"/>${city}<path d="M80 62V24l50-10 25 22-6 36-48 11z" fill="#bcac88"/><path d="M80 56V24l50-10 25 22-6 30-48 11z" fill="#e5dbc1" stroke="#ac9e80" stroke-width="3"/>${houses}</svg>`;}
$('siege-grid').innerHTML=SCENARIOS.map(s=>`<button class="siege-option" data-siege="${s.id}" aria-pressed="false">${thumbnail(s)}<span class="siege-caption"><strong>${s.name}</strong><span class="siege-date">${s.faction.toUpperCase()} · ${s.date}</span><span class="siege-work">${s.work}</span></span></button>`).join('');
$('choose').onclick=()=>openDialog('sieges');$('notes').onclick=()=>openDialog('history');$('help').onclick=()=>openDialog('help-dialog');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>{modalCount=Math.max(0,modalCount-1);if(modalCount===0){setPause(pauseBeforeDialog);save();}});d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});});document.querySelectorAll('[data-siege]').forEach(b=>b.onclick=()=>{const wasPaused=pauseBeforeDialog;const id=b.dataset.siege,targetPaused=saves.worlds[id]?.paused??wasPaused;choose(id);pauseBeforeDialog=targetPaused;$('sieges').close();toast('Welcome to '+sim.config.name);});
function syncCollapse(){const closed=$('overview').classList.contains('collapsed');$('collapse').setAttribute('aria-expanded',String(!closed));$('collapse').setAttribute('aria-label',closed?'Expand siege details':'Collapse siege details');$('collapse').textContent=closed?'+':'−';}
$('collapse').onclick=()=>{$('overview').classList.toggle('collapsed');syncCollapse();};$('pause').onclick=()=>{setPause(!paused);save();};document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{setSpeed(Number(b.dataset.speed));save();});document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view.view(b.dataset.view);document.querySelectorAll('[data-view]').forEach(v=>v.setAttribute('aria-pressed',String(v===b)));save();});$('close-inspector').onclick=()=>inspect(null);$('follow-person').onclick=()=>{if(selected===null)return;view.followId=selected;const a=sim.agents[selected];view.controls.target.set(a.x,a.y+.8,a.z);view.camera.position.set(a.x-8,a.y+7,a.z+10);setTool('orbit');};$('finish').onclick=()=>{sim.finishWorks();physics.refreshTerrain();view.update(0);setPause(false);toast('Works complete. Watch the next phase unfold.');save();};$('restart').onclick=()=>{const id=sim.config.id;delete saves.worlds[id];sim=null;choose(id,false);toast('A fresh siege. Your other worlds are preserved.');};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Use your browser’s full screen or the site’s game controls.');}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit full screen':'Enter full screen');view.resize();});
function cast(event){const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,view.camera);}
function actorHit(){const hits=ray.intersectObjects(view.actorTargets,false);return hits.length?view.pickActor(hits[0]):null;}
function groundPoint(){return ray.intersectObject(view.terrain,false)[0]?.point||null;}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;cast(e);const id=actorHit();if(tool==='grab'){e.preventDefault();e.stopImmediatePropagation();if(id===null){toast('Choose The works or The camp, then hold a person.');return;}physics.grab(id);inspect(id);const b=physics.bodies[id];drag={id,pointerId:e.pointerId,height:b.position.y+3.5,trail:[],originX:e.clientX,originY:e.clientY};plane.set(new THREE.Vector3(0,1,0),-drag.height);if(ray.ray.intersectPlane(plane,hitPoint)){physics.moveHeld(hitPoint.x,drag.height,hitPoint.z);drag.trail.push({x:hitPoint.x,z:hitPoint.z,t:performance.now()});}canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';if(paused)toast('Resume time to move the physical body.');}else if(tool==='blast'){e.preventDefault();e.stopImmediatePropagation();const p=groundPoint();if(p){const n=physics.blast(p.x,p.z);view.shockwave(p.x,p.z);toast(n?`${n} people knocked off balance.`:'The shockwave crossed an empty patch of ground.');}}else{canvas.dataset.downX=e.clientX;canvas.dataset.downY=e.clientY;}},true);
canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();e.stopImmediatePropagation();cast(e);plane.set(new THREE.Vector3(0,1,0),-drag.height);if(ray.ray.intersectPlane(plane,hitPoint)){physics.moveHeld(hitPoint.x,drag.height,hitPoint.z);const now=performance.now();drag.trail.push({x:hitPoint.x,z:hitPoint.z,t:now});drag.trail=drag.trail.filter(p=>now-p.t<140);}},true);
function drop(velocity){if(!drag)return;physics.release(velocity);if(canvas.hasPointerCapture(drag.pointerId))canvas.releasePointerCapture(drag.pointerId);drag=null;canvas.style.cursor=tool==='grab'?'grab':'default';save();}
canvas.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.pointerId){e.preventDefault();e.stopImmediatePropagation();const a=drag.trail[0],b=drag.trail.at(-1),elapsed=a&&b?Math.max(.05,(b.t-a.t)/1000):1,age=b?performance.now()-b.t:1000;drop(a&&b&&age<180?{x:(b.x-a.x)/elapsed*.8,y:1.8,z:(b.z-a.z)/elapsed*.8}:{x:0,y:0,z:0});}else if(tool==='orbit'&&Math.hypot(e.clientX-Number(canvas.dataset.downX),e.clientY-Number(canvas.dataset.downY))<5){cast(e);const id=actorHit();if(id!==null)inspect(id);}},true);canvas.addEventListener('pointercancel',()=>drop({x:0,y:0,z:0}),true);canvas.addEventListener('wheel',e=>{if(!drag)return;e.preventDefault();e.stopImmediatePropagation();drag.height=clamp(drag.height-e.deltaY*.025,sim.agents[drag.id].y+1,48);physics.moveHeld(physics.cursor.position.x,drag.height,physics.cursor.position.z);},{capture:true,passive:false});
addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();setPause(!paused);save();}else if(e.code==='KeyG')setTool(tool==='grab'?'orbit':'grab');else if(e.key==='Escape'){drop({x:0,y:0,z:0});setTool('orbit');inspect(null);}else if(['1','2','3','4'].includes(e.key))view.view(['overview','works','city','camp'][Number(e.key)-1]);});addEventListener('resize',()=>view.resize());addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){save();then=performance.now();}});
try{const query=new URLSearchParams(location.search).get('siege');choose(scenarioById(query||saves.last).id);$('loading').remove();if(!storageOK)toast('Browser storage is unavailable. This world stays in the current session.');}catch(error){$('loading').innerHTML='<p>This browser could not start the 3D scene.</p><p>Try a browser with WebGL enabled.</p>';console.error(error);throw error;}
window.__siegeworks=Object.freeze({getSimulation:()=>sim,getPhysics:()=>physics,getScene:()=>view,getState:()=>({scenario:sim.config.id,paused,speed,tool,progress:sim.progress,loads:sim.completedLoads,stage:sim.stage}),save,choose,setTool,setPause});
function animate(now){requestAnimationFrame(animate);const realDt=Math.max(0,Math.min((now-then)/1000,.08));then=now;let elapsed=0;if(!paused&&!document.hidden){accumulator+=realDt*speed;let steps=0;while(accumulator>=1/30&&steps<30){sim.update(1/30);physics.update(1/30);for(const event of sim.events){if(event.type==='deposit'){view.burst(event.x,event.y+.6,event.z,1.2);if(physics.objects.length<80)physics.stone(event.x,event.y,event.z);}else if(event.type==='shot')view.shot();else if(event.type==='relief'){const a=sim.agents.find(a=>a.role==='relief');if(a)view.burst(a.x,a.y,a.z,1.4);}}if(sim.clock>8&&Math.floor((sim.clock-1/30)/9)!==Math.floor(sim.clock/9)&&sim.config.kind!=='rings')view.shot(true);for(const impact of physics.pendingImpacts.splice(0))view.burst(impact.x,impact.y,impact.z,Math.min(8,impact.strength*.35));accumulator-=1/30;elapsed+=1/30;steps++;}}view.update(elapsed);if(selected!==null){const a=sim.agents[selected];view.selection.visible=true;view.selection.position.set(a.disabled?physics.bodies[selected].position.x:a.x,(a.disabled?physics.bodies[selected].position.y-.7:a.y)+.05,a.disabled?physics.bodies[selected].position.z:a.z);}else view.selection.visible=false;if(now-lastUI>200){updateUI();lastUI=now;}if(now-lastSave>3000){save();lastSave=now;}}
requestAnimationFrame(animate);
