import * as THREE from 'three';
import {SCENARIOS,scenarioById} from './scenarios.js';
import {SiegeSimulation,workPoint,clamp,phases,naturalHeight,fortressOutline,ringSpec,campLayout,WATER_LEVEL,dayTime,DAY_LENGTH} from './simulation.js';
import {SiegePhysics} from './physics.js';
import {MiniatureScene,THEMES} from './scene.js';
const $=id=>document.getElementById(id),canvas=$('scene'),SAVE='siegeworks-worlds-v1';let sim,physics,view,paused=false,speed=1,tool='orbit',selected=null,then=performance.now(),accumulator=0,lastSave=0,lastUI=0,toastTimer,drag=null,storageOK=true,pauseBeforeDialog=false,modalCount=0,filter='all';let saves={version:1,last:'masada',worlds:{},prefs:{}};
try{const raw=localStorage.getItem(SAVE);if(raw&&raw.length<4000000){const s=JSON.parse(raw);if(s.version===1&&s.worlds&&typeof s.worlds==='object')saves={prefs:{},...s};}}catch{storageOK=false;}
const coarse=matchMedia('(pointer:coarse)').matches,prefs={quality:['high','balanced'].includes(saves.prefs?.quality)?saves.prefs.quality:coarse||navigator.hardwareConcurrency<=4?'balanced':'high',cycle:saves.prefs?.cycle!==false};
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(),hitPoint=new THREE.Vector3();
const isRoman=s=>/Roman|Octavian/.test(s.faction)||/Roman/.test(s.enemy||'');
function toast(message,ms=2600){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),ms);}
function save(){if(!sim)return;saves.last=sim.config.id;saves.prefs=prefs;saves.worlds[sim.config.id]={simulation:sim.exportState(),physics:physics.exportState(),paused:modalCount>0?pauseBeforeDialog:paused,speed,camera:view.camera.position.toArray(),target:view.controls.target.toArray(),selected,progress:sim.progress};try{localStorage.setItem(SAVE,JSON.stringify(saves));$('save-status').textContent='Saved in this browser';}catch{if(storageOK)toast('Storage is unavailable. Your world stays in this session.');storageOK=false;$('save-status').textContent='This session only';}}
function setPause(value){paused=value;$('pause').setAttribute('aria-pressed',String(value));$('pause').setAttribute('aria-label',value?'Resume simulation':'Pause simulation');$('pause').querySelector('use').setAttribute('href',value?'#i-play':'#i-pause');document.querySelector('.live-dot').style.opacity=value?'.35':'1';}
function setSpeed(value){speed=value;document.querySelectorAll('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.speed)===speed)));}
const HINTS={grab:'Hold a person to lift · Flick to throw · Scroll to raise · Esc to drop',blast:'Click the ground for a shockwave · People recover and resume their jobs',orbit:'Drag to orbit · Scroll to zoom · Click a person to inspect'};
function setTool(value){if(drag)drop({x:0,y:0,z:0});tool=value;view.controls.enabled=value==='orbit';document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===value)));$('hint').textContent=HINTS[value];canvas.style.cursor=value==='grab'?'grab':value==='blast'?'crosshair':'default';}
function roleName(a){const s=sim.config;return a.role==='worker'?'Worker':a.role==='soldier'?`${s.faction} soldier`:a.role==='relief'?'Relief army':`${s.enemy||'Defending'} defender`;}
function inspect(id){selected=id;$('inspector').hidden=id===null;if(id!==null){const a=sim.agents[id];$('person-title').textContent=roleName(a)+' '+String(id+1).padStart(2,'0');$('person-side').textContent=a.role==='soldier'||a.role==='worker'?'THE BESIEGERS':'THE BESIEGED';}updateUI();}
function openDialog(id){if(modalCount===0){pauseBeforeDialog=paused;setPause(true);}modalCount++;$(id).showModal();}
function dayLabel(){if(!prefs.cycle)return{icon:'#i-sun',day:'Day',label:'always day'};const t=dayTime(sim.clock),day=Math.floor(sim.clock/DAY_LENGTH+.12)+1,night=t>.64&&t<.97;return{icon:night?'#i-moon':'#i-sun',day:'Day '+day,label:t<.08?'dawn':t<.28?'morning':t<.42?'midday':t<.56?'afternoon':t<.64?'dusk':t<.97?'night':'before dawn'};}
function renderPhases(){const list=phases(sim.config),current=Math.max(0,list.indexOf(sim.stage));$('phases').replaceChildren(...list.map((name,i)=>{const li=document.createElement('li');li.title=name;li.innerHTML=`<span class="sr">${name}${i<current?' (done)':i===current?' (now)':''}</span>`;li.className=i<current?'done':i===current?'current':'';if(i===current)li.setAttribute('aria-current','step');return li;}));$('next-phase').textContent=list[current+1]?'Next: '+list[current+1]:'Final phase';}
function updateUI(){if(!sim)return;const p=Math.round(sim.progress*100);$('progress').textContent=p+'%';$('progress-fill').style.width=p+'%';$('progress-fill').parentElement.setAttribute('aria-valuenow',p);if($('stage').textContent!==sim.stage){$('stage').textContent=sim.stage;renderPhases();}$('loads').textContent=sim.completedLoads;$('population').textContent=sim.agents.length;$('clock').textContent=Math.floor(sim.clock/60)+':'+String(Math.floor(sim.clock%60)).padStart(2,'0');const d=dayLabel();$('daytime').querySelector('use').setAttribute('href',d.icon);$('daytime').querySelector('span').textContent=d.day;$('daylabel').textContent=d.label;
 if(selected!==null){const a=sim.agents[selected];$('person-job').textContent=a.job+(a.carrying?' · carrying a basket':'');$('person-health').textContent=Math.round(a.health*100)+'%';$('health-fill').style.width=Math.round(a.health*100)+'%';const worker=a.role==='worker';$('fatigue-row').hidden=$('fatigue-bar').hidden=!worker;$('person-fatigue').textContent=Math.round(a.fatigue*100)+'%';$('fatigue-fill').style.width=Math.round(a.fatigue*100)+'%';const story=[worker&&a.loads?`${a.loads} load${a.loads>1?'s':''} placed`:'',a.fights?`${a.fights} skirmish${a.fights>1?'es':''}`:'',a.tumbles?`thrown or knocked down ${a.tumbles}×`:'',a.arrowHits?`struck by ${a.arrowHits} missile${a.arrowHits>1?'s':''}`:''].filter(Boolean);$('person-story').textContent=story.length?story.join(' · '):worker?'Has not placed a load yet.':'A quiet life so far.';}}
const STAGE_TEXT={Advancing:'The works are ready. The engine moves up.','Guns forward':'The batteries are ready. The guns move forward.',Bombardment:'Bombardment begins.','Holding the lines':'The lines are complete.'};
function choose(id,restore=true){if(sim)save();if(view)view.dispose();sim=new SiegeSimulation(id);const stored=restore?saves.worlds[id]:null;if(stored&&!sim.restoreState(stored.simulation)){toast('That save could not be restored. A fresh siege is ready.');}physics=new SiegePhysics(sim);if(stored)physics.restoreState(stored.physics);view=new MiniatureScene(canvas,sim,physics,{quality:prefs.quality,cycle:prefs.cycle});setPause(stored?.paused===true);setSpeed([1,4,12].includes(stored?.speed)?stored.speed:1);setTool('orbit');inspect(null);const s=sim.config;
 $('current-name').textContent=s.name;$('current-date').textContent=s.date;$('siege-title').textContent=s.name;$('region').textContent=s.region;$('date').textContent=`${s.faction} · ${s.date}`;$('focus').textContent=s.focus;$('work-name').textContent=s.work;$('stage').textContent='';document.querySelectorAll('[data-siege]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.siege===id)));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view==='overview')));
 $('history-title').textContent=s.name+' · '+s.date;$('history-sides').textContent=`${s.faction} besiegers · ${s.enemy} defenders · ${s.region}`;$('history-fact').textContent=s.fact;$('history-limit').textContent=s.limit;$('sources').replaceChildren(...s.sources.map(([label,url])=>{const li=document.createElement('li'),a=document.createElement('a');a.href=url;a.textContent=label;a.target='_blank';a.rel='noopener noreferrer';li.append(a);return li;}));
 if(stored&&[stored.camera,stored.target].every(a=>Array.isArray(a)&&a.length===3&&a.every(v=>Number.isFinite(v)&&Math.abs(v)<500))){view.camera.position.fromArray(stored.camera);view.controls.target.fromArray(stored.target);view.controls.update();}if(matchMedia('(max-width:700px), (max-height:600px)').matches)$('overview').classList.add('collapsed');syncCollapse();accumulator=0;updateUI();renderPhases();save();}
// Selector cards draw a small map of each board from the same terrain the miniature uses.
const maps=new Map();
function drawMap(c,s){const g=c.getContext('2d'),W=124,H=88,img=g.createImageData(W,H),th=THEMES[s.theme]||THEMES.desert,low=new THREE.Color(th.low),high=new THREE.Color(th.high),col=new THREE.Color(),shallow=new THREE.Color('#9ccfc4'),deep=new THREE.Color('#4f8fa0');for(let j=0;j<H;j++)for(let i=0;i<W;i++){const x=i-62+.5,z=j-44+.5,h=naturalHeight(s,x,z),shade=clamp(1+(h-naturalHeight(s,x-1,z-1))*.18,.72,1.25);if(h<WATER_LEVEL)col.copy(shallow).lerp(deep,clamp((WATER_LEVEL-h)/2,0,1));else col.copy(low).lerp(high,clamp(h/14,0,1)).multiplyScalar(shade);const k=(j*W+i)*4;img.data[k]=col.r*255;img.data[k+1]=col.g*255;img.data[k+2]=col.b*255;img.data[k+3]=255;}g.putImageData(img,0,0);
 const P=(x,z)=>[x+62,z+44];g.lineCap='round';g.lineJoin='round';if(s.kind==='rings'){const r=ringSpec(s);g.strokeStyle='#8a6a45';g.lineWidth=2.2;for(const [rx,rz] of r.single?[r.inner]:[r.inner,r.outer]){g.beginPath();for(let k=0;k<=60;k++){const a=r.a0+(r.a1-r.a0)*k/60,[px,pz]=P(r.cx+Math.cos(a)*rx,r.cz+Math.sin(a)*rz);k?g.lineTo(px,pz):g.moveTo(px,pz);}g.stroke();}}else{g.strokeStyle='#9a6a42';g.lineWidth=s.kind==='trenches'?2:4;g.beginPath();for(let k=0;k<=40;k++){const p=workPoint(s,k/40),[px,pz]=P(p.x,p.z);k?g.lineTo(px,pz):g.moveTo(px,pz);}g.stroke();}
 const o=fortressOutline(s);g.fillStyle='#efe6d0cc';g.strokeStyle='#fffaf0';g.lineWidth=2;g.beginPath();o.forEach(([x,z],k)=>{const [px,pz]=P(x,z);k?g.lineTo(px,pz):g.moveTo(px,pz);});g.closePath();g.fill();g.stroke();const cl=campLayout(s);g.fillStyle='#d9cdb0';for(let r=0;r<cl.rows;r++)for(let k=0;k<cl.cols;k++){const [px,pz]=P(cl.x+k*3.6,cl.z+r*4.2);g.fillRect(px-.9,pz-1.1,1.8,2.2);}}
function buildSelector(){const counts={all:SCENARIOS.length,roman:SCENARIOS.filter(isRoman).length,ancient:SCENARIOS.filter(s=>s.era==='ancient').length,medieval:SCENARIOS.filter(s=>s.era==='medieval').length,'early modern':SCENARIOS.filter(s=>s.era==='early modern').length};$('filters').innerHTML=Object.entries({all:'All',roman:'Roman',ancient:'Ancient',medieval:'Medieval','early modern':'Early modern'}).map(([k,label])=>`<button data-filter="${k}" aria-pressed="${k===filter}">${label}<span>${counts[k]}</span></button>`).join('');$('world-count').textContent=SCENARIOS.length;
 $('siege-grid').innerHTML=SCENARIOS.map(s=>`<button class="siege-option" data-siege="${s.id}" aria-pressed="false"><canvas width="124" height="88" aria-hidden="true"></canvas><span class="siege-caption"><strong>${s.name}</strong><span class="siege-date">${s.date}</span><span class="siege-sides">${s.faction} vs ${s.enemy}</span><span class="siege-work">${s.work}</span><span class="chips"><span class="chip">${s.era}</span>${isRoman(s)?'<span class="chip roman">Roman</span>':''}<span class="chip saved" data-saved="${s.id}" hidden></span></span></span></button>`).join('');
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));applyFilter();});
 document.querySelectorAll('[data-siege]').forEach(b=>b.onclick=()=>{const wasPaused=pauseBeforeDialog,id=b.dataset.siege,targetPaused=saves.worlds[id]?.paused??wasPaused;choose(id);pauseBeforeDialog=targetPaused;$('sieges').close();toast('Welcome to '+sim.config.name);});}
function applyFilter(){document.querySelectorAll('[data-siege]').forEach(b=>{const s=scenarioById(b.dataset.siege);b.hidden=!(filter==='all'||filter==='roman'&&isRoman(s)||s.era===filter);});}
function openSelector(){for(const s of SCENARIOS){const chip=document.querySelector(`[data-saved="${s.id}"]`),w=saves.worlds[s.id];chip.hidden=!w;if(w)chip.textContent=Number.isFinite(w.progress)?`saved · ${Math.round(w.progress*100)}%`:'saved';}openDialog('sieges');const pending=[...document.querySelectorAll('.siege-option')].filter(b=>!maps.has(b.dataset.siege));const step=()=>{for(const b of pending.splice(0,3)){drawMap(b.querySelector('canvas'),scenarioById(b.dataset.siege));maps.set(b.dataset.siege,true);}if(pending.length)requestAnimationFrame(step);};requestAnimationFrame(step);}
buildSelector();applyFilter();
$('choose').onclick=openSelector;$('notes').onclick=()=>openDialog('history');$('help').onclick=()=>openDialog('help-dialog');$('settings').onclick=()=>openDialog('settings-dialog');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>{modalCount=Math.max(0,modalCount-1);if(modalCount===0){setPause(pauseBeforeDialog);save();}});d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});});
function syncSettings(){document.querySelectorAll('[data-quality]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.quality===prefs.quality)));document.querySelectorAll('[data-cycle]').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.cycle==='on')===prefs.cycle)));}
document.querySelectorAll('[data-quality]').forEach(b=>b.onclick=()=>{prefs.quality=b.dataset.quality;view.setQuality(prefs.quality);syncSettings();save();});document.querySelectorAll('[data-cycle]').forEach(b=>b.onclick=()=>{prefs.cycle=b.dataset.cycle==='on';view.setCycle(prefs.cycle);syncSettings();updateUI();save();});syncSettings();
function syncCollapse(){const closed=$('overview').classList.contains('collapsed');$('collapse').setAttribute('aria-expanded',String(!closed));$('collapse').setAttribute('aria-label',closed?'Expand siege details':'Collapse siege details');$('collapse').textContent=closed?'+':'−';}
$('collapse').onclick=()=>{$('overview').classList.toggle('collapsed');syncCollapse();};$('pause').onclick=()=>{setPause(!paused);save();};document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{setSpeed(Number(b.dataset.speed));save();});document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view.view(b.dataset.view);document.querySelectorAll('[data-view]').forEach(v=>v.setAttribute('aria-pressed',String(v===b)));save();});$('close-inspector').onclick=()=>inspect(null);$('follow-person').onclick=()=>{if(selected===null)return;view.followId=selected;view.tween=null;const a=sim.agents[selected];view.controls.target.set(a.x,a.y+.8,a.z);view.camera.position.set(a.x-8,a.y+7,a.z+10);setTool('orbit');};$('finish').onclick=()=>{sim.finishWorks();physics.refreshTerrain();view.update(0,0);setPause(false);toast('Works complete. Watch the next phase unfold.');save();};$('restart').onclick=()=>{const id=sim.config.id;delete saves.worlds[id];sim=null;choose(id,false);toast('A fresh siege. Your other worlds are preserved.');};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Use your browser’s full screen or the site’s game controls.');}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit full screen':'Enter full screen');view.resize();});
// Tooltips name each control and its shortcut.
const tip=$('tip');document.querySelectorAll('[data-tip]').forEach(el=>{const show=()=>{const r=el.getBoundingClientRect();tip.textContent=el.dataset.tip;tip.hidden=false;tip.style.left=clamp(r.left+r.width/2,70,innerWidth-70)+'px';tip.style.top=(r.top-8)+'px';};el.addEventListener('pointerenter',e=>{if(e.pointerType!=='touch')show();});el.addEventListener('focus',()=>{if(el.matches(':focus-visible'))show();});for(const ev of ['pointerleave','blur','click'])el.addEventListener(ev,()=>tip.hidden=true);if(!el.getAttribute('aria-label'))el.setAttribute('aria-description',el.dataset.tip);});
function cast(event){const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,view.camera);}
function actorHit(){const hits=ray.intersectObjects(view.actorTargets,false);return hits.length?view.pickActor(hits[0]):null;}
function groundPoint(){return ray.intersectObject(view.terrain,false)[0]?.point||null;}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;cast(e);const id=actorHit();if(tool==='grab'){e.preventDefault();e.stopImmediatePropagation();if(id===null){toast('Choose the Works or Camp view, then hold a person.');return;}physics.grab(id);inspect(id);const b=physics.bodies[id];drag={id,pointerId:e.pointerId,height:b.position.y+3.5,trail:[],originX:e.clientX,originY:e.clientY};plane.set(new THREE.Vector3(0,1,0),-drag.height);if(ray.ray.intersectPlane(plane,hitPoint)){physics.moveHeld(hitPoint.x,drag.height,hitPoint.z);drag.trail.push({x:hitPoint.x,z:hitPoint.z,t:performance.now()});}canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';if(paused)toast('Resume time to move the physical body.');}else if(tool==='blast'){e.preventDefault();e.stopImmediatePropagation();const p=groundPoint();if(p){const n=physics.blast(p.x,p.z);view.shockwave(p.x,p.z);toast(n?`${n} people knocked off balance.`:'The shockwave crossed an empty patch of ground.');}}else{canvas.dataset.downX=e.clientX;canvas.dataset.downY=e.clientY;}},true);
canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();e.stopImmediatePropagation();cast(e);plane.set(new THREE.Vector3(0,1,0),-drag.height);if(ray.ray.intersectPlane(plane,hitPoint)){physics.moveHeld(hitPoint.x,drag.height,hitPoint.z);const now=performance.now();drag.trail.push({x:hitPoint.x,z:hitPoint.z,t:now});drag.trail=drag.trail.filter(p=>now-p.t<140);}},true);
function drop(velocity){if(!drag)return;physics.release(velocity);if(canvas.hasPointerCapture(drag.pointerId))canvas.releasePointerCapture(drag.pointerId);drag=null;canvas.style.cursor=tool==='grab'?'grab':'default';save();}
canvas.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.pointerId){e.preventDefault();e.stopImmediatePropagation();const a=drag.trail[0],b=drag.trail.at(-1),elapsed=a&&b?Math.max(.05,(b.t-a.t)/1000):1,age=b?performance.now()-b.t:1000;drop(a&&b&&age<180?{x:(b.x-a.x)/elapsed*.8,y:1.8,z:(b.z-a.z)/elapsed*.8}:{x:0,y:0,z:0});}else if(tool==='orbit'&&Math.hypot(e.clientX-Number(canvas.dataset.downX),e.clientY-Number(canvas.dataset.downY))<5){cast(e);const id=actorHit();if(id!==null)inspect(id);}},true);canvas.addEventListener('pointercancel',()=>drop({x:0,y:0,z:0}),true);canvas.addEventListener('wheel',e=>{if(!drag)return;e.preventDefault();e.stopImmediatePropagation();drag.height=clamp(drag.height-e.deltaY*.025,sim.agents[drag.id].y+1,48);physics.moveHeld(physics.cursor.position.x,drag.height,physics.cursor.position.z);},{capture:true,passive:false});
addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();setPause(!paused);save();}else if(e.code==='KeyG')setTool(tool==='grab'?'orbit':'grab');else if(e.code==='KeyB')setTool(tool==='blast'?'orbit':'blast');else if(e.key==='Escape'){drop({x:0,y:0,z:0});setTool('orbit');inspect(null);}else if(['1','2','3','4'].includes(e.key)){const kind=['overview','works','city','camp'][Number(e.key)-1];view.view(kind);document.querySelectorAll('[data-view]').forEach(v=>v.setAttribute('aria-pressed',String(v.dataset.view===kind)));}});addEventListener('resize',()=>view.resize());addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){save();then=performance.now();}});
try{const query=new URLSearchParams(location.search).get('siege');choose(scenarioById(query||saves.last).id);$('loading').remove();if(!storageOK)toast('Browser storage is unavailable. This world stays in the current session.');}catch(error){$('loading').innerHTML='<p>This browser could not start the 3D scene.</p><p>Try a browser with WebGL enabled.</p>';console.error(error);throw error;}
window.__siegeworks=Object.freeze({getSimulation:()=>sim,getPhysics:()=>physics,getScene:()=>view,getState:()=>({scenario:sim.config.id,paused,speed,tool,progress:sim.progress,loads:sim.completedLoads,stage:sim.stage,quality:prefs.quality,cycle:prefs.cycle}),save,choose,setTool,setPause,inspect});
function animate(now){requestAnimationFrame(animate);const realDt=Math.max(0,Math.min((now-then)/1000,.08));then=now;let elapsed=0;if(!paused&&!document.hidden){accumulator+=realDt*speed;let steps=0;while(accumulator>=1/30&&steps<30){sim.update(1/30);physics.update(1/30);physics.handleEvents(sim.events);for(const event of sim.events){if(event.type==='deposit')view.burst(event.x,event.y+.6,event.z,1.2);else if(event.type==='hit')view.burst(event.x,event.y,event.z,.9);else if(event.type==='shot')view.shot();else if(event.type==='missile')view.missile(event);else if(event.type==='relief'){const a=sim.agents.find(a=>a.role==='relief');if(a)view.burst(a.x,a.y,a.z,1.4);}else if(event.type==='stage'){toast(STAGE_TEXT[event.stage]||event.stage+'.',3400);renderPhases();}}if(sim.clock>8&&Math.floor((sim.clock-1/30)/9)!==Math.floor(sim.clock/9)&&sim.config.kind!=='rings')view.shot(true);for(const impact of physics.pendingImpacts.splice(0))view.impact(impact);accumulator-=1/30;elapsed+=1/30;steps++;}}view.update(elapsed,realDt);if(selected!==null){const a=sim.agents[selected];view.selection.visible=true;view.selection.position.set(a.disabled?physics.bodies[selected].position.x:a.x,(a.disabled?physics.bodies[selected].position.y-.7:a.y)+.05,a.disabled?physics.bodies[selected].position.z:a.z);}else view.selection.visible=false;if(now-lastUI>200){updateUI();lastUI=now;}if(now-lastSave>3000){save();lastSave=now;}}
requestAnimationFrame(animate);
