import {containsPoint,segmentBlocked} from './collision.js';
const RADIUS=.54,NEIGHBOURS=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];

// Ground crews plan around solid footprints. Elevated sentries use the wall walk.
export class GroundNavigation{
 constructor(physics){this.physics=physics;this.paths=new Map();this.version=-1;this.step=.5;this.cols=241;this.rows=167;}
 // Solid footprints reach down to the ground, so anything taller than a step blocks, even on a slope below its base.
 obstacles(a){return this.physics.boxes.filter(b=>b.active&&b.top>a.y-.2);}
 // A quick bounding-circle test skips footprints far from the segment before the exact check.
 crosses(b,a,p,y,moving){if(!b.active||b.top<=y-.2||moving!==undefined&&!!b.moving!==moving)return false;const r=(b.reach??=Math.hypot(b.w,b.d)/2)+RADIUS;if(Math.max(a.x,p.x)<b.x-r||Math.min(a.x,p.x)>b.x+r||Math.max(a.z,p.z)<b.z-r||Math.min(a.z,p.z)>b.z+r)return false;return segmentBlocked(b,a,p,RADIUS);}
 blocked(a,p){for(const b of this.physics.boxes)if(this.crosses(b,a,p,a.y))return true;return false;}
 rebuild(){if(this.version===this.physics.obstacleVersion)return;this.mask=new Uint8Array(this.cols*this.rows);for(const b of this.physics.boxes){if(!b.active||b.moving)continue;const c=Math.abs(Math.cos(b.yaw)),s=Math.abs(Math.sin(b.yaw)),rx=c*b.w/2+s*b.d/2+.9,rz=s*b.w/2+c*b.d/2+.9,minI=Math.max(0,Math.floor((b.x-rx+60)/this.step)),maxI=Math.min(this.cols-1,Math.ceil((b.x+rx+60)/this.step)),minJ=Math.max(0,Math.floor((b.z-rz+41.5)/this.step)),maxJ=Math.min(this.rows-1,Math.ceil((b.z+rz+41.5)/this.step));for(let j=minJ;j<=maxJ;j++)for(let i=minI;i<=maxI;i++){const x=-60+i*this.step,z=-41.5+j*this.step;if(!containsPoint(b,x,z,.62))continue;const y=this.physics.sim.surfaceHeight(x,z);if(b.top>y-.2)this.mask[j*this.cols+i]=1;}}this.paths.clear();this.version=this.physics.obstacleVersion;}

 point(k){return{x:-60+(k%this.cols)*this.step,z:-41.5+Math.floor(k/this.cols)*this.step};}
 cell(p){const i=Math.max(0,Math.min(this.cols-1,Math.round((p.x+60)/this.step))),j=Math.max(0,Math.min(this.rows-1,Math.round((p.z+41.5)/this.step)));return j*this.cols+i;}
 free(k){if(!this.mask[k])return k;const origin=this.point(k);let best=-1,distance=Infinity;for(let j=-5;j<=5;j++)for(let i=-5;i<=5;i++){const q=k+j*this.cols+i;if(q<0||q>=this.mask.length||this.mask[q])continue;const p=this.point(q),d=Math.hypot(p.x-origin.x,p.z-origin.z);if(d<distance){best=q;distance=d;}}return best;}
 // A* over the walkability grid. Buffers are reused and the search is capped so an unreachable goal stays cheap.
 plan(a,goal){this.rebuild();const start=this.free(this.cell(a)),end=this.free(this.cell(goal));if(start<0||end<0)return[];const size=this.mask.length;if(this.scores?.length!==size){this.scores=new Float64Array(size);this.previous=new Int32Array(size);this.stamp=new Uint32Array(size);this.done=new Uint32Array(size);this.generation=0;}const scores=this.scores,previous=this.previous,stamp=this.stamp,done=this.done,gen=++this.generation,heap=[],score=k=>stamp[k]===gen?scores[k]:Infinity;const push=item=>{heap.push(item);let i=heap.length-1;while(i>0){const p=(i-1)>>1;if(heap[p].f<=item.f)break;heap[i]=heap[p];i=p;}heap[i]=item;};const pop=()=>{const first=heap[0],last=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let child=i*2+1;if(child+1<heap.length&&heap[child+1].f<heap[child].f)child++;if(heap[child].f>=last.f)break;heap[i]=heap[child];i=child;}heap[i]=last;}return first;};const target=this.point(end);stamp[start]=gen;scores[start]=0;previous[start]=-1;push({k:start,f:0});let expanded=0;while(heap.length&&expanded<9000){const {k}=pop();if(done[k]===gen)continue;if(k===end){const route=[];for(let q=end;q!==start;q=previous[q]){if(q<0)return[];route.push(this.point(q));}return route.reverse();}done[k]=gen;expanded++;const i=k%this.cols,j=Math.floor(k/this.cols);for(const [di,dj] of NEIGHBOURS){const ni=i+di,nj=j+dj,n=nj*this.cols+ni;if(ni<0||ni>=this.cols||nj<0||nj>=this.rows||this.mask[n]||done[n]===gen)continue;if(di&&dj&&(this.mask[j*this.cols+ni]||this.mask[nj*this.cols+i]))continue;const cost=scores[k]+(di&&dj?Math.SQRT2:1);if(cost>=score(n))continue;stamp[n]=gen;scores[n]=cost;previous[n]=k;const p=this.point(n);push({k:n,f:cost+Math.hypot(p.x-target.x,p.z-target.z)/this.step});}}return[];}
 target(a,goal){const boxes=this.physics.boxes,clear=(from,to)=>!boxes.some(b=>this.crosses(b,from,to,a.y,false));if(clear(a,goal)){this.paths.delete(a.id);return goal;}this.rebuild();const now=this.physics.sim.clock;let cached=this.paths.get(a.id);if(!cached||Math.hypot(goal.x-cached.goal.x,goal.z-cached.goal.z)>2.5||!cached.path.length&&now-cached.time>.6){cached={goal:{...goal},path:this.plan(a,goal),time:now};this.paths.set(a.id,cached);}while(cached.path.length&&Math.hypot(a.x-cached.path[0].x,a.z-cached.path[0].z)<.3)cached.path.shift();
 // A waypoint hidden behind a corner is skipped for a later one in view; a stuck figure retries after a pause.
 for(let k=0;k<Math.min(3,cached.path.length);k++)if(clear(a,cached.path[k])){cached.path.splice(0,k);return cached.path[0];}const home=this.point(this.free(this.cell(a)));if(cached.path.length&&clear(a,home))return home;cached.path=[];return{x:a.x,z:a.z};}
 // Goals inside a solid footprint are moved to the nearest open ground.
 reach(a,x,z){if(!this.physics.boxes.some(b=>b.active&&!b.moving&&b.top>a.y-.2&&containsPoint(b,x,z,.62)))return null;if(this.reachVersion!==this.physics.obstacleVersion){this.reachCache=new Map();this.reachVersion=this.physics.obstacleVersion;}const key=Math.round(x*4)*8192+Math.round(z*4);let p=this.reachCache.get(key);if(!p){p=this.freePosition(x,z);this.reachCache.set(key,p);}return p;}
 freePosition(x,z){let best=null,distance=Infinity;for(let ring=0;ring<=30;ring++){const r=ring*.45,n=Math.max(1,Math.ceil(r*12));for(let i=0;i<n;i++){const a=i/n*Math.PI*2,p={x:Math.max(-59,Math.min(59,x+Math.cos(a)*r)),z:Math.max(-40,Math.min(40,z+Math.sin(a)*r))},y=this.physics.sim.surfaceHeight(p.x,p.z);if(!this.physics.boxes.some(b=>b.active&&b.top>y-.2&&containsPoint(b,p.x,p.z,.6))){const d=Math.hypot(p.x-x,p.z-z);if(d<distance){distance=d;best={...p,y};}}}if(best)return best;}return{x:-56,z:-35,y:this.physics.sim.surfaceHeight(-56,-35)};}
}
