import {containsPoint,segmentBlocked} from './collision.js';

// Ground crews plan around solid footprints. Elevated sentries use the wall walk.
export class GroundNavigation{
 constructor(physics){this.physics=physics;this.paths=new Map();this.version=-1;this.step=.5;this.cols=241;this.rows=167;}
 obstacles(a){return this.physics.boxes.filter(b=>b.active&&b.top>a.y+.12&&b.bottom<a.y+1.65);}
 blocked(a,p){return this.obstacles(a).some(b=>segmentBlocked(b,a,p));}
 rebuild(){if(this.version===this.physics.obstacleVersion)return;this.mask=new Uint8Array(this.cols*this.rows);for(const b of this.physics.boxes){if(!b.active||b.moving)continue;const c=Math.abs(Math.cos(b.yaw)),s=Math.abs(Math.sin(b.yaw)),rx=c*b.w/2+s*b.d/2+.9,rz=s*b.w/2+c*b.d/2+.9,minI=Math.max(0,Math.floor((b.x-rx+60)/this.step)),maxI=Math.min(this.cols-1,Math.ceil((b.x+rx+60)/this.step)),minJ=Math.max(0,Math.floor((b.z-rz+41.5)/this.step)),maxJ=Math.min(this.rows-1,Math.ceil((b.z+rz+41.5)/this.step));for(let j=minJ;j<=maxJ;j++)for(let i=minI;i<=maxI;i++){const x=-60+i*this.step,z=-41.5+j*this.step;if(!containsPoint(b,x,z,.62))continue;const y=this.physics.sim.surfaceHeight(x,z);if(b.top>y+.12&&b.bottom<y+1.65)this.mask[j*this.cols+i]=1;}}this.paths.clear();this.version=this.physics.obstacleVersion;}

 point(k){return{x:-60+(k%this.cols)*this.step,z:-41.5+Math.floor(k/this.cols)*this.step};}
 cell(p){const i=Math.max(0,Math.min(this.cols-1,Math.round((p.x+60)/this.step))),j=Math.max(0,Math.min(this.rows-1,Math.round((p.z+41.5)/this.step)));return j*this.cols+i;}
 free(k){if(!this.mask[k])return k;const origin=this.point(k);let best=-1,distance=Infinity;for(let j=-5;j<=5;j++)for(let i=-5;i<=5;i++){const q=k+j*this.cols+i;if(q<0||q>=this.mask.length||this.mask[q])continue;const p=this.point(q),d=Math.hypot(p.x-origin.x,p.z-origin.z);if(d<distance){best=q;distance=d;}}return best;}
 plan(a,goal){this.rebuild();const start=this.free(this.cell(a)),end=this.free(this.cell(goal));if(start<0||end<0)return[];const scores=new Float64Array(this.mask.length).fill(Infinity),previous=new Int32Array(this.mask.length).fill(-1),closed=new Uint8Array(this.mask.length),heap=[];const push=item=>{heap.push(item);let i=heap.length-1;while(i>0){const p=(i-1)>>1;if(heap[p].f<=item.f)break;heap[i]=heap[p];i=p;}heap[i]=item;};const pop=()=>{const first=heap[0],last=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let child=i*2+1;if(child+1<heap.length&&heap[child+1].f<heap[child].f)child++;if(heap[child].f>=last.f)break;heap[i]=heap[child];i=child;}heap[i]=last;}return first;};const target=this.point(end);scores[start]=0;push({k:start,f:0});while(heap.length){const {k}=pop();if(closed[k])continue;if(k===end){const route=[];for(let q=end;q!==start;q=previous[q]){if(q<0)return[];route.push(this.point(q));}return route.reverse();}closed[k]=1;const i=k%this.cols,j=Math.floor(k/this.cols);for(const [di,dj] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const ni=i+di,nj=j+dj,n=nj*this.cols+ni;if(ni<0||ni>=this.cols||nj<0||nj>=this.rows||this.mask[n]||closed[n])continue;if(di&&dj&&(this.mask[j*this.cols+ni]||this.mask[nj*this.cols+i]))continue;const cost=scores[k]+Math.hypot(di,dj);if(cost>=scores[n])continue;scores[n]=cost;previous[n]=k;const p=this.point(n);push({k:n,f:cost+Math.hypot(p.x-target.x,p.z-target.z)/this.step});}}return[];}
 target(a,goal){const boxes=this.obstacles(a).filter(b=>!b.moving);if(!boxes.some(b=>segmentBlocked(b,a,goal))){this.paths.delete(a.id);return goal;}this.rebuild();let cached=this.paths.get(a.id);if(!cached||Math.hypot(goal.x-cached.goal.x,goal.z-cached.goal.z)>2.5){cached={goal:{...goal},path:this.plan(a,goal)};this.paths.set(a.id,cached);}while(cached.path.length&&Math.hypot(a.x-cached.path[0].x,a.z-cached.path[0].z)<.18)cached.path.shift();const next=cached.path[0];if(!next)return{x:a.x,z:a.z};if(boxes.some(b=>segmentBlocked(b,a,next))){this.paths.delete(a.id);return{x:a.x,z:a.z};}return next;}
 freePosition(x,z){let best=null,distance=Infinity;for(let ring=0;ring<=30;ring++){const r=ring*.45,n=Math.max(1,Math.ceil(r*12));for(let i=0;i<n;i++){const a=i/n*Math.PI*2,p={x:Math.max(-59,Math.min(59,x+Math.cos(a)*r)),z:Math.max(-40,Math.min(40,z+Math.sin(a)*r))},y=this.physics.sim.surfaceHeight(p.x,p.z);if(!this.physics.boxes.some(b=>b.active&&b.top>y+.12&&b.bottom<y+1.65&&containsPoint(b,p.x,p.z,.6))){const d=Math.hypot(p.x-x,p.z-z);if(d<distance){distance=d;best={...p,y};}}}if(best)return best;}return{x:-56,z:-35,y:this.physics.sim.surfaceHeight(-56,-35)};}
}
