import * as CANNON from 'cannon-es';
import { clamp } from './simulation.js';
import {TERRAIN,PERSON_ORIGIN} from './collision.js';
import {GroundNavigation} from './navigation.js';
/** Dynamic bodies share the rendered height field. Controlled agents become physical on contact or pickup. */
export class SiegePhysics{
 constructor(sim){this.sim=sim;this.world=new CANNON.World({gravity:new CANNON.Vec3(0,-9.81,0),allowSleep:true});this.world.broadphase=new CANNON.SAPBroadphase(this.world);this.world.solver.iterations=10;this.world.defaultContactMaterial.friction=.65;this.world.defaultContactMaterial.restitution=.18;this.bodies=[];this.objects=[];this.pendingImpacts=[];this.revision=-1;
 this.boxes=[];this.obstacleVersion=0;this.navigation=new GroundNavigation(this);sim.navigate=(a,p)=>this.navigation.target(a,p);sim.blocked=(a,p)=>this.navigation.blocked(a,p);sim.agentPosition=a=>{const b=this.bodies[a.id];return b?.type===CANNON.Body.DYNAMIC?{x:b.position.x,y:b.position.y-PERSON_ORIGIN,z:b.position.z}:a;};
 const {step,cols,rows}=TERRAIN;this.step=step;this.cols=cols;this.rows=rows;const data=Array.from({length:cols+1},()=>Array(rows+1).fill(0));this.groundShape=new CANNON.Heightfield(data,{elementSize:step});this.ground=new CANNON.Body({mass:0,shape:this.groundShape,collisionFilterGroup:1});this.ground.position.set(-62,0,44);this.ground.quaternion.setFromEuler(-Math.PI/2,0,0);this.world.addBody(this.ground);this.refreshTerrain();
 for(const a of sim.agents){const body=new CANNON.Body({mass:65,type:CANNON.Body.KINEMATIC,linearDamping:.15,angularDamping:.45,sleepSpeedLimit:.25,sleepTimeLimit:1});body.addShape(new CANNON.Box(new CANNON.Vec3(.5,.4,.28)),new CANNON.Vec3(0,.13,.05));body.addShape(new CANNON.Sphere(.28),new CANNON.Vec3(0,.63,0));body.addShape(new CANNON.Sphere(.26),new CANNON.Vec3(0,-.46,0));body.position.set(a.x,a.y+.72,a.z);body.agent=a;body.dynamicAge=0;body.collisionFilterGroup=2;body.collisionFilterMask=1|2|4;body.addEventListener('collide',e=>{if(body.type!==CANNON.Body.DYNAMIC)return;if(e.body.agent)sim.engage(a,e.body.agent);const impact=Math.abs(e.contact.getImpactVelocityAlongNormal());if(impact>3&&body.dynamicAge>.15){a.health=clamp(a.health-(impact-3)*.016,.2,1);this.pendingImpacts.push({x:body.position.x,y:body.position.y,z:body.position.z,strength:impact});sim.react(body.position.x,body.position.z,6);}});this.world.addBody(body);this.bodies.push(body);}
 this.cursor=new CANNON.Body({mass:0,collisionFilterGroup:0,collisionFilterMask:0});this.world.addBody(this.cursor);this.held=null;
 }
 refreshTerrain(){if(this.revision===this.sim.revision)return;for(let i=0;i<=this.cols;i++)for(let j=0;j<=this.rows;j++)this.groundShape.data[i][j]=this.sim.heightAt(-62+i*this.step,44-j*this.step);this.groundShape.update();this.groundShape.updateMinValue();this.groundShape.updateMaxValue();this.groundShape.updateBoundingSphereRadius();this.ground.updateBoundingRadius();this.ground.aabbNeedsUpdate=true;this.revision=this.sim.revision;}
 floorAt(x,z){return this.groundShape.getHeightAt(clamp(x+62,0,123.999999),clamp(44-z,0,87.999999),true);}
 addBox(x,y,z,w,h,d,yaw=0){const body=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(w/2,h/2,d/2)),collisionFilterGroup:1});body.position.set(x,y,z);body.quaternion.setFromEuler(0,yaw,0);body.aabbNeedsUpdate=true;body.updateAABB();body.obstacle={body,x,z,w,h,d,yaw,bottom:y-h/2,top:y+h/2,active:true,moving:false};this.boxes.push(body.obstacle);this.obstacleVersion++;this.world.addBody(body);return body;}
 addRoof(body,w,d,h){const x=w*.78/Math.SQRT2,z=d*.78/Math.SQRT2,vertices=[new CANNON.Vec3(-x,-.425,-z),new CANNON.Vec3(x,-.425,-z),new CANNON.Vec3(x,-.425,z),new CANNON.Vec3(-x,-.425,z),new CANNON.Vec3(0,.425,0)],shape=new CANNON.ConvexPolyhedron({vertices,faces:[[0,1,2,3],[0,4,1],[1,4,2],[2,4,3],[3,4,0]]});body.addShape(shape,new CANNON.Vec3(0,body.obstacle.bottom+h+.5-body.position.y,0));body.obstacle.top=body.obstacle.bottom+h+.925;body.obstacle.w=x*2;body.obstacle.d=z*2;body.aabbNeedsUpdate=true;body.updateAABB();this.obstacleVersion++;}
 removeBox(body){if(!body.obstacle?.active)return;body.obstacle.active=false;this.obstacleVersion++;this.world.removeBody(body);}
 resizeBox(body,bottom,height){const box=body.obstacle;if(!box?.active||Math.abs(box.h-height)<.002)return;box.h=height;box.bottom=bottom;box.top=bottom+height;body.position.y=bottom+height/2;body.shapes[0].halfExtents.y=height/2;body.shapes[0].updateConvexPolyhedronRepresentation();body.shapes[0].updateBoundingSphereRadius();body.updateBoundingRadius();body.aabbNeedsUpdate=true;this.obstacleVersion++;}
 makeDynamic(id){const body=this.bodies[id];if(!body)return null;body.type=CANNON.Body.DYNAMIC;body.mass=65;body.updateMassProperties();body.wakeUp();body.dynamicAge=0;body.aabbNeedsUpdate=true;this.world.broadphase.dirty=true;body.agent.disabled=true;body.agent.wallPatrol=false;body.agent.job='Tumbling';return body;}
 grab(id){this.release({x:0,y:0,z:0});const body=this.makeDynamic(id);if(!body)return false;this.cursor.position.copy(body.position);const constraint=new CANNON.PointToPointConstraint(body,new CANNON.Vec3(0,.12,0),this.cursor,new CANNON.Vec3(),20000);this.world.addConstraint(constraint);this.held={body,constraint};body.agent.job='Held by you';return true;}
 moveHeld(x,y,z){if(!this.held||![x,y,z].every(Number.isFinite))return;this.cursor.position.set(clamp(x,-59,59),clamp(y,1,55),clamp(z,-41,41));this.held.body.wakeUp();}
 release(velocity={x:0,y:0,z:0}){if(!this.held)return false;const {body,constraint}=this.held;this.world.removeConstraint(constraint);body.velocity.set(clamp(velocity.x||0,-35,35),clamp(velocity.y||0,-15,25),clamp(velocity.z||0,-35,35));body.wakeUp();body.angularVelocity.set(1.2,0,.5);body.dynamicAge=0;body.agent.job='Tumbling';this.held=null;return true;}
 blast(x,z,r=12,strength=9){this.sim.react(x,z,r+8);let count=0;for(const body of this.bodies){const dx=body.position.x-x,dz=body.position.z-z,d=Math.hypot(dx,dz);if(d>r)continue;this.makeDynamic(body.agent.id);const f=(1-d/r)*strength;body.velocity.set(dx/(d||1)*f,f*.65+1,dz/(d||1)*f);body.angularVelocity.set(f*.3,f*.1,1);count++;}return count;}
 projectile(from,to,speed=17,radius=.28){const body=new CANNON.Body({mass:8,shape:new CANNON.Sphere(radius),linearDamping:.005,collisionFilterGroup:4});body.position.set(from.x,from.y,from.z);const dx=to.x-from.x,dz=to.z-from.z,range=Math.hypot(dx,dz),t=Math.max(.5,range/speed);body.velocity.set(dx/t,(to.y-from.y)/t+9.81*t/2,dz/t);body.life=12;body.projectile=true;body.radius=radius;body.addEventListener('collide',e=>{if(body.hit)return;body.hit=true;const impact=Math.abs(e.contact.getImpactVelocityAlongNormal());if(e.body.wall&&Math.hypot(body.position.x-this.sim.config.end[0],body.position.z-this.sim.config.end[1])<10)this.sim.wallHealth=clamp(this.sim.wallHealth-impact*.0018,0,1);this.pendingImpacts.push({x:body.position.x,y:body.position.y,z:body.position.z,strength:impact});this.sim.react(body.position.x,body.position.z,10);});this.world.addBody(body);this.objects.push(body);return body;}
 stone(x,y,z){const body=new CANNON.Body({mass:1,shape:new CANNON.Sphere(.18),linearDamping:.2,collisionFilterGroup:4});body.position.set(x,y+.5,z);body.velocity.set((this.sim.random()-.5)*2,1.6,(this.sim.random()-.5)*2);body.life=3;this.world.addBody(body);this.objects.push(body);return body;}
 terrainPenetration(body){let penetration=0;const point=new CANNON.Vec3(),local=new CANNON.Vec3();for(let i=0;i<body.shapes.length;i++){const shape=body.shapes[i],offset=body.shapeOffsets[i];if(shape instanceof CANNON.Sphere){body.quaternion.vmult(offset,point);point.vadd(body.position,point);for(const [dx,dz] of [[0,0],[.7,0],[-.7,0],[0,.7],[0,-.7],[.5,.5],[.5,-.5],[-.5,.5],[-.5,-.5]]){const x=point.x+dx*shape.radius,z=point.z+dz*shape.radius,y=point.y-Math.sqrt(1-dx*dx-dz*dz)*shape.radius;penetration=Math.max(penetration,this.floorAt(x,z)-y);}}else if(shape instanceof CANNON.Box){const h=shape.halfExtents;for(const x of [-h.x,0,h.x])for(const y of [-h.y,h.y])for(const z of [-h.z,0,h.z]){local.set(x+offset.x,y+offset.y,z+offset.z);body.quaternion.vmult(local,point);point.vadd(body.position,point);penetration=Math.max(penetration,this.floorAt(point.x,point.z)-point.y);}}}return penetration;}
 guardTerrain(body){const margin=body.agent?1:.4;body.position.x=clamp(body.position.x,-62+margin,62-margin);body.position.z=clamp(body.position.z,-44+margin,44-margin);const penetration=this.terrainPenetration(body);if(penetration>.005){body.position.y+=penetration+.002;if(body.velocity.y<0)body.velocity.y=Math.max(0,-body.velocity.y*.08);body.aabbNeedsUpdate=true;body.wakeUp();}}
 syncCarts(dt){if(!this.cartBodies)return;this.sim.carts.forEach((cart,i)=>{const body=this.cartBodies[i],y=this.floorAt(cart.x,cart.z)+.62,box=body.obstacle;body.position.set(cart.x,y,cart.z);body.quaternion.setFromEuler(0,cart.heading,0);body.velocity.set(0,0,0);body.aabbNeedsUpdate=true;Object.assign(box,{x:cart.x,z:cart.z,yaw:cart.heading,bottom:y-.55,top:y+.55});});}
 update(dt){if(!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.1);this.refreshTerrain();this.syncCarts(dt);for(const body of this.bodies){const a=body.agent;if(body.type===CANNON.Body.KINEMATIC){if(!a.wallPatrol){const next={x:a.x,z:a.z};if(this.navigation.blocked({x:body.position.x,z:body.position.z,y:body.position.y-PERSON_ORIGIN},next)){const p=this.navigation.freePosition(body.position.x,body.position.z);Object.assign(a,p);}}
 body.position.set(a.x,a.y+PERSON_ORIGIN,a.z);body.quaternion.setFromEuler(0,a.heading,0);body.velocity.set(0,0,0);body.aabbNeedsUpdate=true;
 }else{body.dynamicAge+=dt;if(body!==this.held?.body&&(body.dynamicAge>(a.combatTarget>=0?1.4:6))&&(body.velocity.length()<.8||body.dynamicAge>14)){const p=this.navigation.freePosition(body.position.x,body.position.z);Object.assign(a,p);a.disabled=false;a.wallPatrol=false;a.recovery=2.5;a.job='Getting up';body.type=CANNON.Body.KINEMATIC;body.updateMassProperties();body.velocity.set(0,0,0);body.angularVelocity.set(0,0,0);body.quaternion.setFromEuler(0,a.heading,0);body.position.set(a.x,a.y+PERSON_ORIGIN,a.z);}}}
 // Small steps bound travel even for a fast throw or a held body near a wall.
 const active=[...this.bodies.filter(b=>b.type===CANNON.Body.DYNAMIC),...this.objects];let travel=0;for(const body of active){travel=Math.max(travel,body.velocity.length()*dt);if(body===this.held?.body)travel=Math.max(travel,body.position.distanceTo(this.cursor.position));}const steps=Math.min(48,Math.max(1,Math.ceil(dt*120),Math.ceil(travel/.12)));for(let i=0;i<steps;i++){this.world.step(dt/steps);for(const body of active)if(body.world)this.guardTerrain(body);}
 for(let i=this.objects.length-1;i>=0;i--){const b=this.objects[i];b.life-=dt;if(b.life<=0||b.position.y<-12){this.world.removeBody(b);this.objects.splice(i,1);}}
 }

 exportState(){return this.bodies.filter(b=>b.type===CANNON.Body.DYNAMIC).map(b=>({id:b.agent.id,position:b.position.toArray(),quaternion:b.quaternion.toArray(),velocity:b.velocity.toArray(),angularVelocity:b.angularVelocity.toArray(),age:b.dynamicAge}));}
 restoreState(save){if(!Array.isArray(save))return;for(const item of save.slice(0,this.bodies.length)){if(!Number.isInteger(item?.id)||!this.bodies[item.id]||![item.position,item.velocity,item.angularVelocity].every(v=>Array.isArray(v)&&v.length===3&&v.every(n=>Number.isFinite(n)&&Math.abs(n)<200))||item.quaternion?.length!==4||!item.quaternion.every(Number.isFinite))continue;const b=this.makeDynamic(item.id);b.position.set(...item.position);b.velocity.set(...item.velocity);b.angularVelocity.set(...item.angularVelocity);b.quaternion.set(...item.quaternion);b.quaternion.normalize();b.dynamicAge=Number.isFinite(item.age)?clamp(item.age,0,15):0;}}
}
