import * as CANNON from 'cannon-es';
import { clamp } from './simulation.js';
/** Dynamic bodies share the rendered height field. Controlled agents become physical on contact or pickup. */
export class SiegePhysics{
 constructor(sim){this.sim=sim;this.world=new CANNON.World({gravity:new CANNON.Vec3(0,-9.81,0),allowSleep:true});this.world.broadphase=new CANNON.SAPBroadphase(this.world);this.world.solver.iterations=10;this.world.defaultContactMaterial.friction=.65;this.world.defaultContactMaterial.restitution=.18;this.bodies=[];this.objects=[];this.pendingImpacts=[];this.revision=-1;
 const step=1.55,cols=80,rows=57;this.step=step;this.cols=cols;this.rows=rows;const data=Array.from({length:cols+1},()=>Array(rows+1).fill(0));this.groundShape=new CANNON.Heightfield(data,{elementSize:step});this.ground=new CANNON.Body({mass:0,shape:this.groundShape,collisionFilterGroup:1});this.ground.position.set(-62,0,44);this.ground.quaternion.setFromEuler(-Math.PI/2,0,0);this.world.addBody(this.ground);this.refreshTerrain();
 for(const a of sim.agents){const body=new CANNON.Body({mass:65,type:CANNON.Body.KINEMATIC,linearDamping:.15,angularDamping:.45,sleepSpeedLimit:.25,sleepTimeLimit:1});body.addShape(new CANNON.Box(new CANNON.Vec3(.23,.35,.17)),new CANNON.Vec3(0,.05,0));body.addShape(new CANNON.Sphere(.24),new CANNON.Vec3(0,.53,0));body.addShape(new CANNON.Sphere(.22),new CANNON.Vec3(0,-.46,0));body.position.set(a.x,a.y+.72,a.z);body.agent=a;body.dynamicAge=0;body.collisionFilterGroup=2;body.collisionFilterMask=1|2|4;body.addEventListener('collide',e=>{if(body.type!==CANNON.Body.DYNAMIC)return;const impact=Math.abs(e.contact.getImpactVelocityAlongNormal());if(impact>3&&body.dynamicAge>.15){a.health=clamp(a.health-(impact-3)*.016,.2,1);this.pendingImpacts.push({x:body.position.x,y:body.position.y,z:body.position.z,strength:impact});sim.react(body.position.x,body.position.z,6);}});this.world.addBody(body);this.bodies.push(body);}
 this.cursor=new CANNON.Body({mass:0,collisionFilterGroup:0,collisionFilterMask:0});this.world.addBody(this.cursor);this.held=null;
 }
 refreshTerrain(){if(this.revision===this.sim.revision)return;for(let i=0;i<=this.cols;i++)for(let j=0;j<=this.rows;j++)this.groundShape.data[i][j]=this.sim.heightAt(-62+i*this.step,44-j*this.step);this.groundShape.update();this.groundShape.updateMinValue();this.groundShape.updateMaxValue();this.groundShape.updateBoundingSphereRadius();this.ground.aabbNeedsUpdate=true;this.revision=this.sim.revision;}
 addBox(x,y,z,w,h,d,yaw=0){const body=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(w/2,h/2,d/2)),collisionFilterGroup:1});body.position.set(x,y,z);body.quaternion.setFromEuler(0,yaw,0);this.world.addBody(body);return body;}
 makeDynamic(id){const body=this.bodies[id];if(!body)return null;body.type=CANNON.Body.DYNAMIC;body.mass=65;body.updateMassProperties();body.wakeUp();body.dynamicAge=0;body.agent.disabled=true;body.agent.job='Tumbling';return body;}
 grab(id){this.release({x:0,y:0,z:0});const body=this.makeDynamic(id);if(!body)return false;this.cursor.position.copy(body.position);const constraint=new CANNON.PointToPointConstraint(body,new CANNON.Vec3(0,.12,0),this.cursor,new CANNON.Vec3(),20000);this.world.addConstraint(constraint);this.held={body,constraint};body.agent.job='Held by you';return true;}
 moveHeld(x,y,z){if(!this.held||![x,y,z].every(Number.isFinite))return;this.cursor.position.set(clamp(x,-59,59),clamp(y,1,55),clamp(z,-41,41));this.held.body.wakeUp();}
 release(velocity={x:0,y:0,z:0}){if(!this.held)return false;const {body,constraint}=this.held;this.world.removeConstraint(constraint);body.velocity.set(clamp(velocity.x||0,-35,35),clamp(velocity.y||0,-15,25),clamp(velocity.z||0,-35,35));body.wakeUp();body.angularVelocity.set(1.2,0,.5);body.dynamicAge=0;body.agent.job='Tumbling';this.held=null;return true;}
 blast(x,z,r=12,strength=9){this.sim.react(x,z,r+8);let count=0;for(const body of this.bodies){const dx=body.position.x-x,dz=body.position.z-z,d=Math.hypot(dx,dz);if(d>r)continue;this.makeDynamic(body.agent.id);const f=(1-d/r)*strength;body.velocity.set(dx/(d||1)*f,f*.65+1,dz/(d||1)*f);body.angularVelocity.set(f*.3,f*.1,1);count++;}return count;}
 projectile(from,to,speed=17,radius=.28){const body=new CANNON.Body({mass:8,shape:new CANNON.Sphere(radius),linearDamping:.005,collisionFilterGroup:4});body.position.set(from.x,from.y,from.z);const dx=to.x-from.x,dz=to.z-from.z,range=Math.hypot(dx,dz),t=Math.max(.5,range/speed);body.velocity.set(dx/t,(to.y-from.y)/t+9.81*t/2,dz/t);body.life=12;body.projectile=true;body.radius=radius;body.addEventListener('collide',e=>{if(body.hit)return;body.hit=true;const impact=Math.abs(e.contact.getImpactVelocityAlongNormal());if(e.body.wall&&Math.hypot(body.position.x-this.sim.config.end[0],body.position.z-this.sim.config.end[1])<10)this.sim.wallHealth=clamp(this.sim.wallHealth-impact*.0018,0,1);this.pendingImpacts.push({x:body.position.x,y:body.position.y,z:body.position.z,strength:impact});this.sim.react(body.position.x,body.position.z,10);});this.world.addBody(body);this.objects.push(body);return body;}
 stone(x,y,z){const body=new CANNON.Body({mass:1,shape:new CANNON.Sphere(.18),linearDamping:.2,collisionFilterGroup:4});body.position.set(x,y+.5,z);body.velocity.set((this.sim.random()-.5)*2,1.6,(this.sim.random()-.5)*2);body.life=3;this.world.addBody(body);this.objects.push(body);return body;}
 update(dt){if(dt<=0)return;this.refreshTerrain();for(const body of this.bodies){const a=body.agent;if(body.type===CANNON.Body.KINEMATIC){body.position.set(a.x,a.y+.72,a.z);body.quaternion.setFromEuler(0,a.heading,0);body.velocity.set(0,0,0);body.aabbNeedsUpdate=true;}else{body.dynamicAge+=dt;if(body!==this.held?.body&&body.dynamicAge>6&&(body.velocity.length()<.8||body.dynamicAge>14)){a.x=clamp(body.position.x,-57,57);a.z=clamp(body.position.z,-38,38);a.y=this.sim.heightAt(a.x,a.z);a.disabled=false;a.recovery=2.5;a.job='Getting up';body.type=CANNON.Body.KINEMATIC;body.velocity.set(0,0,0);body.angularVelocity.set(0,0,0);body.quaternion.setFromEuler(0,a.heading,0);body.position.set(a.x,a.y+.72,a.z);}}}
 this.world.step(1/60,Math.min(dt,.1),6);for(let i=this.objects.length-1;i>=0;i--){const b=this.objects[i];b.life-=dt;if(b.life<=0||b.position.y<-12){this.world.removeBody(b);this.objects.splice(i,1);}}
 }
 exportState(){return this.bodies.filter(b=>b.type===CANNON.Body.DYNAMIC).map(b=>({id:b.agent.id,position:b.position.toArray(),quaternion:b.quaternion.toArray(),velocity:b.velocity.toArray(),angularVelocity:b.angularVelocity.toArray(),age:b.dynamicAge}));}
 restoreState(save){if(!Array.isArray(save))return;for(const item of save.slice(0,this.bodies.length)){if(!Number.isInteger(item?.id)||!this.bodies[item.id]||![item.position,item.velocity,item.angularVelocity].every(v=>Array.isArray(v)&&v.length===3&&v.every(n=>Number.isFinite(n)&&Math.abs(n)<200))||item.quaternion?.length!==4||!item.quaternion.every(Number.isFinite))continue;const b=this.makeDynamic(item.id);b.position.set(...item.position);b.velocity.set(...item.velocity);b.angularVelocity.set(...item.angularVelocity);b.quaternion.set(...item.quaternion);b.quaternion.normalize();b.dynamicAge=Number.isFinite(item.age)?clamp(item.age,0,15):0;}}
}
