// Each siege is data: its story, the landform, the circuit of walls, the camp and the works.
// terrain: a landform (rise, hill, mesa, plain, coastline) with optional sea, river, marsh, ditch, land masses, bumps and ridges.
// walls: shape (rect, round, star, poly), size and height. kind: the siege works the crews build.
// finale: the label for the last phase; breach:false keeps the walls standing where the city did not fall by assault.
const PI=Math.PI;
export const SCENARIOS=[
 {id:'masada',name:'Masada',date:'73 / 74 CE',faction:'Roman',region:'Judaean Desert',kind:'ramp',theme:'desert',work:'Western siege ramp',focus:'Earth, timber, and a natural spur.',description:'Watch a supply line build an earthen approach over the western spur. When the surface is ready, a timber tower can climb toward the casemate wall.',fact:'The western ramp, siege camps, and encircling wall survive. The ramp was built on a natural spur; the Romans did not build the mountain. The siege is commonly dated to 73 or 74 CE.',limit:'The plateau, camps, and ramp are schematic. Construction speed, worker numbers, tower motion, and the breach sequence are illustrative. Details of the final assault and the historical narrative remain debated.',sources:[['Masada, UNESCO','https://whc.unesco.org/en/list/1040/'],['Roman ramp, Israel Nature and Parks Authority','https://en.parks.org.il/article/the-roman-ramp-trail-at-masada-national-park/'],['2024 archaeological analysis','https://doi.org/10.1017/S1047759424000084']],start:[-32,0],end:[2,0],camp:[-45,-21],fort:[18,0],height:24,workers:48,soldiers:24,defenders:24,seed:1040},
 {id:'alesia',name:'Alesia',date:'52 BCE',faction:'Roman',region:'Gaul',kind:'rings',relief:20,theme:'green',work:'Double lines of fortification',focus:'A siege inside a siege.',description:'Builders extend two defensive circuits around the hilltop settlement. Roman patrols hold the space between them while a relief force approaches from outside.',fact:'Caesar enclosed the oppidum with an inner line and protected his troops with an outer line. Archaeological investigations have recovered the defensive lines, camps, and military material.',limit:'The two circuits are compressed into a small landscape. The model simplifies the valleys, ditch systems, troop numbers, and attacks. It does not reconstruct a particular hour of the battle.',sources:[['Alesia, Musée d’Archéologie nationale','https://musee-archeologienationale.fr/vercingetorix-et-alesia'],['Archaeology, Alésia MuséoParc','https://alesia.com/archeologie/']],start:[-35,0],end:[-10,0],camp:[-42,-24],fort:[0,0],height:9,workers:48,soldiers:32,defenders:28,seed:52},
 {id:'jerusalem',name:'Jerusalem',date:'70 CE',faction:'Roman',region:'Judaea',kind:'terraces',theme:'desert',work:'Assault terraces',focus:'Ramps against a layered city.',description:'Work crews build approach terraces beneath the northern defenses. Towers and artillery support an assault against several walls around a dense urban model.',fact:'Roman forces under Titus besieged Jerusalem in 70 CE. Josephus describes siege banks, engines, successive walls, and assaults during the siege.',limit:'This is a schematic engineering vignette, not a surveyed reconstruction of Jerusalem or a complete account of the siege. Buildings, banks, and positions are simplified; the destruction of civilians is not simulated.',sources:[['Josephus, Jewish War, Book V','https://penelope.uchicago.edu/josephus/war-5.html'],['Josephus, Jewish War, Book VI','https://penelope.uchicago.edu/josephus/war-6.html']],start:[-33,0],end:[0,0],camp:[-44,-24],fort:[20,0],height:7,workers:52,soldiers:28,defenders:28,seed:70},
 {id:'tyre',name:'Tyre',date:'332 BCE',faction:'Macedonian',region:'Phoenician coast',kind:'causeway',theme:'coast',work:'Stone causeway',focus:'Make a road across the sea.',description:'Haulers carry rubble from the shore and extend a causeway toward an island city. Ships circle the works and towers advance as the stone surface emerges from the water.',fact:'Alexander’s forces besieged the island city in 332 BCE. A causeway linked it to the mainland, permanently changing the coastline.',limit:'The island, channel, causeway, fleet, and construction rate are stylized. Ships follow simple steering paths; the water surface is a wave model. This is not a sediment transport or naval warfare reconstruction.',sources:[['Tyre, UNESCO','https://whc.unesco.org/en/list/299/'],['Tyre archaeological research, American University of Beirut','https://www.aub.edu.lb/museum_archeo/Documents/Newsletter%20September%202022%2C%20vol.%20XXXV.pdf']],start:[-32,0],end:[7,0],camp:[-46,-23],fort:[24,0],height:2,workers:52,soldiers:24,defenders:24,seed:332},
 {id:'constantinople',name:'Constantinople',date:'1453 CE',faction:'Ottoman',region:'Bosphorus',kind:'battery',theme:'coast',work:'Artillery approach',focus:'Earthworks before the land walls.',description:'Crews prepare protected gun positions and bring ammunition forward. Heavy cannon fire physical projectiles toward a miniature section of the layered land walls.',fact:'The Ottoman siege of 1453 overcame Constantinople’s defenses. The surviving land walls are part of the Historic Areas of Istanbul World Heritage property.',limit:'This model shows a selected landward sector. The coastline and buildings are schematic; cannon behavior, wall damage, units, and construction rates are illustrative. It does not model the full campaign.',sources:[['Historic Areas of Istanbul, UNESCO','https://whc.unesco.org/en/list/356/'],['Panorama 1453 History Museum','https://www.panoramikmuze.com/']],start:[-33,0],end:[-3,0],camp:[-45,-25],fort:[21,0],height:2,workers:48,soldiers:32,defenders:28,seed:1453},
 {id:'candia',name:'Candia',date:'1648–1669 CE',faction:'Ottoman',region:'Venetian Crete',kind:'trenches',theme:'coast',work:'Trenches and batteries',focus:'An approach to a bastioned city.',description:'Digging crews push zigzag trenches toward the Venetian bastions. Supply carriers move between the camp and batteries while cannon exchange fire over the earthworks.',fact:'Candia, present-day Heraklion, was a Venetian city besieged by Ottoman forces from 1648 to 1669. Contemporary maps show the fortified city and siege operations.',limit:'The star-shaped walls and trench system are schematic, not a tracing of a historical map. This compressed scenario does not reproduce twenty-one years of fighting or the underground mining campaign.',sources:[['Contemporary siege map, Royal Collection Trust','https://militarymaps.rct.uk/other-17th-century-conflicts/siege-of-candia-1648'],['Historic city, Municipality of Heraklion','https://www.heraklion.gr/en/visitor/history/tour-of-the-city.html']],start:[-34,0],end:[-2,0],camp:[-46,-25],fort:[20,0],height:2.5,workers:52,soldiers:32,defenders:28,seed:1669},
 {id:'lachish',name:'Lachish',date:'701 BCE',faction:'Assyrian',enemy:'Judahite',era:'ancient',region:'Kingdom of Judah',kind:'ramp',theme:'dry',work:'Stone siege ramp',focus:'A ramp of stone against a city mound.',description:'Haulers pile stone into a ramp against the corner of a walled mound. When it reaches the wall, a wheeled engine with a ram climbs it while archers on the walls shoot down at the works.',
  fact:'In 701 BCE the Assyrian king Sennacherib besieged and captured Lachish, one of the chief cities of the kingdom of Judah. Excavators found the Assyrians’ stone siege ramp at the south-west corner of the mound, the only Assyrian siege ramp known from archaeology, and a counter-ramp built by the defenders inside the wall opposite it. Sennacherib had the siege carved on stone panels for his palace at Nineveh; these are now in the British Museum.',
  limit:'The ramp’s original length, shape and volume are disputed, and the palace reliefs follow artistic conventions rather than showing the scene realistically. The mound, walls, ramp and engines here are schematic, and the direction of attack is turned to suit the board.',
  sources:[['Lachish relief panel, British Museum','https://www.britishmuseum.org/collection/object/W_1856-0909-14_2'],['Garfinkel et al. 2021, Constructing the Assyrian siege ramp at Lachish','https://doi.org/10.1111/ojoa.12231'],['Lachish and its siege ramps, Biblical Archaeology Society','https://library.biblicalarchaeology.org/sidebar/lachish-and-its-siege-ramps/']],
  start:[-26,0],end:[3,0],camp:[-46,-25],fort:[20,0],height:9,workers:52,soldiers:28,defenders:26,effort:1.41,seed:701,engine:'ram',finale:'Assault up the ramp',
  terrain:{type:'mesa',h:9,center:[20,0],r:[17,15],power:2.2,edge:.6,ridges:[[10,-5,10,5,2.4,2.2]]},walls:{shape:'round',r:[13,11],n:16,height:3},clear:[[10,0,4]],roofs:'flat'},
 {id:'rhodes',name:'Rhodes',date:'305–304 BCE',faction:'Antigonid',enemy:'Rhodian',era:'ancient',region:'Aegean',kind:'terraces',theme:'coast',work:'Levelled approach',focus:'A city-taker against a harbour city.',description:'Crews clear and grade a broad approach toward the walls of a harbour city. A great iron-plated tower then rolls forward while ships circle offshore.',
  fact:'In 305–304 BCE Demetrius, son of Antigonus, besieged Rhodes for about a year, first from the sea against the harbour and then by land. The historian Diodorus describes his helepolis (“city-taker”), a nine-storey wheeled tower plated with iron on three sides and pushed by picked men. The Rhodians built a second wall, dug countermines and attacked the tower with fire missiles, and the siege ended in a peace that left the city independent.',
  limit:'Ancient writers give different sizes for the helepolis, and the length of the cubit is uncertain. The harbour, walls, approach and fleet here are schematic, and the sea phase of the siege is reduced to circling ships.',
  sources:[['Diodorus Siculus 20.81–88, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Diodorus_Siculus/20D*.html'],['Diodorus Siculus 20.91–100, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Diodorus_Siculus/20E*.html'],['Antigonus I Monophthalmus, Britannica','https://www.britannica.com/biography/Antigonus-I-Monophthalmus']],
  start:[-33,0],end:[1,0],camp:[-46,-25],fort:[20,0],height:4,workers:52,soldiers:28,defenders:26,effort:1.89,seed:305,engine:'helepolis',breach:false,finale:'Peace agreed',
  terrain:{type:'rise',h:4,at:2,width:16,sea:['east',42]},walls:{height:3.2},roofs:'flat'},
 {id:'acre',name:'Acre',date:'1189–1191 CE',faction:'Crusader',enemy:'Ayyubid',era:'medieval',region:'Levant coast',kind:'rings',relief:20,theme:'coast',work:'Camp ditches and ramparts',focus:'Besiegers who are besieged.',description:'Crusader crews dig ditches and ramparts facing both the port city and the hills inland. Patrols hold the space between, and in the later phase Saladin’s field army attacks the outer line.',
  fact:'From 1189 to 1191 crusaders besieged Saladin’s garrison in the port of Acre, while Saladin’s army in turn surrounded the crusader camp on the landward side. The crusaders protected their camp with ditches and ramparts and were supplied by sea. After Philip II of France and Richard I of England arrived, mining and constant bombardment broke the walls, and the garrison surrendered in July 1191.',
  limit:'The extent and layout of the crusader lines are not well documented, and army sizes are uncertain. Here the lines are two schematic arcs, the city is simplified, and the mining and bombardment are not modelled.',
  sources:[['Itinerarium Peregrinorum, Fordham Medieval Sourcebook','https://sourcebooks.web.fordham.edu/source/1191acre.asp'],['A. V. Murray, review of Hosler, The Siege of Acre (Speculum)','https://doi.org/10.1086/711859'],['The Siege of Acre, Yale University Press','https://yalebooks.yale.edu/2020/04/14/the-siege-of-acre/']],
  start:[-35,0],end:[-10,0],camp:[-17,-6],campCols:4,campRows:3,fort:[24,0],height:2,workers:48,soldiers:32,defenders:26,effort:1.52,seed:1191,finale:'Saladin’s army attacks',
  terrain:{type:'plain',h:.6,sea:['east',40]},rings:{center:[24,0],inner:[22,19],outer:[44,32],arc:[PI/2-.3,PI*1.5+.3]},walls:{shape:'round',r:[12,11],n:14,height:3.2},roofs:'flat'},
 {id:'gaillard',name:'Château Gaillard',date:'1203–1204 CE',faction:'French',enemy:'Angevin',era:'medieval',region:'Normandy',kind:'trenches',theme:'green',work:'Ditches and mines',focus:'Undermining a castle on a spur.',description:'Diggers push covered approaches along the spur toward the castle while stone-throwing engines are brought forward. Crossbowmen on the walls shoot at the works.',
  fact:'Richard I of England had Château Gaillard built in 1196–1198 on a chalk spur above the Seine. Philip II of France blockaded it from September 1203 behind a double ditch, and in February 1204 his miners brought down the great tower of the outer work. The French then got into the next court through a building beside the chapel, breached the last wall, and took the castle on 6 March 1204.',
  limit:'Most detail comes from one partisan eyewitness, William the Breton, the French king’s chaplain, whose verse and prose accounts differ on how the attackers got in. The castle here is a simplified concentric plan, and the blockade line and mining are shown as approach trenches.',
  sources:[['Siège de Château-Gaillard, Encyclopædia Universalis','https://www.universalis.fr/encyclopedie/siege-de-chateau-gaillard/'],['William the Breton, Philippide VII','https://remacle.org/bloodwolf/historiens/guillaumelebreton/philippide7.htm'],['Les Andelys, Château Gaillard, ADLFI archaeology notice','https://doi.org/10.4000/adlfi.12220']],
  start:[-34,0],end:[4,0],camp:[-46,-25],fort:[22,0],height:3,workers:48,soldiers:28,defenders:22,effort:0.91,seed:1204,engine:'trebuchet',finale:'Walls breached',
  terrain:{type:'mesa',h:9,center:[22,0],r:[14,12],spur:[-42,8,8,3],river:['x',53,14]},walls:{shape:'round',r:[11,9],n:12,height:3.6,thickness:1.2},features:['keep','innerWall','chapel'],houses:.25,roofs:'tile'},
 {id:'orleans',name:'Orléans',date:'1428–1429 CE',faction:'English',enemy:'French',era:'medieval',region:'Loire valley',kind:'rings',relief:20,theme:'green',work:'Siege forts and earthworks',focus:'A ring of forts on the Loire.',description:'English crews raise earthworks in an arc around a river city, with a fortified bridgehead across the water. In the later phase a relief army marches on the English lines.',
  fact:'From October 1428 an English army besieged Orléans, holding the bridge fort of Les Tourelles on the south bank of the Loire and building a near-ring of forts around the city. Both sides made heavy use of gunpowder artillery. Joan of Arc entered the city with supplies in late April 1429, the French stormed Les Tourelles on 7 May, and the English withdrew on 8 May.',
  limit:'The number, names and exact positions of the English forts vary between accounts, and sources differ by a few days on some dates. The forts are drawn here as continuous earthwork arcs, and the guns are not modelled.',
  sources:[['Siege of Orléans, Britannica','https://www.britannica.com/event/Siege-of-Orleans'],['Saint Joan of Arc, Britannica','https://www.britannica.com/biography/Saint-Joan-of-Arc'],['K. DeVries, Gunpowder weaponry and Joan of Arc (War & Society)','https://doi.org/10.1179/072924796791200889']],
  start:[-35,0],end:[-10,0],camp:[-31,-2],campCols:4,campRows:3,fort:[6,0],height:2,workers:48,soldiers:32,defenders:26,effort:1.17,seed:1429,reliefFrom:[-55,-20],finale:'Relief army arrives',
  terrain:{type:'plain',h:.5,river:['z',24,12]},rings:{center:[6,0],inner:[24,17],outer:[40,27],arc:[PI-.15,PI*2+.15]},walls:{scale:[.75,.6],height:3.2},features:['bridgeFort'],roofs:'tile'},
 {id:'vienna',name:'Vienna',date:'1683 CE',faction:'Ottoman',enemy:'Habsburg',era:'early modern',region:'Danube',kind:'trenches',relief:22,theme:'green',work:'Approach trenches and mines',focus:'Trenches against bastions, and a relief.',description:'Ottoman crews dig zigzag approaches toward the bastions while batteries fire. In the later phase a relief army comes down from the heights and attacks the siege lines.',
  fact:'In July 1683 an Ottoman army under Grand Vizier Kara Mustafa surrounded Vienna, a city defended by bastions, ravelins and a wide ditch. Ottoman troops dug approach trenches and mines against the bastions in front of the imperial palace, while about 16,000 soldiers and citizens under Starhemberg held out. On 12 September 1683 a relief army under King Jan III Sobieski of Poland and Charles of Lorraine came down from the Kahlenberg heights and drove the Ottomans away.',
  limit:'Army sizes differ widely between sources, and the start of the siege is given as 14 or 17 July. The bastions, trenches and river are schematic, and the relief battle is reduced to a skirmish at the siege lines.',
  sources:[['Zweite Türkenbelagerung (1683), Wien Geschichte Wiki','https://www.geschichtewiki.wien.gv.at/Zweite_T%C3%BCrkenbelagerung_(1683)'],['Stadtbefestigung, Wien Geschichte Wiki','https://www.geschichtewiki.wien.gv.at/Stadtbefestigung'],['Merzifonlu Kara Mustafa Paşa, Britannica','https://www.britannica.com/biography/Merzifonlu-Kara-Mustafa-Pasa']],
  start:[-34,0],end:[-5,0],camp:[-46,-25],fort:[22,0],height:2,workers:52,soldiers:32,defenders:28,seed:1683,breach:false,reliefFrom:[-56,30],reliefLine:[-44,17],finale:'Relief army arrives',
  terrain:{type:'plain',h:.6,river:['z',-39,10]},walls:{shape:'star',n:12,r:[22,15],height:3.6,thickness:1.9},roofs:'tile'},
 {id:'carthage',name:'Carthage',date:'149–146 BCE',faction:'Roman',enemy:'Carthaginian',era:'ancient',region:'North Africa',kind:'causeway',theme:'coast',work:'Harbour mole',focus:'A mole toward the harbour mouth.',description:'Haulers carry stone from the shore to build a mole across open water toward the harbour entrance of a walled city. Towers follow along the finished surface.',
  fact:'Appian reports that Scipio walled off the isthmus and then built a stone-filled mole into the sea to close the harbour entrance. The Carthaginians answered by secretly digging a new channel from the harbour to the open sea and sailing out a fleet. The city fell in spring 146 BCE after street fighting, and the Romans destroyed it.',
  limit:'Most detail comes from Appian, generally thought to draw on Polybius, and his directions are simplified, so the mole’s exact line is a reconstruction; no remains of it have been located. The city, harbours and isthmus here are schematic.',
  sources:[['Appian, Punic Wars 117–126, Perseus','https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0230%3Atext%3DPun.%3Achapter%3D18'],['H. Hurst, Understanding Carthage as a Roman port','https://bollettinodiarcheologiaonline.beniculturali.it/wp-content/uploads/2019/01/6_Hurst_paper.pdf'],['Third Punic War, Britannica','https://www.britannica.com/event/Third-Punic-War']],
  start:[-31,0],end:[5,0],camp:[-46,-23],fort:[24,0],height:2,workers:52,soldiers:28,defenders:26,effort:1.08,seed:146,cartReach:-2,finale:'Storming the city',
  terrain:{type:'coastline',shore:[-32,7],h:.5,land:[[24,0,17,22,2.2],[24,-34,8,13,1.4]],bumps:[[18,11,-6,9]]},walls:{shape:'round',r:[14,19],n:16,height:3.2},clear:[[18,11,5]],features:['cothon'],roofs:'flat',tall:true},
 {id:'numantia',name:'Numantia',date:'134–133 BCE',faction:'Roman',enemy:'Celtiberian',era:'ancient',region:'Hispania',kind:'rings',theme:'dry',work:'Circumvallation',focus:'A blockade instead of an assault.',description:'Roman crews close a hilltop town inside a ring of ditch, palisade and towered wall. In the later phase the defenders try to break out against the lines.',
  fact:'Instead of storming Numantia, Scipio Aemilianus surrounded it with ditches, a palisade and a towered wall, and Appian says he blocked the river with floating timbers studded with blades. Starved, the Numantines surrendered in 133 BCE, and Scipio destroyed the town. Adolf Schulten excavated the city in 1905 and the Roman camps around it between 1906 and 1912.',
  limit:'Sources differ on the length of the blockade, the number of camps (six or seven) and the length of the ring (about 9–10 km), and Schulten’s plan of the siege works is still debated. The two schematic rings here stand for the full system of camps and walls.',
  sources:[['Appian, Wars in Spain 90–98, Perseus','https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0230%3Atext%3DHisp.%3Achapter%3D15'],['Numancia, Junta de Castilla y León','https://www.jcyl.es/jcyl/patrimoniocultural/GuiaLugaresArqueologicos/soria/04soria/index.html'],['Numantia, Britannica','https://www.britannica.com/place/Numantia']],
  start:[-35,0],end:[-10,0],camp:[-38.5,-4],campCols:3,campRows:3,cartLane:14,fort:[0,0],height:2,workers:48,soldiers:32,defenders:28,effort:1.0,seed:133,finale:'Breakout attempts',
  terrain:{type:'hill',h:7,center:[0,0],r:[15,12],river:['z',38,8]},rings:{inner:[27,20],outer:[42,30]},walls:{shape:'round',r:[12,10],n:14,height:3},roofs:'thatch'},
 {id:'avaricum',name:'Avaricum',date:'52 BCE',faction:'Roman',enemy:'Gallic (Bituriges)',era:'ancient',region:'Gaul',kind:'ramp',theme:'green',work:'Siege terrace (agger)',focus:'One narrow way through the marshes.',description:'Legionaries raise a broad earth-and-timber terrace along the only dry approach to a town ringed by river and marsh. Towers advance on it toward the Gallic rampart.',
  fact:'Caesar reports that his army built a siege ramp about 330 feet wide and 80 feet high in 25 days of cold and rain, while the defenders tried to undermine and burn it. The town was taken by assault in a rainstorm. Excavations in Bourges have found a large ditch across the south of the promontory, which researchers match to the narrow approach Caesar describes.',
  limit:'The ramp itself has not been located by excavation, and it is unconfirmed whether the town’s rampart was a timber-laced Gallic wall. Caesar’s casualty figures cannot be checked. The marsh, ramp and town here are schematic.',
  sources:[['Caesar, Gallic War VII, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Caesar/Gallic_War/7C*.html'],['L. Augier et al. 2024, Topography of Bourges in the Iron Age','https://doi.org/10.46608/basic1.9782356134929.18'],['Bourges, Britannica','https://www.britannica.com/place/Bourges']],
  start:[-31,0],end:[5,0],camp:[-45,-24],fort:[20,0],height:6,workers:52,soldiers:28,defenders:28,effort:1.12,seed:52.5,weather:'rain',finale:'Assault in the rain',
  terrain:{type:'hill',h:6,center:[20,0],r:[15,13],marsh:[20,0,18,16,7],river:['x',55,12]},walls:{scale:[.68,.6],height:3.2},features:['turrets'],roofs:'thatch'},
 {id:'uxellodunum',name:'Uxellodunum',date:'51 BCE',faction:'Roman',enemy:'Gallic (Cadurci)',era:'ancient',region:'Gaul',kind:'ramp',theme:'green',work:'Ramp, tower and mines',focus:'Win by taking the water.',description:'Crews build a ramp below a cliff-ringed town, toward the spring the defenders depend on. A tall tower rises on it to command the path to the water.',
  fact:'Hirtius reports that Caesar could not storm the cliff-ringed town, so he set out to cut off its water. His men built a 60-foot ramp with a ten-storey tower to command the spring and dug tunnels to its source until it dried up, and the defenders surrendered. Excavations at the Fontaine de Loulié on the Puy d’Issolud found tunnels interpreted as Roman galleries and Gallic counter-mines, along with hundreds of arrowheads.',
  limit:'The site’s location was disputed for a long time before the Puy d’Issolud was accepted after Jean-Pierre Girault’s excavations. The ramp and tower dimensions come only from Hirtius. The tunnels are not modelled, and the walls here do not fall.',
  sources:[['Caesar (Hirtius), Gallic War VIII, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Caesar/Gallic_War/8A*.html'],['J.-M. Pailler, review of Girault, La Fontaine de Loulié (Pallas)','https://doi.org/10.4000/pallas.2404'],['Uxellodunum, Mairie de Vayrac','https://www.vayrac.fr/tourisme/uxellodunum']],
  start:[-30,0],end:[3,0],camp:[-45,-24],fort:[22,0],height:7,workers:48,soldiers:28,defenders:24,effort:0.9,seed:51,engine:'tower',stories:8,breach:false,finale:'Spring cut off',
  terrain:{type:'mesa',h:12,center:[22,0],r:[15,13],marsh:[22,0,19,17,6,-2.6]},walls:{shape:'round',r:[12,10],n:14,height:2.8},features:['spring'],roofs:'thatch'},
 {id:'massilia',name:'Massilia',date:'49 BCE',faction:'Roman',enemy:'Massiliote Greek',era:'ancient',region:'Gaul (Provence)',kind:'terraces',theme:'coast',work:'Siege ramp and brick tower',focus:'Rebuilt in brick after the fire.',description:'Legionaries drive a siege ramp, sheds and a brick tower against the land side of a Greek city with the sea on three sides.',
  fact:'Caesar’s legate Trebonius drove a siege ramp, sheds and towers against the land side of this Greek city, which the sea washed on three sides. Under fire from catapults on the walls, his men built a six-storey brick tower and a 60-foot covered gallery that let them undermine a city tower. After a surprise sortie burned the wooden works, the Romans rebuilt in brick, and Massilia surrendered later in 49 BCE.',
  limit:'The detailed account is Caesar’s own, and he was a party to the war. No archaeological trace of the Roman siege works has been identified. The city and coast here are schematic, and the fire and rebuilding are not modelled.',
  sources:[['Caesar, Civil War II, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Caesar/Civil_Wars/2A*.html'],['La Bourse, INRAP archaeological atlas of Marseille','https://multimedia.inrap.fr/atlas/marseille/sites/2878/La-Bourse'],['Marseille, Britannica','https://www.britannica.com/place/Marseille/Administration-and-social-conditions']],
  start:[-33,0],end:[6,0],camp:[-46,-25],fort:[24,0],height:3.5,workers:52,soldiers:28,defenders:26,effort:3.13,seed:49,engine:'brick',stories:6,breach:false,finale:'City surrenders',
  terrain:{type:'coastline',shore:[10,0],h:.6,land:[[24,0,16,15,3]]},walls:{shape:'round',r:[13,12],n:16,height:3.4},roofs:'tile'},
 {id:'perusia',name:'Perusia',date:'41–40 BCE',faction:'Octavian',enemy:'Antonian',era:'ancient',region:'Etruria',kind:'rings',theme:'green',work:'Ditch and towered wall',focus:'Romans against Romans.',description:'Octavian’s crews ring a hill town with a ditch and a wall of wooden towers. In the later phase the besieged try to break out while slingers on both sides exchange lead shot.',
  fact:'Appian says Octavian ringed the hill town of Perusia with a ditch and wall about 56 stades around, later deepening the ditch to 30 feet and adding wooden towers. After failed breakouts and famine, Lucius Antonius surrendered in early 40 BCE, and the town burned. Lead sling bullets from the siege, some inscribed with unit names or insults, survive in museums in Perugia and Oxford.',
  limit:'The size of the works and the number of towers are Appian’s figures, and the lines have not been traced on the ground. Sling bullets were cast by both sides, and readings of individual bullets are still revised. The rings here are schematic.',
  sources:[['Appian, Civil Wars 5.30–38, Perseus','https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0232%3Abook%3D5%3Achapter%3D4'],['Lead sling bullet from Perusia, Ashmolean Museum','https://latininscriptions.ashmus.ox.ac.uk/xml/AN_Fortnum_V_241.xml'],['Sling bullet, Perugia, Italian Ministry of Culture catalogue','https://catalogo.beniculturali.it/detail/ArchaeologicalProperty/1000156554']],
  start:[-35,0],end:[-10,0],camp:[-38.5,-4],campCols:3,campRows:3,cartLane:14,fort:[0,0],height:2,workers:48,soldiers:32,defenders:28,effort:1.0,seed:40,finale:'Breakout attempts',
  terrain:{type:'hill',h:9,center:[0,0],r:[16,13],bumps:[[-6,8,2.5,40],[7,-6,2,50]],river:['x',55,10]},rings:{inner:[27,20],outer:[42,30]},walls:{shape:'round',r:[12,10],n:13,height:3},roofs:'tile'},
 {id:'jotapata',name:'Jotapata',date:'67 CE',faction:'Roman',enemy:'Jewish rebels',era:'ancient',region:'Galilee',kind:'ramp',theme:'dry',work:'Assault bank',focus:'A bank against a rising wall.',description:'Crews raise an earth-and-timber bank up the one approachable side of a cliff-top town, while the defenders build their wall higher. Towers climb the finished bank.',
  fact:'Josephus, who commanded the town’s defenders, reports that the Romans built an earth-and-timber bank against the north wall while he raised the wall higher behind screens of ox-hide. After 47 days the bank stood above the wall, and Roman soldiers climbed in before dawn. Excavations on the northern slope uncovered a deep layer of soil, fieldstones and mortar that the archaeologists identify as the Roman assault ramp, along with arrowheads, catapult bolts and ballista stones.',
  limit:'The siege’s length and its death toll come from Josephus alone, and his own dates do not quite agree with each other. Archaeologists found the ramp’s remains but not its full size. The town and bank here are schematic and turned to suit the board.',
  sources:[['Josephus, Jewish War III','https://penelope.uchicago.edu/josephus/war-3.html'],['Yodfat, New Encyclopedia of Archaeological Excavations in the Holy Land','https://library.biblicalarchaeology.org/book/the-new-encyclopedia-of-archaeological-excavations-in-the-holy-land/yodfat/'],['Adan-Bayewitz and Aviam 1997, Journal of Roman Archaeology','https://doi.org/10.1017/S1047759400014768']],
  start:[-31,0],end:[4,0],camp:[-45,-24],fort:[20,0],height:10,workers:52,soldiers:28,defenders:26,effort:2.52,seed:67,finale:'Assault over the bank',
  terrain:{type:'mesa',h:10,center:[20,0],r:[14,13],spur:[-40,6,8]},walls:{shape:'round',r:[11,10],n:14,height:3},roofs:'flat'},
 {id:'gamla',name:'Gamla',date:'67 CE',faction:'Roman',enemy:'Jewish rebels',era:'ancient',region:'Golan',kind:'ramp',theme:'dry',work:'Earth banks and rams',focus:'A town on a camel’s hump.',description:'Crews build banks along the saddle toward a ridge-top town. Battering rams follow, and the defenders shoot down from the wall.',
  fact:'Josephus reports that the Romans raised earth banks on the town’s east side and broke the wall with battering rams in three places, but the defenders drove back their first assault. Excavations found a five-metre breach in the middle of the eastern wall, with ballista stones and arrowheads scattered around it.',
  limit:'The casualty figures and the mass leap from the cliffs come only from Josephus. Archaeology confirms the breach and the bombardment but cannot test those numbers. The ridge, town and banks here are schematic and turned to suit the board.',
  sources:[['Josephus, Jewish War IV','https://penelope.uchicago.edu/josephus/war-4.html'],['Gamla, Jewish Virtual Library (Israel Ministry of Foreign Affairs text)','https://jewishvirtuallibrary.org/gamla'],['Gamala, New Encyclopedia of Archaeological Excavations in the Holy Land','https://library.biblicalarchaeology.org/book/the-new-encyclopedia-of-archaeological-excavations-in-the-holy-land/gamala/']],
  start:[-30,0],end:[3,0],camp:[-45,-24],fort:[22,0],height:9.5,workers:48,soldiers:28,defenders:26,effort:2.11,seed:670,engine:'ram',finale:'Breach opened',
  terrain:{type:'mesa',h:10,center:[22,0],r:[20,8],power:2.6,spur:[-40,4,7,2.5]},walls:{shape:'round',r:[15,5.5],n:14,height:2.6},roofs:'flat'},
 {id:'machaerus',name:'Machaerus',date:'71 / 72 CE',faction:'Roman',enemy:'Jewish rebels',era:'ancient',region:'Peraea',kind:'rings',theme:'desert',work:'Siege wall and camps',focus:'A wall around a hilltop fortress.',description:'Roman crews ring a conical hill with a siege wall and small camps. An unfinished assault ramp climbs one slope, and the defenders sortie against the works.',
  fact:'Josephus reports that Bassus began filling a valley to build a siege bank, but the defenders surrendered after the Romans captured one of their young fighters and threatened to crucify him. Surveys around the hill recorded a Roman siege wall ringed with camps and an assault ramp that was never finished.',
  limit:'Sources differ on the year (71 or 72 CE) and on the number of Roman camps. Josephus places the siege bank on the east, but the surviving unfinished ramp lies north-west of the fortress. The hill, wall and camps here are schematic.',
  sources:[['Josephus, Jewish War VII','https://penelope.uchicago.edu/josephus/war-7.html'],['M. J. F. Fowler, AARGnews 64 (2022)','https://aargonline.com/wp/wp-content/uploads/2022/10/AARGnews64.pdf'],['Gy. Vörös, Archaeological missions to Machaerus (SHAJ 13)','https://publication.doa.gov.jo/uploads/publications/208/SHAJ_2019_13_-321-336.pdf']],
  start:[-35,0],end:[-10,0],camp:[-58,-40],fort:[0,0],height:2,workers:48,soldiers:28,defenders:24,effort:0.73,seed:72,finale:'Sorties against the works',
  terrain:{type:'hill',h:14,center:[0,0],r:[14,12],top:.25,edge:.9,ridges:[[-26,-13,-15,-7,5,3.5]]},rings:{single:true,inner:[34,26]},walls:{shape:'round',r:[9,7],n:12,height:3},features:['citadel','ringCamps'],houses:.5,roofs:'flat'},
 {id:'hatra',name:'Hatra',date:'c. 198–199 CE',faction:'Roman',enemy:'Hatrene Arab',era:'ancient',region:'Upper Mesopotamia',kind:'battery',theme:'desert',work:'Engine emplacements',focus:'Engines against a round desert city.',description:'Roman crews prepare positions for siege engines before the round double walls of a desert city. Archers on the walls shoot back, and the walls hold.',
  fact:'Cassius Dio reports that Severus attacked Hatra twice and both times lost his siege engines, many of them burned. When part of the outer wall finally fell, Severus called his troops back, hoping the city would surrender, and the chance was lost. Hatra’s walls, laid out in a near circle, held the city against both Trajan and Severus.',
  limit:'Modern dates for the two attempts range from 197 to 199 CE, and Herodian’s description of the site does not match the flat desert. The engines, walls and temple here are schematic, and the burning of the engines is not modelled.',
  sources:[['Cassius Dio, Roman History 76, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Cassius_Dio/76*.html'],['Hatra, UNESCO World Heritage Centre','https://whc.unesco.org/en/list/277/'],['Hatra, Britannica','https://www.britannica.com/place/Hatra']],
  start:[-34,0],end:[-1,0],camp:[-46,-25],fort:[24,0],height:2,workers:48,soldiers:32,defenders:28,seed:198,engine:'ballista',breach:false,finale:'Severus withdraws',
  terrain:{type:'plain',h:.4,ditch:[24,0,22.4,22.4,.95,2.2]},walls:{shape:'round',r:[19,19],n:24,height:3.4},features:['innerRing','temple'],roofs:'flat'},
 {id:'dura',name:'Dura-Europos',date:'c. 256 CE',faction:'Sasanian Persian',enemy:'Roman garrison',era:'ancient',region:'Euphrates',kind:'ramp',theme:'desert',work:'Siege ramp and mines',focus:'Ramps, mines, and a buried street.',description:'Persian crews build a ramp toward the desert wall of a Roman-held city above the Euphrates, while the garrison banks earth behind its own wall.',
  fact:'No written account of this siege survives; what is known comes from excavations by Yale University and the French Academy (1928–1937). The Persians dug mines under the western wall and built a large brick-and-earth ramp, while the Roman garrison buried the buildings along the wall in an earth bank to strengthen it. In a Roman countermine near Tower 19, excavators found the remains of about 20 soldiers.',
  limit:'The idea that the soldiers in the Tower 19 countermine were killed by Persian smoke is a recent reinterpretation by Simon James; the original excavator thought they died by sword or fire. How the city finally fell is unknown, so the walls here do not break. The mines are not modelled.',
  sources:[['S. James 2011, Stratagems, combat and chemical warfare in the siege mines of Dura-Europos (AJA)','https://ajaonline.org/article/360/'],['Dura-Europos, Yale University Art Gallery','https://duraeuropos.artgallery.yale.edu/'],['Dura-Europos: archaeology and history, Encyclopaedia Iranica','https://www.iranicaonline.org/articles/dura-europos/dura-europos-i-archaeology-and-history/']],
  start:[-31,0],end:[3,0],camp:[-45,-24],fort:[22,0],height:6.2,workers:52,soldiers:28,defenders:26,effort:1.18,seed:256,breach:false,finale:'The city falls',
  terrain:{type:'mesa',h:6,center:[22,0],r:[18,16],power:6,river:['x',52,14],ridges:[[9.6,-12,9.6,12,1.3,1.5]]},walls:{scale:[.9,.8],height:3.2},clear:[[10,-8,3],[10,0,3],[10,8,3]],roofs:'flat'},
 {id:'amida',name:'Amida',date:'359 CE',faction:'Sasanian Persian',enemy:'Roman garrison',era:'ancient',region:'Upper Tigris',kind:'ramp',theme:'dry',work:'Siege mounds and towers',focus:'Mound against mound.',description:'Persian crews heap a great mound toward the walls, with a second mound beside it, while the garrison raises its own mound behind the wall.',
  fact:'Ammianus Marcellinus, a Roman officer inside the city, describes Persian siege towers and two great earth mounds raised against the walls, while the defenders built their own mound behind the wall to match them. After 73 days the Roman mound collapsed forward and formed a bridge for the attackers, and the city was taken. Ammianus escaped at night through an unguarded side gate.',
  limit:'Almost everything comes from Ammianus’ eyewitness account, including his large figures for people and casualties. He does not say which side of the city the mounds faced. The mounds, walls and river here are schematic, and the collapse of the Roman mound is not modelled.',
  sources:[['Ammianus Marcellinus 19, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/19*.html'],['Ammianus Marcellinus 18, LacusCurtius','https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/18*.html'],['Ancient Iran: the Sasanian period, Britannica','https://www.britannica.com/place/ancient-Iran/The-Sasanian-period']],
  start:[-31,0],end:[2,0],camp:[-45,-24],fort:[20,0],height:7.2,workers:52,soldiers:28,defenders:28,effort:1.03,seed:359,finale:'Assault over the mounds',
  terrain:{type:'mesa',h:7,center:[20,0],r:[17,15],power:3,river:['z',37,10],bumps:[[-6,9,3.2,30]],ridges:[[8.5,-3,8.5,3,2.4,2.2]]},walls:{height:3.4},clear:[[9,0,4]],roofs:'flat'}
];
// The first six worlds keep their original landforms.
Object.assign(SCENARIOS[0],{enemy:'Jewish rebels',era:'ancient',terrain:'masada',walls:{shape:'poly',points:[[-12,-23],[11,-23],[13,-15],[12,21],[5,24],[-12,21]]},features:['palace'],roofs:'flat',finale:'Breach opened'});
Object.assign(SCENARIOS[1],{effort:.67,enemy:'Gallic',era:'ancient',terrain:'alesia',camp:[-60,-42],cartReach:-5,roofs:'thatch',finale:'Relief force approaching'});
Object.assign(SCENARIOS[2],{enemy:'Jewish defenders',era:'ancient',terrain:'jerusalem',features:['innerWalls','fortress'],roofs:'flat',finale:'Breach opened'});
Object.assign(SCENARIOS[3],{enemy:'Tyrian',era:'ancient',terrain:'tyre',cartReach:-2,roofs:'flat',tall:true,finale:'Breach opened'});
Object.assign(SCENARIOS[4],{enemy:'Byzantine',era:'medieval',terrain:{type:'rise',h:2,seaStep:29},walls:{height:5},features:['landWalls'],engine:'bombard',roofs:'tile',finale:'Breach opened'});
Object.assign(SCENARIOS[5],{enemy:'Venetian',era:'early modern',terrain:{type:'rise',h:2.5,seaStep:29},walls:{shape:'star',n:14,r:[24,17],height:3.6,thickness:1.9},roofs:'tile',finale:'Breach opened'});
// Clothing and kit are broad period cues for the miniature, not reconstructions of particular units.
const LABOR={tunic:['#c7af87','#eee1be','#b8a07a'],head:'cap',headColor:'#9b8663',legs:'#675f4d'},LABOR_EAST={...LABOR,head:'wrap',headColor:'#ebe3cf'};
const ROMAN={tunic:['#a94e3d','#9c4434'],head:'helmet',headColor:'#8e978f',crest:'#b33b2a',shield:'rect',shieldColor:'#a3402f',weapon:'sword',legs:'#6b5c48'};
const JUDAEAN={tunic:['#b59f78','#8e7d60','#a58d6a','#c9b892'],head:'wrap',headColor:'#d8cdb3',shield:'round',shieldColor:'#8a6a45',weapon:'spear',legs:'#6e6250'};
const GAUL={tunic:['#6f8a5a','#a8843f','#5f7590','#8c5a3c'],head:'hair',headColor:'#6b4a2e',shield:'oval',shieldColor:'#7d6a46',weapon:'spear',legs:'#7a6a50'};
const MACEDONIAN={tunic:['#8f4a3a','#a46a4a'],head:'helmet',headColor:'#b08d57',shield:'round',shieldColor:'#b08d57',weapon:'pike',legs:'#6b5c48'};
const TYRIAN={tunic:['#b9a27a','#7d6a8e','#9c8a64'],head:'cap',headColor:'#7d6a5a',shield:'round',shieldColor:'#8c6c48',weapon:'spear',legs:'#6e6250'};
const OTTOMAN={tunic:['#9c3b33','#3f5a7a','#c19a48','#7a3f5a'],head:'bork',headColor:'#efe8d6',shield:'round',shieldColor:'#9b7b4b',weapon:'sword',legs:'#5d5446'};
const BYZANTINE={tunic:['#7a2f3a','#4e5f7d','#8a7a5a'],head:'helmet',headColor:'#8f948f',shield:'round',shieldColor:'#7a2f3a',weapon:'spear',legs:'#5f5a50'};
const VENETIAN={tunic:['#8a2b2b','#3c4f6b','#6d6a5f'],head:'morion',headColor:'#9aa09c',shield:'none',weapon:'musket',legs:'#4f4b45'};
const ASSYRIAN={tunic:['#8a5a3a','#a07048'],head:'cone',headColor:'#9a9a8c',shield:'round',shieldColor:'#8c6e46',weapon:'spear',legs:'#5d5446'};
const GREEK={tunic:['#b44a3a','#c9b48a','#6c7a8c'],head:'helmet',headColor:'#b08d57',shield:'round',shieldColor:'#a8834e',weapon:'spear',legs:'#6b5c48'};
const CARTHAGINIAN={tunic:['#d6cdb5','#8a6a7a','#9a8a6a'],head:'helmet',headColor:'#a68a55',shield:'round',shieldColor:'#c2a56d',weapon:'spear',legs:'#6b5c48'};
const CELTIBERIAN={tunic:['#6d5a45','#8b7a5c','#5f6a55'],head:'hair',headColor:'#4a3a2a',shield:'round',shieldColor:'#6e5b3e',weapon:'spear',legs:'#5a4f40'};
const ANTONIAN={...ROMAN,tunic:['#6f8696','#5f7585'],shieldColor:'#4f6b80',crest:'#d8d0b8'};
const ARAB={tunic:['#d9cdb0','#a67c52','#7c6a52'],head:'wrap',headColor:'#ece4d0',shield:'round',shieldColor:'#8c6c48',weapon:'spear',legs:'#6e6250'};
const SASANIAN={tunic:['#8e3b46','#5b6d8a','#b98c3e'],head:'helmet',headColor:'#9a9c96',shield:'round',shieldColor:'#7a5a3a',weapon:'spear',legs:'#5a4a40'};
const LATE_ROMAN={tunic:['#e3ddcc','#b0544a'],head:'helmet',headColor:'#9aa09a',shield:'oval',shieldColor:'#b0544a',weapon:'spear',legs:'#5f5448'};
const CRUSADER={tunic:['#e6e0d0','#a33a2e','#3e5a8a'],head:'helmet',headColor:'#a3a8a6',shield:'rect',shieldColor:'#c9c0aa',weapon:'spear',legs:'#5d5850'};
const AYYUBID={tunic:['#d8c39a','#7d8a5a','#b46a3a'],head:'wrap',headColor:'#efe8d6',shield:'round',shieldColor:'#a07a48',weapon:'spear',legs:'#6a5d4a'};
const FRENCH={tunic:['#3d5a8a','#c9b77a','#7a3a3a'],head:'helmet',headColor:'#a3a8a6',shield:'rect',shieldColor:'#3d5a8a',weapon:'spear',legs:'#5a5550'};
const ANGEVIN={tunic:['#a33a2e','#c9a24a','#6a5a4a'],head:'helmet',headColor:'#a3a8a6',shield:'rect',shieldColor:'#a33a2e',weapon:'spear',legs:'#5a5550'};
const ENGLISH={tunic:['#e8e2d4','#a33a2e'],head:'helmet',headColor:'#a3a8a6',shield:'none',weapon:'spear',legs:'#5a5550'};
const FRENCH_LATE={tunic:['#3d5a8a','#e8e2d4'],head:'helmet',headColor:'#a3a8a6',shield:'none',weapon:'musket',legs:'#5a5550'};
const HABSBURG={tunic:['#d9d4c6','#6b7d94','#8a3a35'],head:'hat',headColor:'#3e3a36',shield:'none',weapon:'musket',legs:'#4f4b45'};
const RELIEF_1683={tunic:['#a3352e','#3c5a86','#d4b45a'],head:'helmet',headColor:'#9aa09c',shield:'none',weapon:'sword',legs:'#4f4b45'};
const DRESS={masada:{worker:LABOR,soldier:ROMAN,defender:JUDAEAN,missile:'arrow'},alesia:{worker:LABOR,soldier:ROMAN,defender:GAUL,relief:{...GAUL,tunic:['#7f8f5e','#9b7b45','#6a6f86']},missile:'arrow'},jerusalem:{worker:LABOR,soldier:ROMAN,defender:JUDAEAN,missile:'arrow'},tyre:{worker:LABOR,soldier:MACEDONIAN,defender:TYRIAN,missile:'arrow'},constantinople:{worker:LABOR_EAST,soldier:OTTOMAN,defender:BYZANTINE,missile:'arrow'},candia:{worker:LABOR_EAST,soldier:{...OTTOMAN,shield:'none',weapon:'musket'},defender:VENETIAN,missile:'musket'},
 lachish:{worker:LABOR,soldier:ASSYRIAN,defender:{...JUDAEAN,shield:'none'},missile:'arrow'},rhodes:{worker:LABOR,soldier:MACEDONIAN,defender:GREEK,missile:'arrow'},acre:{worker:LABOR,soldier:CRUSADER,defender:AYYUBID,relief:{...AYYUBID,tunic:['#c9a46a','#6d7a52','#9a5a3a']},missile:'arrow'},gaillard:{worker:LABOR,soldier:FRENCH,defender:ANGEVIN,missile:'arrow'},orleans:{worker:LABOR,soldier:ENGLISH,defender:FRENCH_LATE,relief:{...FRENCH_LATE,weapon:'spear'},missile:'musket'},vienna:{worker:LABOR_EAST,soldier:{...OTTOMAN,shield:'none',weapon:'musket'},defender:HABSBURG,relief:RELIEF_1683,missile:'musket'},
 carthage:{worker:LABOR,soldier:ROMAN,defender:CARTHAGINIAN,missile:'arrow'},numantia:{worker:LABOR,soldier:ROMAN,defender:CELTIBERIAN,missile:'arrow'},avaricum:{worker:LABOR,soldier:ROMAN,defender:GAUL,missile:'arrow'},uxellodunum:{worker:LABOR,soldier:ROMAN,defender:GAUL,missile:'arrow'},massilia:{worker:LABOR,soldier:ROMAN,defender:GREEK,missile:'arrow'},perusia:{worker:LABOR,soldier:ROMAN,defender:ANTONIAN,missile:'sling'},
 jotapata:{worker:LABOR,soldier:ROMAN,defender:JUDAEAN,missile:'arrow'},gamla:{worker:LABOR,soldier:ROMAN,defender:JUDAEAN,missile:'arrow'},machaerus:{worker:LABOR,soldier:ROMAN,defender:JUDAEAN,missile:'arrow'},hatra:{worker:LABOR,soldier:ROMAN,defender:ARAB,missile:'arrow'},dura:{worker:LABOR_EAST,soldier:SASANIAN,defender:LATE_ROMAN,missile:'arrow'},amida:{worker:LABOR_EAST,soldier:SASANIAN,defender:LATE_ROMAN,missile:'arrow'}};
for(const s of SCENARIOS)s.dress=DRESS[s.id];
export const scenarioById=id=>SCENARIOS.find(s=>s.id===id)||SCENARIOS[0];
