import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {naturalHeight,workPoint,fortressOutline,clamp,wallProfile} from './simulation.js';
import {TERRAIN,terrainIndices,PERSON_ORIGIN,containsPoint,insidePolygon} from './collision.js';
const palette={sand:'#c9b68f',stone:'#e4d9bf',cream:'#f4ecda',darkStone:'#b6a58a',wood:'#887453',roof:'#bd8064',red:'#a94e3d',green:'#7d9372',water:'#91b9b6',metal:'#7c8881',skin:'#dfb994'};
export class MiniatureScene{
 constructor(canvas,sim,physics){this.canvas=canvas;this.sim=sim;this.physics=physics;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#dde3da');this.scene.fog=new THREE.Fog('#dde3da',210,400);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;this.camera=new THREE.PerspectiveCamera(38,1,.1,450);this.camera.position.set(-91,84,103);this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(2,7,0);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.maxPolarAngle=Math.PI*.46;this.controls.minDistance=9;this.controls.maxDistance=215;this.controls.zoomSpeed=.85;this.controls.panSpeed=.65;this.scene.add(new THREE.HemisphereLight('#fff8de','#90a191',2.1));const light=new THREE.DirectionalLight('#fff2d7',3.3);light.position.set(-50,90,55);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.camera.left=-80;light.shadow.camera.right=80;light.shadow.camera.top=66;light.shadow.camera.bottom=-66;light.shadow.camera.near=1;light.shadow.camera.far=210;light.shadow.bias=-.00025;light.shadow.normalBias=.18;this.scene.add(light);this.root=new THREE.Group();this.scene.add(this.root);this.buckets=new Map();this.breakableWalls=[];this.mats=new Map();this.randSeed=sim.config.seed;this.wheels=[];this.banners=[];this.boats=[];this.dust=[];this.revision=-1;this.actorTargets=[];this.time=0;this.followId=null;this.workSurface=null;
 this.buildLandscape();this.buildArchitecture();this.flush();this.buildWorks();this.buildEngine();this.buildActors();this.buildDetails();this.resize();this.update(0);}
 random(){this.randSeed=(Math.imul(this.randSeed,1664525)+1013904223)>>>0;return this.randSeed/4294967296;}
 material(color){if(!this.mats.has(color))this.mats.set(color,new THREE.MeshStandardMaterial({color,roughness:.9}));return this.mats.get(color);}
 part(geo,color,x=0,y=0,z=0,ry=0,parent=null){if(parent){const mesh=new THREE.Mesh(geo,this.material(color));mesh.position.set(x,y,z);mesh.rotation.y=ry;mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}geo.rotateY(ry);geo.translate(x,y,z);const list=this.buckets.get(color)||[];list.push(geo.toNonIndexed());geo.dispose();this.buckets.set(color,list);}
 box(w,h,d,color,x,y,z,ry=0,parent=null){return this.part(new THREE.BoxGeometry(w,h,d),color,x,y,z,ry,parent);}
 flush(){for(const [color,geos] of this.buckets){const merged=mergeGeometries(geos,false),m=new THREE.Mesh(merged,this.material(color));m.castShadow=m.receiveShadow=true;this.root.add(m);geos.forEach(g=>g.dispose());}this.buckets.clear();}
 buildLandscape(){const s=this.sim.config,geo=new THREE.PlaneGeometry(124,88,TERRAIN.cols,TERRAIN.rows);geo.rotateX(-Math.PI/2);geo.setIndex(terrainIndices());const p=geo.attributes.position,colors=new Float32Array(p.count*3);const c=new THREE.Color();for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),h=this.sim.heightAt(x,z);p.setY(i,h);const dry=s.theme==='green'?'#a8b493':'#d1bf97',high=s.theme==='green'?'#bdc6a8':'#ddcba6';c.set(h>7?high:dry).multiplyScalar(.96+.04*Math.sin(x*.35+z*.17));colors.set([c.r,c.g,c.b],i*3);}geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.computeVertexNormals();const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));m.receiveShadow=true;this.root.add(m);this.terrain=m;this.box(124,3,88,'#b5a58a',0,-5.6,0);this.box(125,.18,89,'#e9ddc0',0,-4.06,0);
 if(s.theme==='coast'){const g=new THREE.PlaneGeometry(124,88,65,46);g.rotateX(-Math.PI/2);const water=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:palette.water,roughness:.43,transparent:true,opacity:.93}));water.position.y=-1.2;water.receiveShadow=true;this.root.add(water);this.water=water;}
 // Fine erosion lines and stones emphasize the tabletop scale.
 for(let i=0;i<210;i++){const x=(this.random()-.5)*120,z=(this.random()-.5)*85,y=naturalHeight(s,x,z);if(y<0||Math.hypot(x-s.fort[0],z-s.fort[1])<20)continue;const scale=.18+this.random()*.55;this.part(new THREE.DodecahedronGeometry(scale,0),i%3?palette.darkStone:palette.cream,x,y+scale*.35,z,this.random()*6);}
 if(s.theme==='green'){for(let i=0;i<100;i++){const x=(this.random()-.5)*120,z=(this.random()-.5)*85;if(Math.hypot(x,z)<23||Math.abs(z)<4)continue;const y=naturalHeight(s,x,z);this.part(new THREE.CylinderGeometry(.09,.14,1.3,5),palette.wood,x,y+.65,z);this.part(new THREE.ConeGeometry(.9,2.1,7),i%2?'#718565':'#91a077',x,y+2,z);}}
 }
 wall(a,b,h=2.7,thickness=.8,towers=true){const s=this.sim.config,dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz),yaw=Math.atan2(dx,dz),x=(a[0]+b[0])/2,z=(a[1]+b[1])/2,profile=wallProfile(s,a,b,h),y=profile.floor;h=profile.top-y;const front=Math.abs(x-s.end[0])<10&&Math.abs(dx)<Math.abs(dz)*.65;
 if(front){const count=Math.ceil(length/2.5);for(let j=0;j<count;j++){const t=(j+.5)/count,px=a[0]+dx*t,pz=a[1]+dz*t,chunk=new THREE.Group();chunk.position.set(px,y,pz);chunk.rotation.y=yaw;this.root.add(chunk);this.box(thickness,h,length/count,palette.stone,0,h/2,0,0,chunk);this.box(thickness+.25,.25,length/count,palette.cream,0,h,0,0,chunk);for(const off of [-.65,.25])this.box(thickness+.1,.48,.42,palette.cream,0,h+.32,off,0,chunk);const body=this.physics.addBox(px,y+h/2,pz,thickness,h,length/count,yaw);body.wall=true;this.breakableWalls.push({group:chunk,body,z:pz,base:y,height:h,removed:false});}}
 else{this.box(thickness,h,length,palette.stone,x,y+h/2,z,yaw);this.box(thickness+.25,.25,length,palette.cream,x,y+h,z,yaw);}if(!front)for(let d=.3;d<length;d+=1.05){const t=d/length;this.box(thickness+.1,.48,.42,palette.cream,a[0]+dx*t,y+h+.32,a[1]+dz*t,yaw);}if(!front){const body=this.physics.addBox(x,y+h/2,z,thickness,h,length,yaw);body.wall=true;}if(towers){for(const p of [a]){const floor=naturalHeight(s,p[0],p[1]),vertex=this.outline.findIndex(q=>q[0]===p[0]&&q[1]===p[1]),adjacent=vertex>=0?wallProfile(s,this.outline[(vertex+this.outline.length-1)%this.outline.length],p).top:profile.top,towerH=Math.max(profile.top,adjacent)-floor+1.2;this.box(2.1,towerH,2.1,palette.darkStone,p[0],floor+towerH/2,p[1]);this.box(2.4,.3,2.4,palette.cream,p[0],floor+towerH+.02,p[1]);for(const side of [-1,1])for(const off of [-.7,.7])this.box(.5,.5,.5,palette.cream,p[0]+side*.85,floor+towerH+.4,p[1]+off);this.physics.addBox(p[0],floor+towerH/2,p[1],2.1,towerH,2.1);}}
 }
 building(x,z,w=2.4,d=3.5,h=2.4,roof=true){const s=this.sim.config;if(![-1,1].every(dx=>[-1,1].every(dz=>insidePolygon(this.outline,x+dx*w*.56,z+dz*d*.56)))||this.physics.boxes.some(b=>b.active&&containsPoint(b,x,z,Math.hypot(w,d)/2+.5)))return;const y=naturalHeight(s,x,z);this.box(w,h,d,palette.cream,x,y+h/2,z);const body=this.physics.addBox(x,y+(h+.1)/2,z,w,h+.1,d);if(roof)this.physics.addRoof(body,w,d,h);this.box(w+.12,.2,d+.12,palette.stone,x,y+h,z);if(roof){const g=new THREE.ConeGeometry(1,1,4);g.rotateY(Math.PI/4);g.scale(w*.78,.85,d*.78);this.part(g,palette.roof,x,y+h+.5,z);}else{for(const side of [-1,1])this.box(w,.35,.12,palette.stone,x,y+h+.22,z+side*d/2);this.box(.6,.3,.6,palette.darkStone,x+.45,y+h+.17,z);}
 for(const side of [-1,1])for(const off of [-.25,.25])this.box(.4,.65,.04,'#6b796b',x+w*off,y+h*.62,z+side*(d/2+.023));this.box(.5,1,.04,palette.wood,x,y+.5,z+d/2+.025);}
 buildArchitecture(){const s=this.sim.config,[cx,cz]=s.fort;this.outline=fortressOutline(s);for(let i=0;i<this.outline.length;i++)this.wall(this.outline[i],this.outline[(i+1)%this.outline.length],s.id==='candia'?3.6:s.id==='constantinople'?5:2.7,s.id==='candia'?1.9:.8);
 if(s.id==='constantinople'){for(const x of [cx-20,cx-24])this.wall([x,-24],[x,25],x===cx-20?3.3:1.8,.75);this.box(7,.2,54,'#9c947b',cx-29,.02,0);}
 if(s.id==='jerusalem'){this.wall([cx-7,-19],[cx-7,20],3,.7);this.wall([cx+5,-19],[cx+5,20],3.6,.8);const y=naturalHeight(s,cx+8,-13);this.box(7,.75,9,palette.stone,cx+8,y+.38,-13);this.box(4.5,5,7,palette.cream,cx+8,y+3,-13);this.physics.addBox(cx+8,y+2.9,-13,6,5.8,9);for(const z of [-16,-14,-12,-10])for(const x of [cx+5.5,cx+10.5])this.part(new THREE.CylinderGeometry(.23,.27,3.8,8),palette.stone,x,y+2.8,z);this.box(6,.4,9,palette.cream,cx+8,y+5.6,-13);}
 let index=0;for(let x=cx-9;x<cx+13;x+=4.4)for(let z=-17;z<19;z+=5.1){if(s.id==='masada'&&x>cx+3&&z<-4||s.id==='jerusalem'&&x>cx+2&&z<-5)continue;const h=1.3+this.random()*2.5;this.building(x+this.random()*.5,z+this.random()*.4,2.6,3.4,h,s.id==='alesia'||s.id==='candia'||s.id==='constantinople');index++;}
 if(s.id==='masada'){// Palace courts, storehouses, and a cistern opening.
 for(let i=0;i<6;i++){const x=cx+2+i*1.7,z=-12,y=naturalHeight(s,x,z);this.box(1.35,1.65,9,palette.stone,x,y+.83,z);this.physics.addBox(x,y+.83,z,1.35,1.66,9);this.box(1.5,.18,9.2,palette.cream,x,y+1.75,z);}const y=naturalHeight(s,cx-4,12);this.box(7,.4,7,palette.darkStone,cx-4,y+.2,12);for(const side of [-1,1]){this.box(.3,1.4,7,palette.stone,cx-4+side*3.4,y+.7,12);this.physics.addBox(cx-4+side*3.4,y+.7,12,.3,1.4,7);}this.part(new THREE.CylinderGeometry(.8,.8,.1,14),'#7d7e6b',cx+6,naturalHeight(s,cx+6,15)+.1,15);}
 const [campX,campZ]=s.camp;for(let row=0;row<4;row++)for(let col=0;col<6;col++){const x=campX+col*3.6,z=campZ+row*4.2,y=naturalHeight(s,x,z);const g=new THREE.ConeGeometry(1,1,4);g.rotateY(Math.PI/4);g.scale(1.3,1.2,1.6);this.part(g,row%2?palette.cream:'#c7bca2',x,y+.62,z);this.physics.addBox(x,y+.6,z,1.84,1.2,2.27);this.box(.09,1.3,.09,palette.wood,x,y+.65,z);this.box(.65,.03,1.6,'#9c957c',x,y+.02,z);}
 const y=naturalHeight(s,campX+6,campZ+6);for(const dx of [-2.5,2.5])this.box(.09,5,.09,palette.wood,campX+6+dx,y+2.5,campZ+6);const flagGeo=new THREE.PlaneGeometry(3.1,1.2,8,2);const flag=new THREE.Mesh(flagGeo,new THREE.MeshStandardMaterial({color:s.faction==='Roman'?palette.red:'#76928a',roughness:.9,side:THREE.DoubleSide}));flag.position.set(campX+6,y+4,campZ+6);this.root.add(flag);this.banners.push(flag);
 for(let i=0;i<16;i++){const x=campX+this.random()*12,z=campZ+12+this.random()*3,h=.2+this.random()*.25;this.box(.8,h,.5,palette.wood,x,naturalHeight(s,x,z)+h/2,z,this.random());}
 if(s.id==='masada'){for(const [x,z] of [[-24,29],[-12,-34],[47,-29],[47,29]]){const h=naturalHeight(s,x,z);for(let i=0;i<3;i++)this.part(new THREE.ConeGeometry(1,1.2,4),palette.cream,x+i*2,h+.6,z,Math.PI/4);for(const side of [-1,1])this.box(.25,.4,8,palette.darkStone,x+side*3.5,h+.2,z);}}
 if(s.kind==='rings'){// Defensive ditches are visible as a schematic footprint before building begins.
 for(const radius of [[30,22],[47,33]]){const points=Array.from({length:181},(_,i)=>{const a=i/180*Math.PI*2,x=Math.cos(a)*radius[0],z=Math.sin(a)*radius[1];return new THREE.Vector3(x,naturalHeight(s,x,z)+.03,z)});const line=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),180,.34,4,false),this.material('#9c9e7f'));line.receiveShadow=true;this.root.add(line);}}
 }
 buildWorks(){const s=this.sim.config,n=this.sim.built.length;this.workBlocks=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),this.material(s.kind==='causeway'?'#beb9a2':s.kind==='trenches'?'#ab9675':'#c6a883'),s.kind==='trenches'?n*2:n);this.workBlocks.castShadow=this.workBlocks.receiveShadow=true;this.workBlocks.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.workBlocks.frustumCulled=false;this.root.add(this.workBlocks);this.stakes=new THREE.InstancedMesh(new THREE.CylinderGeometry(.055,.08,1,5),this.material(palette.wood),n*4);this.stakes.castShadow=true;this.stakes.frustumCulled=false;this.root.add(this.stakes);this.dummy=new THREE.Object3D();}
 buildEngine(){const s=this.sim.config;this.engine=new THREE.Group();this.root.add(this.engine);const cannon=s.kind==='battery'||s.kind==='trenches';if(cannon){this.box(2.1,.4,3.5,palette.wood,0,.6,0,0,this.engine);const barrel=this.part(new THREE.CylinderGeometry(.38,.56,3.3,14),palette.metal,0,1.45,.15,0,this.engine);barrel.rotation.x=Math.PI/2-.15;this.box(1,.5,.8,palette.darkStone,0,1,-1.4,0,this.engine);}else{for(const y of [1.4,3.3,5.2,7.1]){this.box(3.4,.22,3.7,palette.wood,0,y,0,0,this.engine);for(const z of [-1.6,1.6])this.box(3.5,1.3,.16,palette.wood,0,y+.65,z,0,this.engine);}for(const x of [-1.5,1.5])for(const z of [-1.5,1.5])this.box(.18,7.4,.18,'#6f6650',x,4,z,0,this.engine);for(const side of [-1,1]){const beam=this.box(.14,7.3,.14,palette.darkStone,side*1.5,4,0,0,this.engine);beam.rotation.z=side*.31;}this.box(3.7,.3,4,palette.cream,0,7.9,0,0,this.engine);this.box(.45,.45,4.8,palette.darkStone,0,1.9,2,0,this.engine);}
 for(const x of [-1.65,1.65])for(const z of [-1.2,1.2]){const wheel=this.part(new THREE.CylinderGeometry(.65,.65,.24,12),palette.wood,x,.65,z,0,this.engine);wheel.rotation.z=Math.PI/2;this.wheels.push(wheel);const axle=this.part(new THREE.CylinderGeometry(.08,.08,.35,8),palette.darkStone,x,.65,z,0,this.engine);axle.rotation.z=Math.PI/2;const support=this.box(.13,1,.13,palette.darkStone,x,1,z,0,this.engine);wheel.userData.axle=axle;wheel.userData.support=support;}
 this.engine.rotation.y=Math.PI/2;this.engine.visible=s.kind!=='rings';
 // A small second battery or torsion engine supplies visible support action.
 this.artillery=new THREE.Group();this.root.add(this.artillery);this.box(2,.2,2.4,palette.wood,0,.5,0,0,this.artillery);this.box(2.3,.14,.25,palette.darkStone,0,1.2,0,0,this.artillery);for(const x of [-.85,.85])this.box(.13,1.6,.18,palette.wood,x,1,0,0,this.artillery);this.throwArm=this.box(.12,2.1,.14,palette.wood,0,1.7,0,0,this.artillery);this.throwArm.rotation.x=-.45;this.artillery.position.set(s.start[0]-2,naturalHeight(s,s.start[0]-2,7),7);this.artillery.rotation.y=-Math.PI/2;
 this.carts=[];for(let i=0;i<5;i++){const cart=new THREE.Group();this.box(1,.25,1.5,palette.wood,0,.55,0,0,cart);for(const side of [-1,1]){this.box(.09,.55,1.5,palette.wood,side*.5,.83,0,0,cart);const wheel=this.part(new THREE.CylinderGeometry(.32,.32,.1,8),palette.darkStone,side*.62,.32,0,0,cart);wheel.rotation.z=Math.PI/2;cart.userData.wheels??=[];cart.userData.wheels.push(wheel);}this.box(.8,.2,1.2,palette.sand,0,.85,0,0,cart);this.root.add(cart);this.carts.push(cart);}this.physics.cartBodies=this.sim.carts.map(c=>{const body=this.physics.addBox(c.x,this.sim.surfaceHeight(c.x,c.z)+.62,c.z,1.4,1.1,1.6,c.heading);body.type=4;body.obstacle.moving=true;return body;});
 }
 buildActors(){const n=this.sim.agents.length;this.actorParts={};const part=(name,geo,total=n)=>{const mesh=new THREE.InstancedMesh(geo,new THREE.MeshStandardMaterial({roughness:.84}),total);mesh.castShadow=mesh.receiveShadow=true;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.userData.actorPart=name;this.root.add(mesh);this.actorParts[name]=mesh;this.actorTargets.push(mesh);return mesh;};part('torso',new THREE.BoxGeometry(.43,.53,.29));part('head',new THREE.SphereGeometry(.21,8,6));part('helmet',new THREE.SphereGeometry(.23,8,6,0,Math.PI*2,0,Math.PI*.58));part('arms',new THREE.BoxGeometry(.12,.47,.13),n*2);part('legs',new THREE.BoxGeometry(.14,.48,.15),n*2);part('shield',new THREE.BoxGeometry(.36,.6,.09));part('weapon',new THREE.BoxGeometry(.07,.72,.05));part('basket',new THREE.CylinderGeometry(.21,.15,.29,7));part('tool',new THREE.BoxGeometry(.04,.75,.04));this.actorRoot=new THREE.Object3D();this.actorPart=new THREE.Object3D();this.partMatrix=new THREE.Matrix4();
 const geom=new THREE.TorusGeometry(.37,.026,5,24);geom.rotateX(-Math.PI/2);this.selection=new THREE.Mesh(geom,new THREE.MeshBasicMaterial({color:'#fff9db',depthWrite:false}));this.selection.visible=false;this.root.add(this.selection);
 this.projectileMesh=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(.22,0),this.material(palette.darkStone),100);this.projectileMesh.frustumCulled=false;this.root.add(this.projectileMesh);this.dustMesh=new THREE.InstancedMesh(new THREE.SphereGeometry(1,5,4),new THREE.MeshBasicMaterial({color:'#e9dcc0',transparent:true,opacity:.55,depthWrite:false}),90);this.dustMesh.frustumCulled=false;this.root.add(this.dustMesh);
 }
 buildDetails(){const s=this.sim.config;if(s.theme==='coast'){for(let i=0;i<(s.id==='tyre'?7:4);i++){const boat=new THREE.Group();const hull=this.part(new THREE.SphereGeometry(1,10,5,0,Math.PI*2,0,Math.PI/2),palette.wood,0,0,0,0,boat);hull.scale.set(.7,.55,2.2);hull.rotation.z=Math.PI;this.box(.06,3.2,.06,palette.wood,0,1.5,0,0,boat);const sail=this.part(new THREE.PlaneGeometry(1.45,2.1),palette.cream,.45,1.9,0,0,boat);sail.material=new THREE.MeshStandardMaterial({color:palette.cream,side:THREE.DoubleSide});boat.userData.phase=i*1.9;this.root.add(boat);this.boats.push(boat);}}
 const ringGeo=new THREE.RingGeometry(.45,.5,40);ringGeo.rotateX(-Math.PI/2);this.ripple=new THREE.Mesh(ringGeo,new THREE.MeshBasicMaterial({color:'#fff8e0',transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide}));this.root.add(this.ripple);this.rippleAge=99;
 }
 updateWorks(){if(this.revision===this.sim.revision)return;const s=this.sim.config,N=this.sim.built.length;for(let i=0;i<N;i++){const p=workPoint(s,i/(N-1)),h=this.sim.built[i]/5,base=this.sim.base[i],yaw=s.kind==='rings'?Math.atan2(-p.x,p.z):s.kind==='trenches'?Math.atan2(1,Math.cos(i/(N-1)*Math.PI*7)*.5):Math.PI/2;this.dummy.position.set(p.x,base+h*.5,p.z);this.dummy.rotation.set(0,yaw,0);this.dummy.scale.set(s.kind==='rings'?1.3:5.6,Math.max(.01,h),s.kind==='rings'?(i<N/2?2.9:3.5):(s.end[0]-s.start[0])/(N-1)+.03);if(h<.001||s.kind!=='trenches')this.dummy.scale.setScalar(0);this.dummy.updateMatrix();if(s.kind==='trenches'){const left=workPoint(s,Math.max(0,(i-.5)/(N-1))),right=workPoint(s,Math.min(1,(i+.5)/(N-1))),heading=Math.atan2(right.x-left.x,right.z-left.z);for(let side=0;side<2;side++){this.dummy.rotation.y=heading;this.dummy.position.set(p.x+Math.cos(heading)*(side?1:-1)*1.8,base+h*.25,p.z-Math.sin(heading)*(side?1:-1)*1.8);this.dummy.scale.set(.45,h*.5,Math.hypot(right.x-left.x,right.z-left.z)+.05);if(h<.001)this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.workBlocks.setMatrixAt(i*2+side,this.dummy.matrix);}}else this.workBlocks.setMatrixAt(i,this.dummy.matrix);for(let j=0;j<4;j++){this.dummy.position.set(p.x+(j%2?1:-1)*(s.kind==='rings'?.4:2.8),base+h/2+(s.kind==='rings'?h*.55:0),p.z+(j<2?-.2:.2));this.dummy.scale.set(1,Math.max(.01,h+(s.kind==='rings'?.6:0)),1);if(h<.001)this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.stakes.setMatrixAt(i*4+j,this.dummy.matrix);}}
 {const pos=this.terrain.geometry.attributes.position;for(let i=0;i<pos.count;i++)pos.setY(i,this.sim.heightAt(pos.getX(i),pos.getZ(i)));pos.needsUpdate=true;this.terrain.geometry.computeVertexNormals();}
 this.workBlocks.instanceMatrix.needsUpdate=true;this.stakes.instanceMatrix.needsUpdate=true;this.revision=this.sim.revision;}
 setPart(name,i,x,y,z,rx=0,ry=0,rz=0,scale=1,color='#fff'){const part=this.actorPart;part.position.set(x,y,z);part.rotation.set(rx,ry,rz);part.scale.setScalar(scale);part.updateMatrix();this.partMatrix.multiplyMatrices(this.actorRoot.matrix,part.matrix);const mesh=this.actorParts[name];mesh.setMatrixAt(i,this.partMatrix);mesh.setColorAt(i,new THREE.Color(color));}
 updateActors(){for(const a of this.sim.agents){const body=this.physics.bodies[a.id],dynamic=body.type===1;if(dynamic){this.actorRoot.quaternion.set(body.quaternion.x,body.quaternion.y,body.quaternion.z,body.quaternion.w);this.actorRoot.position.set(0,-PERSON_ORIGIN,0).applyQuaternion(this.actorRoot.quaternion).add(body.position);}else{this.actorRoot.position.set(a.x,a.y,a.z);this.actorRoot.rotation.set(0,a.heading,0);}this.actorRoot.updateMatrix();const walk=dynamic?0:Math.sin(a.walk)*.5,work=a.attackSwing>0?Math.sin(a.attackSwing/.4*Math.PI)*1.35:a.state==='build'?Math.sin(this.sim.clock*5+a.id)*.5:0,color=a.role==='worker'?(a.id%3?'#c7af87':'#eee1be'):a.role==='soldier'?(this.sim.config.faction==='Roman'?palette.red:'#548078'):a.role==='relief'?'#8e9970':'#839674';const damage=1-a.health;const torso=new THREE.Color(color).multiplyScalar(1-damage*.28).getStyle();this.setPart('torso',a.id,0,.85,0,0,0,0,1,torso);this.setPart('head',a.id,0,1.27,0,0,0,0,1,palette.skin);this.setPart('helmet',a.id,0,1.37,0,0,0,0,a.role==='worker'?.95:1.1,a.role==='worker'?'#9b8663':palette.metal);this.setPart('arms',a.id*2,-.3,.8,0,a.carrying?-.7:a.combatTarget>=0?-.75:-walk+work,0,a.carrying?.3:.12,1,color);this.setPart('arms',a.id*2+1,.3,.8,0,a.carrying?-.7:a.combatTarget>=0?-work:walk+work,0,a.carrying?-.3:-.12,1,color);this.setPart('legs',a.id*2,-.12,.29,0,walk,0,0,1,'#675f4d');this.setPart('legs',a.id*2+1,.12,.29,0,-walk,0,0,1,'#675f4d');this.setPart('shield',a.id,-.39,.77,.18,0,0,.1,a.role==='worker'?0:1,a.role==='soldier'?palette.red:'#d1ba88');this.setPart('weapon',a.id,.34,.8+.16*Math.cos(work),.1-.16*Math.sin(work),-work,0,0,a.role==='worker'?0:1,palette.metal);this.setPart('basket',a.id,0,.66,.32,0,0,0,a.carrying?1:0,'#a89069');this.setPart('tool',a.id,.34,1.05,.1,a.state==='build'?work:0,0,-.2,a.role==='worker'&&a.state==='build'?1:0,palette.wood);}
 for(const mesh of Object.values(this.actorParts)){mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;}}
 pickActor(hit){if(hit?.instanceId===undefined)return null;const key=hit.object.userData.actorPart;return key==='arms'||key==='legs'?Math.floor(hit.instanceId/2):hit.instanceId;}
 burst(x,y,z,strength=3){for(let i=0;i<Math.min(18,Math.ceil(strength*2));i++){if(this.dust.length>=90)this.dust.shift();this.dust.push({x,y,z,vx:(this.random()-.5)*strength,vy:this.random()*2+.5,vz:(this.random()-.5)*strength,life:1.8,age:0,size:.08+this.random()*.2});}}
 shockwave(x,z){this.ripple.position.set(x,this.sim.heightAt(x,z)+.08,z);this.rippleAge=0;this.burst(x,this.ripple.position.y,z,7);}
 shot(defender=false){const s=this.sim.config,cannon=s.kind==='battery'||s.kind==='trenches';const from=defender?{x:s.end[0]+4,y:s.height+3,z:3}:{x:this.engine.position.x+1,y:this.engine.position.y+(cannon?1.5:6.8),z:this.engine.position.z};const to=defender?{x:s.start[0]+(s.end[0]-s.start[0])*.45,y:this.sim.heightAt(s.start[0]+8,0)+.4,z:(this.random()-.5)*6}:{x:s.end[0]+4,y:s.height+2,z:(this.random()-.5)*8};this.physics.projectile(from,to,cannon?20:14,cannon?.28:.2);this.burst(from.x,from.y,from.z,cannon?3:1);this.throwArm.rotation.x=-1;}
 update(dt){this.time+=dt;const s=this.sim.config;this.updateWorks();this.updateActors();for(const wall of this.breakableWalls){const collapse=(1-this.sim.wallHealth)*Math.max(0,1-Math.abs(wall.z)/7);wall.group.scale.y=Math.max(.12,1-collapse*1.25);if(!wall.removed)this.physics.resizeBox(wall.body,wall.base,wall.height*wall.group.scale.y);if(collapse>.55&&!wall.removed){this.physics.removeBox(wall.body);wall.removed=true;this.burst(wall.group.position.x,wall.group.position.y+1,wall.group.position.z,4);}}const p=workPoint(s,this.sim.engine*(s.kind==='battery'||s.kind==='trenches'?.52:1));const floor=Math.max(...this.wheels.map(w=>this.sim.surfaceHeight(p.x+w.position.z,p.z-w.position.x)));this.engine.position.set(p.x,floor+.1,p.z);this.engine.rotation.z=0;for(const w of this.wheels){w.position.y=this.sim.surfaceHeight(p.x+w.position.z,p.z-w.position.x)-this.engine.position.y+.65;w.rotation.y=this.sim.engine*65;w.userData.axle.position.y=w.position.y;const height=Math.max(.12,1.4-w.position.y);w.userData.support.scale.y=height;w.userData.support.position.y=w.position.y+height/2;}this.throwArm.rotation.x+=(-.45-this.throwArm.rotation.x)*Math.min(1,dt*3);
 this.carts.forEach((c,i)=>{const cart=this.sim.carts[i];c.position.set(cart.x,this.sim.surfaceHeight(cart.x,cart.z)+.1,cart.z);c.rotation.y=cart.heading;c.userData.wheels.forEach(w=>w.rotation.y=cart.distance/.32);});
 for(const banner of this.banners){const p=banner.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(p.getX(i)*2+this.time*3)*.08);p.needsUpdate=true;banner.geometry.computeVertexNormals();}
 if(this.water){const p=this.water.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,Math.sin(p.getX(i)*.2+this.time*1.4)*.035+Math.cos(p.getZ(i)*.25-this.time)*.035);p.needsUpdate=true;}
 this.boats.forEach((b,i)=>{const angle=this.time*.02+b.userData.phase;if(s.id==='tyre'){b.position.set(-5+Math.sin(angle)*8,-1.23,18+Math.cos(angle)*12*(i%2?-1:1));b.rotation.y=Math.atan2(Math.cos(angle)*8,-Math.sin(angle)*12*(i%2?-1:1));}else{b.position.set(-30+i*15+Math.sin(angle)*6,-1.23,36+Math.cos(angle)*3);b.rotation.y=Math.PI/2;}b.rotation.z=Math.sin(this.time*1.3+i)*.035;});
 this.physics.objects.forEach((b,i)=>{this.dummy.position.copy(b.position);this.dummy.quaternion.set(b.quaternion.x,b.quaternion.y,b.quaternion.z,b.quaternion.w);this.dummy.scale.setScalar(b.projectile?b.radius/.22:.8);this.dummy.updateMatrix();this.projectileMesh.setMatrixAt(i,this.dummy.matrix);});this.projectileMesh.count=this.physics.objects.length;this.projectileMesh.instanceMatrix.needsUpdate=true;
 for(let i=this.dust.length-1;i>=0;i--){const d=this.dust[i];d.age+=dt;if(d.age>d.life){this.dust.splice(i,1);continue;}d.x+=d.vx*dt;d.y+=d.vy*dt;d.z+=d.vz*dt;d.vy-=1.2*dt;}this.dust.forEach((d,i)=>{this.dummy.position.set(d.x,d.y,d.z);this.dummy.rotation.set(0,0,0);this.dummy.scale.setScalar(d.size*(1+d.age*.6)*(1-d.age/d.life));this.dummy.updateMatrix();this.dustMesh.setMatrixAt(i,this.dummy.matrix);});this.dustMesh.count=this.dust.length;this.dustMesh.instanceMatrix.needsUpdate=true;this.rippleAge+=dt;this.ripple.scale.setScalar(1+this.rippleAge*12);this.ripple.material.opacity=Math.max(0,.65-this.rippleAge*.7);
 if(this.followId!==null){const b=this.physics.bodies[this.followId],a=this.sim.agents[this.followId],pos=a.disabled?b.position:{x:a.x,y:a.y+.72,z:a.z};const target=new THREE.Vector3(pos.x,pos.y,pos.z),delta=target.clone().sub(this.controls.target).multiplyScalar(.08);this.camera.position.add(delta);this.controls.target.add(delta);}this.controls.update();this.renderer.render(this.scene,this.camera);}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/Math.max(1,h);this.camera.updateProjectionMatrix();}
 view(kind){this.followId=null;const s=this.sim.config;let target,pos;if(kind==='works'){const p=workPoint(s,this.sim.front/(this.sim.built.length-1));target=new THREE.Vector3(p.x,this.sim.heightAt(p.x,p.z)+3,p.z);pos=target.clone().add(new THREE.Vector3(-21,18,28));}else if(kind==='city'){target=new THREE.Vector3(s.fort[0],s.height+1,0);pos=target.clone().add(new THREE.Vector3(-34,31,41));}else if(kind==='camp'){target=new THREE.Vector3(s.camp[0]+5,2,s.camp[1]+5);pos=target.clone().add(new THREE.Vector3(-14,17,24));}else{target=new THREE.Vector3(2,s.id==='masada'?8:2,0);pos=new THREE.Vector3(-91,84,103);}this.camera.position.copy(pos);this.controls.target.copy(target);this.controls.update();}
 dispose(){this.controls.dispose();this.renderer.dispose();const gs=new Set(),ms=new Set();this.root.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m);if(o.isInstancedMesh)o.dispose();});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
}
