import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {naturalHeight,workPoint,fortressOutline,clamp,wallProfile,castleHeight,enginePoint,campLayout,ringSpec,ringPoint,hasWater,WATER_LEVEL,outlineNearest,hasTower} from './simulation.js';
import {TERRAIN,terrainIndices,PERSON_ORIGIN,containsPoint,insidePolygon} from './collision.js';
import {Atmosphere} from './atmosphere.js';
import {Particles,glowColor} from './particles.js';
const palette={sand:'#c9b68f',stone:'#e4d9bf',cream:'#f4ecda',darkStone:'#b6a58a',wood:'#887453',darkWood:'#5f4c36',roof:'#b97a5e',thatch:'#b49a63',red:'#a94e3d',water:'#7fb3b4',metal:'#7c8881',bronze:'#a3804a',iron:'#5f6466',hide:'#7d5f43',brick:'#b06a4e',skin:'#dfb994',canvas:'#e8dfc7',straw:'#c9b072',leaf:'#7c9461',dark:'#4a4a42'};
// Ground colours per landscape: low and high ground, rock and strata on steep faces, vegetation, trodden paths, shore and seabed.
export const THEMES={
 desert:{low:'#d8c49b',high:'#e6d4ad',rock:'#b78f68',strata:'#cfa97f',grass:'#bdb38a',path:'#c4a47b',sand:'#ead9b3',bed:'#8fa79f',green:.12,wall:'#e6dbc1',tower:'#cdbd9c'},
 dry:{low:'#c9bb91',high:'#d6c79e',rock:'#a88e6c',strata:'#bea27b',grass:'#a7aa76',path:'#b89d76',sand:'#e2d4ad',bed:'#8aa49c',green:.55,wall:'#ddd2b8',tower:'#c6b796'},
 green:{low:'#9fb07b',high:'#b4bf8e',rock:'#9b9079',strata:'#aa9f86',grass:'#8aa063',path:'#b5a27b',sand:'#d2c79f',bed:'#7f9a8e',green:1,wall:'#d8d1bc',tower:'#c3b99f'},
 coast:{low:'#cfbd93',high:'#dbcaa2',rock:'#b39b7a',strata:'#c2a985',grass:'#acae80',path:'#c0a57d',sand:'#ebddb6',bed:'#86a8a2',green:.45,wall:'#e3d8bd',tower:'#cbbc9b'}};
const hash=(x,z)=>{const v=Math.sin(x*127.1+z*311.7)*43758.5453;return v-Math.floor(v);};
const vnoise=(x,z)=>{const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz,u=fx*fx*(3-2*fx),v=fz*fz*(3-2*fz),a=hash(ix,iz),b=hash(ix+1,iz),c=hash(ix,iz+1),d=hash(ix+1,iz+1);return a+(b-a)*u+(c-a)*v+(a-b-c+d)*u*v;};
const smooth=(a,b,v)=>{const t=clamp((v-a)/(b-a),0,1);return t*t*(3-2*t);};
const C=hex=>new THREE.Color(hex),tmp=new THREE.Color(),tmp2=new THREE.Color();
const SKIN=['#e3b994','#cf9f78','#b8875f','#9b6c4a','#d8ab83'];
const FLORA={desert:['acacia','shrub','shrub'],dry:['olive','shrub','cypress','olive'],green:['deciduous','conifer','deciduous','shrub'],coast:['olive','cypress','shrub','olive']};
// A triangular prism, used for ridge tents and roofs.
function prism(w,h,d){const g=new THREE.BufferGeometry(),x=w/2,z=d/2,p=[[-x,0,-z],[x,0,-z],[0,h,-z],[-x,0,z],[x,0,z],[0,h,z]],f=[[0,2,1],[3,4,5],[0,3,5],[0,5,2],[1,2,5],[1,5,4],[0,1,4],[0,4,3]],pos=[];for(const t of f)for(const i of t)pos.push(...p[i]);g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.computeVertexNormals();g.setAttribute('uv',new THREE.Float32BufferAttribute(new Float32Array(pos.length/3*2),2));return g;}

export class MiniatureScene{
 constructor(canvas,sim,physics,options={}){this.canvas=canvas;this.sim=sim;this.physics=physics;this.options={quality:'high',cycle:true,...options};this.scene=new THREE.Scene();
 this.renderer=new THREE.WebGLRenderer({canvas,antialias:this.options.quality!=='high',alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.options.quality==='high'?2:1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;
 this.camera=new THREE.PerspectiveCamera(36,1,.1,900);this.camera.position.set(-91,84,103);this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(2,7,0);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.maxPolarAngle=Math.PI*.46;this.controls.minDistance=7;this.controls.maxDistance=215;this.controls.zoomSpeed=.85;this.controls.panSpeed=.65;
 this.atmosphere=new Atmosphere(this.scene,this.renderer,{quality:this.options.quality,cycle:this.options.cycle});this.sim.dayCycle=this.options.cycle;
 this.root=new THREE.Group();this.scene.add(this.root);this.particles=new Particles(this.root);this.buckets=new Map();this.breakableWalls=[];this.mats=new Map();this.randSeed=sim.config.seed;this.wheels=[];this.feet=[];this.banners=[];this.boats=[];this.flames=[];this.lamps=[];this.revision=-1;this.actorTargets=[];this.time=0;this.followId=null;this.tween=null;
 this.buildLandscape();this.buildArchitecture();this.buildVegetation();this.flush();this.buildWorks();this.buildEngine();this.buildCarts();this.buildActors();this.buildDetails();this.buildPlinth();this.resize();this.view('overview',false);this.update(0,0);}
 get theme(){return THEMES[this.sim.config.theme]||THEMES.desert;}
 random(){this.randSeed=(Math.imul(this.randSeed,1664525)+1013904223)>>>0;return this.randSeed/4294967296;}
 material(key){if(!this.mats.has(key)){const kinds={matte:{vertexColors:true,roughness:.86},metal:{vertexColors:true,roughness:.42,metalness:.55},cloth:{vertexColors:true,roughness:.95,side:THREE.DoubleSide}};this.mats.set(key,new THREE.MeshStandardMaterial(kinds[key]||{color:key,roughness:.85}));}return this.mats.get(key);}
 // Static parts are baked into a few merged meshes. Each part gets a slight tint and a darker foot, like hand-painted miniatures.
 part(geo,color,x=0,y=0,z=0,ry=0,parent=null,kind='matte'){if(parent){const mesh=new THREE.Mesh(geo,kind==='metal'?new THREE.MeshStandardMaterial({color,roughness:.42,metalness:.55}):this.material(color));mesh.position.set(x,y,z);mesh.rotation.y=ry;mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 geo.rotateY(ry);geo.translate(x,y,z);const g=geo.index?geo.toNonIndexed():geo.clone();geo.dispose();g.computeBoundingBox();const p=g.attributes.position,colors=new Float32Array(p.count*3),bb=g.boundingBox,span=bb.max.y-bb.min.y,jitter=.93+hash(x*1.7+y,z*1.3-y)*.12;tmp.set(color);for(let i=0;i<p.count;i++){const t=span>.35?(p.getY(i)-bb.min.y)/span:1,shade=jitter*(.8+.2*Math.min(1,t*1.6));colors[i*3]=tmp.r*shade;colors[i*3+1]=tmp.g*shade;colors[i*3+2]=tmp.b*shade;}g.setAttribute('color',new THREE.BufferAttribute(colors,3));if(!g.attributes.uv)g.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(p.count*2),2));const list=this.buckets.get(kind)||[];list.push(g);this.buckets.set(kind,list);}
 box(w,h,d,color,x,y,z,ry=0,parent=null,kind){return this.part(new THREE.BoxGeometry(w,h,d),color,x,y,z,ry,parent,kind);}
 flush(){for(const [kind,geos] of this.buckets){const merged=mergeGeometries(geos,false),m=new THREE.Mesh(merged,this.material(kind));m.castShadow=m.receiveShadow=true;this.root.add(m);geos.forEach(g=>g.dispose());}this.buckets.clear();}

 // ---------- Landscape ----------
 buildLandscape(){const s=this.sim.config,geo=new THREE.PlaneGeometry(124,88,TERRAIN.cols,TERRAIN.rows);geo.rotateX(-Math.PI/2);geo.setIndex(terrainIndices());const p=geo.attributes.position;this.heights=new Float32Array(p.count);this.natural=new Float32Array(p.count);for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);this.natural[i]=naturalHeight(s,x,z);const h=this.sim.heightAt(x,z);p.setY(i,h);this.heights[i]=h;}
 geo.setAttribute('color',new THREE.BufferAttribute(new Float32Array(p.count*3),3));this.prepareTerrainPaint();this.paintTerrain(geo);geo.computeVertexNormals();
 const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.97,map:this.detailTexture()}));m.receiveShadow=true;m.castShadow=true;this.root.add(m);this.terrain=m;
 if(hasWater(s))this.buildWater();this.buildSkirt();
 // Scattered stones emphasise the tabletop scale.
 for(let i=0;i<190;i++){const x=(this.random()-.5)*120,z=(this.random()-.5)*85,y=naturalHeight(s,x,z);if(y<WATER_LEVEL+.3||Math.hypot(x-s.fort[0],z-s.fort[1])<22||this.nearWorks(x,z,3))continue;const scale=.16+this.random()*.5;this.part(new THREE.DodecahedronGeometry(scale,0),i%3?this.theme.rock:this.theme.high,x,y+scale*.3,z,this.random()*6);}}
 nearWorks(x,z,margin=0){const s=this.sim.config;if(s.kind==='rings'){const r=ringSpec(s);for(const [rx,rz] of r.single?[r.inner]:[r.inner,r.outer]){const d=Math.abs(Math.hypot((x-r.cx)/rx,(z-r.cz)/rz)-1)*Math.min(rx,rz);if(d<2+margin)return true;}return false;}return x>s.start[0]-3-margin&&x<s.end[0]+3+margin&&Math.abs(z)<5+margin;}
 detailTexture(){if(typeof document==='undefined')return null;const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d'),img=g.createImageData(256,256);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const n=vnoise(x/9,y/9)*.5+vnoise(x/3.5,y/3.5)*.3+hash(x,y)*.2,v=Math.round(222+n*33),k=(y*256+x)*4;img.data[k]=img.data[k+1]=img.data[k+2]=v;img.data[k+3]=255;}g.putImageData(img,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(22,16);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}
 // Paths, contact shadows and cavities are worked out once; works colours update as the earth moves.
 prepareTerrainPaint(){const s=this.sim.config,c=campLayout(s),segs=[];const add=(a,b)=>segs.push([a[0],a[1],b[0],b[1]]);const camp=[c.x+c.w/2,c.z+1.9];if(s.kind==='rings'){const r=ringSpec(s),inner=ringPoint(s,0,(r.a0+r.a1)/2);add(camp,[inner.x,inner.z]);}else{add(camp,[s.start[0]-1,0]);add([s.start[0]-1,0],[s.start[0]+2,0]);}const route=this.sim.cartRoute;add([route.left,route.z-route.r],[route.right,route.z-route.r]);add([route.left,route.z+route.r],[route.right,route.z+route.r]);this.paths=segs;
 const n=(TERRAIN.cols+1)*(TERRAIN.rows+1);this.occlusion=new Float32Array(n).fill(1);this.terrainWet=hasWater(s);}
 bakeOcclusion(){const cols=TERRAIN.cols+1;this.occlusion.fill(1);for(const b of this.physics.boxes){if(!b.active||b.moving)continue;const r=Math.max(b.w,b.d)/2+1.6;// Plane rows run from z=-44 to z=44.
 for(let j=Math.max(0,Math.floor(b.z+44-r));j<=Math.min(TERRAIN.rows,Math.ceil(b.z+44+r));j++)for(let i=Math.max(0,Math.floor(b.x+62-r));i<=Math.min(TERRAIN.cols,Math.ceil(b.x+62+r));i++){const x=i-62,z=j-44;let d=0;for(let k=0;k<6&&containsPoint(b,x,z,d);k++)d+=.3;const f=containsPoint(b,x,z,0)?.7:.7+.3*smooth(0,1.6,d);const v=j*cols+i;this.occlusion[v]=Math.min(this.occlusion[v],f);}}}
 paintTerrain(geo,only=null){const s=this.sim.config,th=this.theme,p=geo.attributes.position,col=geo.attributes.color,cols=TERRAIN.cols+1,low=C(th.low),high=C(th.high),rock=C(th.rock),strata=C(th.strata),grass=C(th.grass),path=C(th.path),sand=C(th.sand),bed=C(th.bed),deep=C('#5f8d8f'),works=C(s.kind==='causeway'?'#bfb59c':s.kind==='rings'?'#a99470':s.kind==='trenches'?'#9a8160':'#b3936c'),dug=C('#7e6a4f'),out=new THREE.Color();
 const heights=this.heights;for(const i of only||Array.from({length:p.count},(_,k)=>k)){const x=p.getX(i),z=p.getZ(i),h=heights[i],gx=i%cols,gz=Math.floor(i/cols),hx=heights[gz*cols+Math.min(cols-1,gx+1)]-heights[gz*cols+Math.max(0,gx-1)],hz=heights[Math.min(TERRAIN.rows,gz+1)*cols+gx]-heights[Math.max(0,gz-1)*cols+gx],slope=Math.hypot(hx,hz)/2,n1=vnoise(x*.09+3,z*.09-2),n2=vnoise(x*.37,z*.37);
 out.copy(low).lerp(high,smooth(0,14,h)).multiplyScalar(.93+.12*vnoise(x*.045-7,z*.045+5));out.lerp(grass,smooth(.5,.78,n1)*th.green*(1-smooth(.5,.9,slope)));if(slope>.45){tmp.copy(rock).lerp(strata,.5+.5*Math.sin(h*2.4+n2*1.6));out.lerp(tmp,smooth(.45,1.1,slope));}
 if(this.terrainWet){out.lerp(sand,smooth(.9,-.4,h)*.85);if(h<WATER_LEVEL+.15){tmp.copy(bed).lerp(deep,smooth(WATER_LEVEL,-3.2,h));out.lerp(tmp,smooth(WATER_LEVEL+.15,WATER_LEVEL-.6,h));}}
 let d=Infinity;for(const [x0,z0,x1,z1] of this.paths){const dx=x1-x0,dz=z1-z0,f=clamp(((x-x0)*dx+(z-z0)*dz)/(dx*dx+dz*dz||1),0,1);d=Math.min(d,Math.hypot(x-x0-dx*f,z-z0-dz*f));}out.lerp(path,(1-smooth(.35,1.5,d))*.42);
 const delta=h-this.natural[i];if(delta>.04)out.lerp(works,smooth(.04,.5,delta));else if(delta<-.04)out.lerp(dug,smooth(-.04,-.5,delta));
 const around=(heights[gz*cols+Math.min(cols-1,gx+2)]+heights[gz*cols+Math.max(0,gx-2)]+heights[Math.min(TERRAIN.rows,gz+2)*cols+gx]+heights[Math.max(0,gz-2)*cols+gx])/4,ao=clamp(1-(around-h)*.09,.72,1.04)*this.occlusion[i]*(.95+.08*n2);out.multiplyScalar(ao);col.setXYZ(i,out.r,out.g,out.b);}col.needsUpdate=true;}
 buildWater(){const s=this.sim.config,g=new THREE.PlaneGeometry(124,88,124,88);g.rotateX(-Math.PI/2);const p=g.attributes.position,depth=new Float32Array(p.count),colors=new Float32Array(p.count*3),shallow=C('#9fd2c6'),mid=C('#62a6ad'),deep=C('#3f7f93');for(let i=0;i<p.count;i++){const d=WATER_LEVEL-naturalHeight(s,p.getX(i),p.getZ(i));depth[i]=d;tmp.copy(shallow).lerp(mid,smooth(.1,1.2,d)).lerp(deep,smooth(1.2,3,d));colors.set([tmp.r,tmp.g,tmp.b],i*3);}g.setAttribute('depth',new THREE.BufferAttribute(depth,1));g.setAttribute('color',new THREE.BufferAttribute(colors,3));
 const mat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.18,metalness:.04,transparent:true,depthWrite:false,envMapIntensity:1.4});this.waterTime={value:0};mat.onBeforeCompile=shader=>{shader.uniforms.uTime=this.waterTime;shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nattribute float depth;varying float vDepth;varying vec2 vXZ;uniform float uTime;').replace('#include <begin_vertex>','#include <begin_vertex>\nvDepth=depth;vXZ=position.xz;transformed.y+=(sin(position.x*.35+uTime*1.1)+cos(position.z*.31-uTime*.9))*.035*smoothstep(0.,1.,depth);');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying float vDepth;varying vec2 vXZ;uniform float uTime;').replace('#include <color_fragment>','#include <color_fragment>\nfloat ripple=sin(vXZ.x*1.9+uTime*1.7+sin(vXZ.y*1.3))*.5+.5;float foam=smoothstep(.42,.04,vDepth)*(.55+.45*ripple);diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.95,.97,.94),foam*.75);diffuseColor.a=clamp(mix(.5,.9,smoothstep(0.,1.4,vDepth))+foam*.4,0.,.95)*smoothstep(-.05,.04,vDepth);');};
 const water=new THREE.Mesh(g,mat);water.position.y=WATER_LEVEL;water.receiveShadow=true;water.renderOrder=2;this.root.add(water);this.water=water;}
 // The board edge is cut like a model base: a soil cross-section down to the plinth.
 buildSkirt(){const s=this.sim.config,pos=[],colors=[],top=C(this.theme.low).multiplyScalar(.8),soil=C('#8a7255'),bottom=C('#5e4a36'),add=(x0,z0,x1,z1)=>{const h0=this.sim.heightAt(x0,z0),h1=this.sim.heightAt(x1,z1);for(const [x,z,y,c] of [[x0,z0,h0,top],[x0,z0,-4.05,bottom],[x1,z1,h1,top],[x1,z1,h1,top],[x0,z0,-4.05,bottom],[x1,z1,-4.05,bottom]]){pos.push(x,y,z);const k=c===top?smooth(-4,Math.max(h0,h1),y):0;tmp.copy(bottom).lerp(soil,.6).lerp(top,k);colors.push(tmp.r,tmp.g,tmp.b);}};for(let x=-62;x<62;x++){add(x,44,x+1,44);add(x+1,-44,x,-44);}for(let z=-44;z<44;z++){add(-62,z,-62,z+1);add(62,z+1,62,z);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,side:THREE.DoubleSide}));m.receiveShadow=true;this.root.add(m);
 if(this.water){const wp=[];const edge=(x0,z0,x1,z1)=>{const a=naturalHeight(s,x0,z0),b=naturalHeight(s,x1,z1);if(a>=WATER_LEVEL&&b>=WATER_LEVEL)return;wp.push(x0,WATER_LEVEL,z0,x0,Math.min(a,WATER_LEVEL),z0,x1,WATER_LEVEL,z1,x1,WATER_LEVEL,z1,x0,Math.min(a,WATER_LEVEL),z0,x1,Math.min(b,WATER_LEVEL),z1);};for(let x=-62;x<62;x++){edge(x,44,x+1,44);edge(x+1,-44,x,-44);}for(let z=-44;z<44;z++){edge(-62,z,-62,z+1);edge(62,z+1,62,z);}if(wp.length){const wg=new THREE.BufferGeometry();wg.setAttribute('position',new THREE.Float32BufferAttribute(wp,3));wg.computeVertexNormals();this.root.add(new THREE.Mesh(wg,new THREE.MeshStandardMaterial({color:'#5f9ea4',transparent:true,opacity:.72,roughness:.3,side:THREE.DoubleSide})));}}}

 // ---------- Architecture ----------
 towerStyle(){const s=this.sim.config,w=s.walls||{};return w.towers||(s.era==='medieval'&&w.shape==='round'?'round':'square');}
 wall(a,b,h=castleHeight(this.sim.config),thickness=.8,towers=true,options={}){const s=this.sim.config,dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz),yaw=Math.atan2(dx,dz),x=(a[0]+b[0])/2,z=(a[1]+b[1])/2,profile=wallProfile(s,a,b,h),y=profile.floor,stone=options.color||this.theme.wall,cap=C(stone).lerp(C('#fbf6ea'),.35).getStyle(),broad=thickness>1.4;h=profile.top-y;const front=options.breakable!==false&&Math.abs(x-s.end[0])<10&&Math.abs(dx)<Math.abs(dz)*.65&&s.kind!=='rings';
 if(front){const count=Math.ceil(length/2.5);for(let j=0;j<count;j++){const t=(j+.5)/count,px=a[0]+dx*t,pz=a[1]+dz*t,chunk=new THREE.Group();chunk.position.set(px,y,pz);chunk.rotation.y=yaw;this.root.add(chunk);this.box(thickness,h,length/count,stone,0,h/2,0,0,chunk);this.box(thickness+.25,.25,length/count,cap,0,h,0,0,chunk);if(!broad)for(const off of [-.65,.25])this.box(thickness+.1,.48,.42,cap,0,h+.32,off,0,chunk);else this.box(.35,.45,length/count,cap,-thickness/2+.18,h+.3,0,0,chunk);const body=this.physics.addBox(px,y+h/2,pz,thickness,h,length/count,yaw);body.wall=true;this.breakableWalls.push({group:chunk,body,z:pz,base:y,height:h,removed:false});}}
 else{this.box(thickness,h,length,stone,x,y+h/2,z,yaw);this.box(thickness+.25,.25,length,cap,x,y+h,z,yaw);this.box(thickness+.06,.35,length,C(stone).multiplyScalar(.88).getStyle(),x,y+.18,z,yaw);}
 if(!front){if(!broad)for(let d=.3;d<length;d+=1.05){const t=d/length;this.box(thickness+.1,.48,.42,cap,a[0]+dx*t,y+h+.32,a[1]+dz*t,yaw);}else{const ox=Math.cos(yaw)*(-thickness/2+.18),oz=-Math.sin(yaw)*(-thickness/2+.18);this.box(.35,.45,length,cap,x+ox,y+h+.3,z+oz,yaw);}const body=this.physics.addBox(x,y+h/2,z,thickness,h,length,yaw);body.wall=true;}
 if(towers)this.tower(a,profile,options);}
 tower(p,profile,options={}){const s=this.sim.config,style=options.style||this.towerStyle(),size=options.size||2.1,outline=options.outline||this.outline,v=outline.findIndex(q=>q[0]===p[0]&&q[1]===p[1]),adjacent=v>=0?wallProfile(s,outline[(v+outline.length-1)%outline.length],p).top:profile.top,floor=Math.min(...[[0,0],[1,1],[-1,1],[1,-1],[-1,-1]].map(([i,j])=>naturalHeight(s,p[0]+i*size*.5,p[1]+j*size*.5))),towerH=Math.max(profile.top,adjacent)-floor+1.2,cap=C(this.theme.tower).lerp(C('#fbf6ea'),.4).getStyle();
 if(style==='round'){this.part(new THREE.CylinderGeometry(size*.58,size*.66,towerH,12),this.theme.tower,p[0],floor+towerH/2,p[1]);this.part(new THREE.CylinderGeometry(size*.68,size*.68,.3,12),cap,p[0],floor+towerH+.02,p[1]);for(let k=0;k<6;k++){const a=k/6*Math.PI*2;this.box(.45,.5,.36,cap,p[0]+Math.cos(a)*size*.55,floor+towerH+.4,p[1]+Math.sin(a)*size*.55,-a);}if(options.roof!==false&&s.era==='medieval')this.part(new THREE.ConeGeometry(size*.72,1.6,12),palette.roof,p[0],floor+towerH+1.1,p[1]);}
 else{this.box(size,towerH,size,this.theme.tower,p[0],floor+towerH/2,p[1]);this.box(size+.3,.3,size+.3,cap,p[0],floor+towerH+.02,p[1]);for(const side of [-1,1])for(const off of [-.7,.7])this.box(.5,.5,.5,cap,p[0]+side*size*.4,floor+towerH+.4,p[1]+off*size/2.1);for(const side of [-1,1])this.box(.06,.42,.24,palette.dark,p[0]+side*(size/2+.01),floor+towerH*.62,p[1]);}
 this.physics.addBox(p[0],floor+towerH/2,p[1],size,towerH,size);}
 building(x,z,w=2.4,d=3.5,h=2.4,roof='flat'){const s=this.sim.config;if(![-1,1].every(dx=>[-1,1].every(dz=>insidePolygon(this.outline,x+dx*w*.56,z+dz*d*.56)))||this.physics.boxes.some(b=>b.active&&containsPoint(b,x,z,Math.hypot(w,d)/2+.5))||(s.clear||[]).some(([cx,cz,r])=>Math.hypot(x-cx,z-cz)<r+Math.hypot(w,d)/2))return false;const y=Math.min(...[[-1,-1],[1,-1],[-1,1],[1,1]].map(([i,j])=>naturalHeight(s,x+i*w/2,z+j*d/2)))-.05,wallColor=[this.theme.wall,'#efe5cf','#e2d2b4','#d7c7a6',palette.cream][Math.floor(hash(x,z)*5)],pitched=roof!=='flat';this.box(w,h,d,wallColor,x,y+h/2,z);const body=this.physics.addBox(x,y+(h+.1)/2,z,w,h+.1,d);if(pitched)this.physics.addRoof(body,w,d,h);this.box(w+.12,.2,d+.12,palette.stone,x,y+h,z);
 if(roof==='tile'){const g=new THREE.ConeGeometry(1,1,4);g.rotateY(Math.PI/4);g.scale(w*.78,.85,d*.78);this.part(g,['#b9765a','#a8684f','#c58867'][Math.floor(hash(z,x)*3)],x,y+h+.5,z);if(hash(x+1,z)>.6)this.box(.28,.6,.28,palette.darkStone,x+w*.25,y+h+.7,z-d*.15);}
 else if(roof==='thatch'){const g=new THREE.ConeGeometry(1,1,4);g.rotateY(Math.PI/4);g.scale(w*.82,1.25,d*.82);this.part(g,[palette.thatch,'#a88d58','#bda56c'][Math.floor(hash(z,x)*3)],x,y+h+.6,z);for(const side of [-1,1])this.box(.12,h,.12,palette.darkWood,x+side*w*.48,y+h/2,z+d*.48);}
 else{for(const side of [-1,1]){this.box(w,.35,.12,palette.stone,x,y+h+.22,z+side*d/2);this.box(.12,.35,d,palette.stone,x+side*w/2,y+h+.22,z);}const r=hash(x*3,z);if(r<.35)this.box(.6,.3,.6,palette.darkStone,x+.45,y+h+.17,z);else if(r<.6){this.box(w*.5,.05,d*.4,['#c7a77a','#b9644f','#8c9a7a'][Math.floor(r*30)%3],x-w*.15,y+h+.9,z+d*.1);for(const k of [-1,1])this.box(.05,.8,.05,palette.wood,x-w*.15+k*w*.24,y+h+.5,z+d*.1+d*.18);}else if(r<.75)this.part(new THREE.CylinderGeometry(.16,.2,.4,7),palette.bronze,x-w*.25,y+h+.3,z-d*.2);}
 const storeys=Math.max(1,Math.floor(h/1.25));for(let k=0;k<storeys;k++)for(const side of [-1,1])for(const off of [-.25,.25])this.box(.34,.5,.04,'#5c6058',x+w*off,y+.95+k*1.2,z+side*(d/2+.023));this.box(.5,1,.04,palette.wood,x,y+.5,z+d/2+.025);return true;}
 feature(name){const s=this.sim.config,[cx,cz]=s.fort,o=this.outline,ring=(f,height,options)=>{const pts=o.map(([x,z])=>[cx+(x-cx)*f,cz+(z-cz)*f]);for(let i=0;i<pts.length;i++)this.wall(pts[i],pts[(i+1)%pts.length],height,.75,true,{breakable:false,outline:pts,...options});};
 if(name==='palace'){for(let i=0;i<6;i++){const x=cx+2+i*1.7,z=-12,y=naturalHeight(s,x,z);this.box(1.35,1.65,9,palette.stone,x,y+.83,z);this.physics.addBox(x,y+.83,z,1.35,1.66,9);this.box(1.5,.18,9.2,palette.cream,x,y+1.75,z);}const y=naturalHeight(s,cx-4,12);this.box(7,.4,7,palette.darkStone,cx-4,y+.2,12);for(const side of [-1,1]){this.box(.3,1.4,7,palette.stone,cx-4+side*3.4,y+.7,12);this.physics.addBox(cx-4+side*3.4,y+.7,12,.3,1.4,7);}this.part(new THREE.CylinderGeometry(.8,.8,.1,14),'#5f7f80',cx+6,naturalHeight(s,cx+6,15)+.1,15);
  for(const [x,z] of [[-24,29],[-12,-34],[47,-29],[47,29]]){const h=naturalHeight(s,x,z);for(let i=0;i<3;i++)this.part(new THREE.ConeGeometry(1,1.2,4),palette.cream,x+i*2,h+.6,z,Math.PI/4);for(const side of [-1,1])this.box(.25,.4,8,palette.darkStone,x+side*3.5,h+.2,z);}}
 else if(name==='innerWalls'){this.wall([cx-7,-19],[cx-7,20],3,.7,true,{breakable:false});this.wall([cx+5,-19],[cx+5,20],3.6,.8,true,{breakable:false});}
 else if(name==='fortress'){const y=naturalHeight(s,cx+8,-13);this.box(7,.75,9,palette.stone,cx+8,y+.38,-13);this.box(4.5,5,7,palette.cream,cx+8,y+3,-13);this.physics.addBox(cx+8,y+2.9,-13,6,5.8,9);for(const z of [-16,-14,-12,-10])for(const x of [cx+5.5,cx+10.5])this.part(new THREE.CylinderGeometry(.23,.27,3.8,8),palette.stone,x,y+2.8,z);this.box(6,.4,9,palette.cream,cx+8,y+5.6,-13);}
 else if(name==='landWalls'){for(const x of [cx-20,cx-24])this.wall([x,-24],[x,25],x===cx-20?3.3:1.8,.75,true);this.box(7,.2,54,'#8f9177',cx-29,.02,0);}
 else if(name==='keep'){const y=naturalHeight(s,cx,cz),h=9;this.part(new THREE.CylinderGeometry(2.2,2.6,h,16),this.theme.tower,cx,y+h/2,cz);this.part(new THREE.CylinderGeometry(2.5,2.5,.35,16),palette.cream,cx,y+h,cz);for(let k=0;k<10;k++){const a=k/10*Math.PI*2;this.box(.5,.55,.4,palette.cream,cx+Math.cos(a)*2.3,y+h+.45,cz+Math.sin(a)*2.3,-a);}this.physics.addBox(cx,y+h/2,cz,4.4,h,4.4);}
 else if(name==='innerWall')ring(.55,3.2,{style:'round',size:1.6});
 else if(name==='innerRing')ring(.72,3,{size:1.8});
 else if(name==='chapel'){const x=cx+3.6,z=cz-3.6,y=naturalHeight(s,x,z);this.box(2.2,2.2,3.2,palette.cream,x,y+1.1,z);const r=prism(2.4,1.3,3.4);this.part(r,palette.roof,x,y+2.2,z);this.box(.5,1.2,.5,palette.cream,x,y+3.2,z+1.5);this.physics.addBox(x,y+1.2,z,2.2,2.4,3.2);}
 else if(name==='temple'){const y=naturalHeight(s,cx,cz);this.box(12,.5,10,palette.stone,cx,y+.25,cz);for(const side of [-1,1]){this.box(12,1.8,.5,palette.cream,cx,y+.9,cz+side*5);this.physics.addBox(cx,y+.9,cz+side*5,12,1.8,.5);}for(let k=0;k<3;k++){const x=cx-3.5+k*3.5;this.box(2.8,3.6,3.6,k===1?'#efe4cc':palette.cream,x,y+1.8,cz+2);this.physics.addBox(x,y+1.8,cz+2,2.8,3.6,3.6);this.part(new THREE.CylinderGeometry(1.3,1.3,.3,12,1,false,0,Math.PI),palette.stone,x,y+3.6,cz+3.81,Math.PI/2);for(const off of [-.9,.9])this.part(new THREE.CylinderGeometry(.18,.2,2.6,8),palette.stone,x+off,y+1.3,cz+3.9);}}
 else if(name==='bridgeFort'){const top=Math.max(...o.map(p=>p[1])),x=cx,y=.3;this.box(2.2,.35,24,palette.darkStone,x,y+.2,top+12);for(let z=top+2;z<top+24;z+=3)this.box(2.4,1.6,.7,palette.darkStone,x,-.5,z);const fz=top+25;this.box(4,4.2,4,this.theme.tower,x,1.6,fz);this.box(4.4,.3,4.4,palette.cream,x,3.75,fz);for(const side of [-1,1])this.box(1.2,5.2,1.2,this.theme.tower,x+side*2,2.1,fz);this.physics.addBox(x,1.6,fz,4,4.2,4);}
 else if(name==='cothon'){const [bx,bz]=s.clear?.[0]||[cx-6,11];this.part(new THREE.CylinderGeometry(1.6,1.8,.9,16),palette.stone,bx,WATER_LEVEL+.4,bz);this.part(new THREE.CylinderGeometry(1.1,1.1,1.6,12),palette.cream,bx,WATER_LEVEL+1.6,bz);for(let k=0;k<16;k++){const a=k/16*Math.PI*2;this.box(.5,.7,1.6,palette.cream,bx+Math.cos(a)*4.6,.35,bz+Math.sin(a)*4.6,-a+Math.PI/2);}}
 else if(name==='turrets'){for(let i=0;i<o.length;i++){const a=o[i],b=o[(i+1)%o.length],len=Math.hypot(b[0]-a[0],b[1]-a[1]),top=wallProfile(s,a,b).top;for(let d=3;d<len-2;d+=5.5){const t=d/len,x=a[0]+(b[0]-a[0])*t,z=a[1]+(b[1]-a[1])*t;this.box(1.1,1.4,1.1,palette.hide,x,top+.95,z,Math.atan2(b[0]-a[0],b[1]-a[1]));this.box(1.3,.12,1.3,palette.darkWood,x,top+1.7,z);}}}
 else if(name==='spring'){const x=s.end[0]+.5,z=3.2,y=naturalHeight(s,x,z);this.part(new THREE.CylinderGeometry(1.3,1.5,.12,16),'#6ea3ad',x,y+.06,z);for(let k=0;k<9;k++){const a=k/9*Math.PI*2;this.part(new THREE.DodecahedronGeometry(.22,0),palette.darkStone,x+Math.cos(a)*1.45,y+.1,z+Math.sin(a)*1.45);}}
 else if(name==='citadel'){const y=naturalHeight(s,cx,cz);this.box(6,3,5,palette.cream,cx,y+1.5,cz);this.physics.addBox(cx,y+1.5,cz,6,3,5);for(const [i,j] of [[-1,-1],[1,-1],[-1,1],[1,1]]){this.box(1.6,4.2,1.6,this.theme.tower,cx+i*3,y+2.1,cz+j*2.5);this.physics.addBox(cx+i*3,y+2.1,cz+j*2.5,1.6,4.2,1.6);}}
 else if(name==='ringCamps'){const r=ringSpec(s);for(let k=0;k<8;k++){const a=k/8*Math.PI*2+.3,p=ringPoint(s,0,a,1.22),y=naturalHeight(s,p.x,p.z);for(const [w,d,ox,oz] of [[4,.4,0,-2],[4,.4,0,2],[.4,4,-2,0],[.4,4,2,0]])this.box(w,.5,d,'#b8a27e',p.x+ox,y+.25,p.z+oz,a);}}}
 buildArchitecture(){const s=this.sim.config,[cx,cz]=s.fort,W=s.walls||{};this.outline=fortressOutline(s);for(let i=0;i<this.outline.length;i++)this.wall(this.outline[i],this.outline[(i+1)%this.outline.length],castleHeight(s),W.thickness||.8,hasTower(s,i));
 for(const f of s.features||[])this.feature(f);
 // Houses fill the circuit, keeping clear of walls, features and open ground.
 const xs=this.outline.map(p=>p[0]),zs=this.outline.map(p=>p[1]),roof=s.roofs||'flat';for(let x=Math.min(...xs)+7;x<Math.max(...xs)-4;x+=4.4)for(let z=Math.min(...zs)+4;z<Math.max(...zs)-3;z+=5.1){const h=(s.tall?2.4:1.3)+this.random()*(s.tall?3.2:2.5),jx=this.random()*.5,jz=this.random()*.4;if(this.random()>(s.houses??1))continue;this.building(x+jx,z+jz,2.6,3.4,h,roof);}
 const c=campLayout(s),round=s.faction==='Ottoman',banner=s.dress?.soldier?.shieldColor||palette.red;for(let row=0;row<c.rows;row++)for(let col=0;col<c.cols;col++){const x=c.x+col*3.6,z=c.z+row*4.2,y=naturalHeight(s,x,z),cloth=row%2?palette.canvas:'#d9cdb0';if(round){this.part(new THREE.CylinderGeometry(1.05,1.05,.7,10),cloth,x,y+.35,z);this.part(new THREE.ConeGeometry(1.15,1,10),row%2?'#e9e1cc':'#c9b48e',x,y+1.2,z);}else{this.part(prism(1.75,1.25,2.2),cloth,x,y,z);this.box(.07,1.35,.07,palette.wood,x,y+.67,z+1.12);this.box(.07,1.35,.07,palette.wood,x,y+.67,z-1.12);}this.physics.addBox(x,y+.6,z,1.84,1.2,2.27);this.box(.65,.03,1.6,'#9c957c',x,y+.02,z+1.5);}
 const fz=c.z+(c.rows>2?6.3:2.1),fy=naturalHeight(s,c.x+c.w/3,fz);for(const dx of [-2.5,2.5])this.box(.09,5,.09,palette.wood,c.x+c.w/3+dx,fy+2.5,fz);const flag=new THREE.Mesh(new THREE.PlaneGeometry(3.1,1.2,10,3),new THREE.MeshStandardMaterial({color:banner,roughness:.9,side:THREE.DoubleSide}));flag.position.set(c.x+c.w/3,fy+4,fz);flag.castShadow=true;this.root.add(flag);this.banners.push(flag);
 for(let i=0;i<16;i++){const x=c.x+this.random()*c.w*.7,z=c.side<0?c.z-2.6-this.random()*1.2:c.z+c.d+2.6+this.random()*1.2,h=.2+this.random()*.25;this.box(.8,h,.5,palette.wood,x,naturalHeight(s,x,z)+h/2,z,this.random());}
 if(s.kind==='rings'){// Ditch footprints show where the lines will run before building begins.
 const r=ringSpec(s);for(const [rx,rz] of r.single?[r.inner]:[r.inner,r.outer]){const points=Array.from({length:181},(_,i)=>{const a=r.a0+(r.a1-r.a0)*i/180,x=r.cx+Math.cos(a)*rx,z=r.cz+Math.sin(a)*rz;return new THREE.Vector3(x,naturalHeight(s,x,z)+.03,z)});const line=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points,r.full),180,.34,4,r.full),this.material('#8f9076'));line.receiveShadow=true;this.root.add(line);}}
 this.physics.settle?.();}
 buildVegetation(){const s=this.sim.config,c=campLayout(s),flora=s.flora||(['tyre','acre','carthage'].includes(s.id)?['palm','olive','shrub']:FLORA[s.theme]||FLORA.dry),count={green:150,dry:85,coast:70,desert:34}[s.theme]||60,route=this.sim.cartRoute;let placed=0;
 for(let attempt=0;attempt<count*6&&placed<count;attempt++){const x=(this.random()-.5)*118,z=(this.random()-.5)*82,y=naturalHeight(s,x,z),type=flora[Math.floor(this.random()*flora.length)],size=.75+this.random()*.6;if(y<WATER_LEVEL+.5||insidePolygon(this.outline,x,z)||Math.hypot(x-s.fort[0],z-s.fort[1])<10||this.nearWorks(x,z,1.5)||x>c.x-4&&x<c.x+c.w+4&&z>c.z-6&&z<c.z+c.d+3||x>route.left-4&&x<route.right+4&&Math.abs(z-route.z)<route.r+2.5||this.physics.boxes.some(b=>b.active&&containsPoint(b,x,z,1.4)))continue;const e=.5,slope=Math.abs(naturalHeight(s,x+e,z)-naturalHeight(s,x-e,z))+Math.abs(naturalHeight(s,x,z+e)-naturalHeight(s,x,z-e));if(slope>1.6)continue;this.plant(type,x,y,z,size);placed++;}}
 plant(type,x,y,z,k=1){const leaf=C(type==='olive'?'#8d9a7a':type==='cypress'?'#55704c':type==='palm'?'#7f9a55':this.theme===THEMES.green?'#6f8d55':'#8c9a68').multiplyScalar(.85+hash(x,z)*.3).getStyle(),bark=type==='palm'?'#9a8462':'#6e5a42';
 if(type==='conifer'){this.part(new THREE.CylinderGeometry(.08*k,.13*k,1.1*k,5),bark,x,y+.55*k,z);this.part(new THREE.ConeGeometry(.95*k,1.9*k,7),leaf,x,y+1.7*k,z);this.part(new THREE.ConeGeometry(.7*k,1.4*k,7),leaf,x,y+2.6*k,z);}
 else if(type==='deciduous'){this.part(new THREE.CylinderGeometry(.09*k,.15*k,1.2*k,5),bark,x,y+.6*k,z);for(const [ox,oy,oz,r] of [[0,1.85,0,.95],[.45,1.6,.2,.62],[-.4,1.65,-.25,.66]])this.part(new THREE.IcosahedronGeometry(r*k,0),leaf,x+ox*k,y+oy*k,z+oz*k,hash(x,z)*6);}
 else if(type==='olive'){this.part(new THREE.CylinderGeometry(.1*k,.17*k,.8*k,5),bark,x,y+.4*k,z);const g=new THREE.IcosahedronGeometry(.85*k,0);g.scale(1.2,.7,1.1);this.part(g,leaf,x,y+1.15*k,z,hash(z,x)*6);}
 else if(type==='cypress'){this.part(new THREE.CylinderGeometry(.07*k,.1*k,.6*k,5),bark,x,y+.3*k,z);const g=new THREE.ConeGeometry(.42*k,3*k,7);this.part(g,leaf,x,y+1.9*k,z);}
 else if(type==='acacia'){this.part(new THREE.CylinderGeometry(.07*k,.12*k,1.5*k,5),bark,x,y+.75*k,z);const g=new THREE.IcosahedronGeometry(1*k,0);g.scale(1.5,.35,1.3);this.part(g,'#8f9662',x,y+1.6*k,z,hash(x,z)*6);}
 else if(type==='palm'){let px=x,py=y,lean=hash(x,z)-.5;for(let i=0;i<4;i++){this.part(new THREE.CylinderGeometry(.09*k,.12*k,.75*k,6),bark,px,py+.37*k,z+lean*i*.12);py+=.72*k;px+=lean*.1;}for(let f=0;f<7;f++){const a=f/7*Math.PI*2,g=new THREE.BoxGeometry(.18*k,.04*k,1.5*k);g.translate(0,0,.7*k);g.rotateX(.45);g.rotateY(a);this.part(g,leaf,px,py,z+lean*.5);}}
 else{const g=new THREE.IcosahedronGeometry(.45*k,0);g.scale(1.2,.75,1.1);this.part(g,leaf,x,y+.25*k,z,hash(z,x)*6);}}

 // ---------- Siege works ----------
 buildWorks(){const s=this.sim.config,n=this.sim.built.length;this.workBlocks=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:s.kind==='causeway'?'#beb9a2':s.kind==='trenches'?'#a89270':'#c6a883',roughness:.95}),s.kind==='trenches'?n*2:n);this.workBlocks.castShadow=this.workBlocks.receiveShadow=true;this.workBlocks.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.workBlocks.frustumCulled=false;this.root.add(this.workBlocks);this.stakes=new THREE.InstancedMesh(new THREE.CylinderGeometry(.055,.08,1,5),new THREE.MeshStandardMaterial({color:palette.wood,roughness:.9}),n*4);this.stakes.castShadow=true;this.stakes.frustumCulled=false;this.root.add(this.stakes);
 this.ringTowers=s.kind==='rings'?new THREE.InstancedMesh(mergeGeometries([new THREE.BoxGeometry(1.3,.12,1.3).translate(0,2.6,0),...[[-1,-1],[1,-1],[-1,1],[1,1]].map(([i,j])=>new THREE.BoxGeometry(.12,2.7,.12).translate(i*.55,1.35,j*.55)),new THREE.BoxGeometry(1.35,.6,.08).translate(0,2.95,.62),new THREE.BoxGeometry(1.35,.6,.08).translate(0,2.95,-.62)]),new THREE.MeshStandardMaterial({color:'#8a7352',roughness:.9}),Math.ceil(n/10)):null;if(this.ringTowers){this.ringTowers.castShadow=true;this.ringTowers.frustumCulled=false;this.root.add(this.ringTowers);}
 this.gabions=s.era==='early modern'&&s.kind==='trenches'?new THREE.InstancedMesh(new THREE.CylinderGeometry(.42,.42,.9,9),new THREE.MeshStandardMaterial({color:'#9b8256',roughness:1}),n):null;if(this.gabions){this.gabions.castShadow=true;this.gabions.frustumCulled=false;this.root.add(this.gabions);}this.dummy=new THREE.Object3D();}
 updateWorks(){if(this.revision===this.sim.revision)return;const s=this.sim.config,N=this.sim.built.length,d=this.dummy,hide=()=>d.scale.setScalar(0);let tower=0;for(let i=0;i<N;i++){const p=workPoint(s,i/(N-1)),h=this.sim.built[i]/5,full=this.sim.built[i]/this.sim.capacity[i],base=this.sim.base[i],r=s.kind==='rings'?ringSpec(s):null,yaw=r?Math.atan2(-(p.x-r.cx)/r.inner[0],(p.z-r.cz)/r.inner[1]):s.kind==='trenches'?Math.atan2(1,Math.cos(i/(N-1)*Math.PI*7)*.5):Math.PI/2;d.position.set(p.x,base+h*.5,p.z);d.rotation.set(0,yaw,0);d.scale.set(1,1,1);if(s.kind!=='trenches')hide();d.updateMatrix();
 if(s.kind==='trenches'){const left=workPoint(s,Math.max(0,(i-.5)/(N-1))),right=workPoint(s,Math.min(1,(i+.5)/(N-1))),heading=Math.atan2(right.x-left.x,right.z-left.z);for(let side=0;side<2;side++){d.rotation.set(0,heading,0);d.position.set(p.x+Math.cos(heading)*(side?1:-1)*1.8,base+h*.25,p.z-Math.sin(heading)*(side?1:-1)*1.8);d.scale.set(.45,h*.5,Math.hypot(right.x-left.x,right.z-left.z)+.05);if(h<.001)hide();d.updateMatrix();this.workBlocks.setMatrixAt(i*2+side,d.matrix);}if(this.gabions){d.position.set(p.x+Math.cos(heading)*2.3,base+.45,p.z-Math.sin(heading)*2.3);d.rotation.set(0,0,0);d.scale.setScalar(full>.6?1:0);d.updateMatrix();this.gabions.setMatrixAt(i,d.matrix);}}else this.workBlocks.setMatrixAt(i,d.matrix);
 for(let j=0;j<4;j++){d.rotation.set(0,0,0);d.position.set(p.x+(j%2?1:-1)*(s.kind==='rings'?.4:2.8),base+h/2+(s.kind==='rings'?h*.55:0),p.z+(j<2?-.2:.2));d.scale.set(1,Math.max(.01,h+(s.kind==='rings'?.6:0)),1);if(h<.001)hide();d.updateMatrix();this.stakes.setMatrixAt(i*4+j,d.matrix);}
 if(this.ringTowers&&i%10===5){d.position.set(p.x,base+h,p.z);d.rotation.set(0,yaw,0);d.scale.setScalar(full>.7?1:0);d.updateMatrix();this.ringTowers.setMatrixAt(tower++,d.matrix);}}
 const pos=this.terrain.geometry.attributes.position,changed=[];for(let i=0;i<pos.count;i++){const h=this.sim.heightAt(pos.getX(i),pos.getZ(i));if(Math.abs(h-this.heights[i])>1e-5){this.heights[i]=h;pos.setY(i,h);changed.push(i);}}if(changed.length||this.revision<0){pos.needsUpdate=true;this.terrain.geometry.computeVertexNormals();if(this.revision<0)this.bakeOcclusion();this.paintTerrain(this.terrain.geometry,this.revision<0?null:changed);}
 this.workBlocks.instanceMatrix.needsUpdate=true;this.stakes.instanceMatrix.needsUpdate=true;if(this.ringTowers)this.ringTowers.instanceMatrix.needsUpdate=true;if(this.gabions)this.gabions.instanceMatrix.needsUpdate=true;this.revision=this.sim.revision;}

 // ---------- Engines ----------
 engineType(){const s=this.sim.config;return s.engine||(s.kind==='battery'||s.kind==='trenches'?(s.era==='ancient'?'ballista':s.era==='medieval'?'trebuchet':'cannon'):'tower');}
 // Engines face local +z, which the group turns toward the walls.
 buildEngine(){const s=this.sim.config,type=this.engineType();this.engine=new THREE.Group();this.root.add(this.engine);this.engineKind=type;this.arm=null;this.barrel=null;this.ramBeam=null;this.bridge=null;const E=this.engine,add=(w,h,d,c,x,y,z,kind)=>this.box(w,h,d,c,x,y,z,0,E,kind);
 if(type==='tower'||type==='helepolis'||type==='brick'){const stories=s.stories||(type==='helepolis'?9:4),step=type==='helepolis'?1.5:1.9,top=1.4+stories*step,iron=type==='helepolis'||s.id==='jotapata',clad=iron?palette.iron:palette.hide,frame=type==='brick'?palette.brick:palette.wood,width=type==='helepolis'?4:3.4,clothKind=iron?'metal':undefined;
 for(let k=0;k<stories;k++){const y=1.4+k*step,w=width*(1-k*(type==='helepolis'?.035:.02));add(w+.3,.22,w,frame,0,y,0);for(const x of [-1,1])add(.16,step*.7,w,type==='brick'?palette.brick:k%2?clad:frame,x*(w/2+.08),y+step*.42,0,type==='brick'?undefined:k%2?clothKind:undefined);add(w,step*.7,.16,type==='brick'?palette.brick:clad,0,y+step*.42,w/2+.08,type==='brick'?undefined:clothKind);add(w,step*.7,.16,frame,0,y+step*.42,-w/2-.08);if(type!=='brick')add(.6,.32,.2,palette.dark,k%2?.7:-.7,y+step*.5,w/2+.18);}
 if(type!=='brick'){for(const x of [-1,1])for(const z of [-1,1])add(.18,top-.6,.18,'#6f6650',x*width*.44,top/2,z*width*.44);for(const side of [-1,1]){const beam=add(.14,top-.6,.14,palette.darkStone,side*width*.44,top/2,0);beam.rotation.x=side*.31;}}
 add(width+.6,.3,width+.3,palette.cream,0,top+.4,0);for(const side of [-1,1])for(const off of [-1.2,0,1.2])add(.45,.45,.45,palette.cream,off,top+.75,side*(width/2));
 this.bridge=new THREE.Group();this.bridge.position.set(0,top-.4,width/2+.1);E.add(this.bridge);this.box(2.2,2.6,.12,palette.wood,0,1.3,0,0,this.bridge);
 if(type!=='brick'){this.ramBeam=add(.45,.45,4.8,palette.darkStone,0,1.9,1.6);this.box(.6,.6,.5,palette.metal,0,0,2.4,0,this.ramBeam,'metal');}
 this.engineTop=top;if(type==='brick'){this.engine.userData.static=true;this.addFoot(0,0);}else{const rows=type==='helepolis'?[-1.8,-.6,.6,1.8]:[-1.2,1.2];for(const z of rows)for(const x of [-1.65,1.65])this.addWheel(x*(width/3.4),z,.65);}}
 else if(type==='ram'){add(2.4,1.6,5.2,palette.hide,0,1.6,0);add(2.6,.2,5.4,palette.darkWood,0,.85,0);this.part(new THREE.CylinderGeometry(.85,1,2,10),palette.hide,0,3.2,1.5,0,E);this.part(new THREE.SphereGeometry(.9,10,6,0,Math.PI*2,0,Math.PI/2),palette.wood,0,4.2,1.5,0,E);this.ramBeam=add(.38,.38,4.6,palette.darkStone,0,1.7,1.4);this.box(.55,.55,.55,palette.metal,0,0,2.4,0,this.ramBeam,'metal');this.engineTop=4.6;for(const z of [-2,0,2])for(const x of [-1.1,1.1])this.addWheel(x,z,.55);}
 else if(type==='cannon'||type==='bombard'){const big=type==='bombard';if(big){add(2.4,.6,6,palette.darkWood,0,.4,0);for(const z of [-2,0,2])add(2.8,.4,.4,palette.wood,0,.85,z);const screen=add(4,2.8,.25,palette.wood,0,1.4,3.6);screen.rotation.x=-.12;}else{for(const side of [-1,1])add(.18,.8,2.6,palette.darkWood,side*.45,.95,0);add(.3,.3,3.4,palette.darkWood,0,.55,-1.4);}
 this.barrel=new THREE.Group();this.barrel.position.set(0,big?1.5:1.35,big?0:.2);E.add(this.barrel);const len=big?5.4:3,r=big?.62:.32;this.part(new THREE.CylinderGeometry(r*.85,r,len,16),palette.bronze,0,0,0,0,this.barrel,'metal').rotation.x=Math.PI/2;for(const t of [-.4,.1,.45])this.part(new THREE.CylinderGeometry(r*1.08,r*1.08,.18,16),'#8a6a3a',0,0,t*len,0,this.barrel,'metal').rotation.x=Math.PI/2;this.part(new THREE.CylinderGeometry(r*.5,r*.5,.1,12),palette.dark,0,0,len/2+.02,0,this.barrel).rotation.x=Math.PI/2;this.barrel.rotation.x=-.12;this.engineTop=big?1.5:1.35;this.muzzle=len/2;if(big)this.addFoot(0,0);else for(const x of [-1.2,1.2])this.addWheel(x,.2,.75);}
 else if(type==='trebuchet'){for(const side of [-1,1]){const a=add(.2,5,.2,palette.wood,side*.8,2.5,-1);a.rotation.x=-.32;const b=add(.2,5,.2,palette.wood,side*.8,2.5,1);b.rotation.x=.32;add(.24,.24,3.8,palette.darkWood,side*.8,.2,0);}add(1.9,.2,.2,palette.darkStone,0,4.75,0);this.arm=new THREE.Group();this.arm.position.set(0,4.75,0);E.add(this.arm);this.box(.22,.22,7.4,palette.wood,0,0,-1.4,0,this.arm);this.box(1.2,1.2,1.3,palette.darkStone,0,-.8,2.3,0,this.arm);this.box(.08,.08,1.6,palette.dark,0,-.3,-5,0,this.arm);this.arm.rotation.x=-.75;this.engineTop=5;this.addFoot(0,-1.2);this.addFoot(0,1.2);}
 else{add(1.6,.5,3,palette.darkWood,0,.9,0);add(.3,1.1,.3,palette.wood,0,.4,0);add(2.8,.35,.5,palette.wood,0,1.35,.6);for(const side of [-1,1]){const arm=add(.12,.12,1.2,palette.darkWood,side*1.2,1.4,.1);arm.rotation.y=side*.5;}add(2.4,.04,.04,'#d8d0b8',0,1.42,-.2);this.engineTop=1.6;this.addFoot(0,-1);this.addFoot(0,1);}
 this.engine.rotation.y=Math.PI/2;this.engine.visible=s.kind!=='rings';
 // A small support engine near the start of the works.
 this.artillery=new THREE.Group();this.root.add(this.artillery);const A=this.artillery;if(s.era==='early modern'){this.box(1.4,.5,2,palette.darkWood,0,.6,0,0,A);this.part(new THREE.CylinderGeometry(.22,.28,1.8,12),palette.bronze,0,1.1,.3,0,A,'metal').rotation.x=Math.PI/2-.2;this.throwArm=new THREE.Object3D();}else{this.box(2,.2,2.4,palette.wood,0,.5,0,0,A);this.box(2.3,.14,.25,palette.darkStone,0,1.2,0,0,A);for(const x of [-.85,.85])this.box(.13,1.6,.18,palette.wood,x,1,0,0,A);this.throwArm=this.box(.12,2.1,.14,palette.wood,0,1.7,0,0,A);this.throwArm.rotation.x=-.45;}A.position.set(s.start[0]-2,naturalHeight(s,s.start[0]-2,7),7);A.rotation.y=-Math.PI/2;}
 addWheel(x,z,r){const wheel=this.part(new THREE.CylinderGeometry(r,r,.24,14),palette.darkWood,x,r,z,0,this.engine);wheel.rotation.z=Math.PI/2;this.part(new THREE.CylinderGeometry(r*.25,r*.25,.3,8),palette.wood,0,0,0,0,wheel);const axle=this.part(new THREE.CylinderGeometry(.08,.08,.35,8),palette.darkStone,x,r,z,0,this.engine);axle.rotation.z=Math.PI/2;const support=this.box(.13,1,.13,palette.darkStone,x,1,z,0,this.engine);wheel.userData={axle,support,r};this.wheels.push(wheel);this.feet.push({x,z});}
 addFoot(x,z){this.feet.push({x,z});}

 // ---------- Carts, people, details ----------
 buildCarts(){this.carts=[];for(let i=0;i<5;i++){const cart=new THREE.Group();this.box(1,.25,1.5,palette.wood,0,.55,0,0,cart);for(const side of [-1,1]){this.box(.09,.55,1.5,palette.wood,side*.5,.83,0,0,cart);const wheel=this.part(new THREE.CylinderGeometry(.34,.34,.1,10),palette.darkWood,side*.62,.34,0,0,cart);wheel.rotation.z=Math.PI/2;cart.userData.wheels??=[];cart.userData.wheels.push(wheel);}this.box(.8,.22,1.2,i%2?palette.sand:'#b9a489',0,.88,0,0,cart);for(const side of [-1,1])this.box(.06,.06,1.3,palette.wood,side*.3,.55,1.3,0,cart);
 // A mule in the shafts.
 const mule=new THREE.Group();mule.position.set(0,0,2.05);cart.add(mule);const coat=['#7a6650','#5f5246','#8b765c'][i%3];this.box(.45,.5,1.15,coat,0,.85,0,0,mule);const neck=this.box(.24,.5,.28,coat,0,1.15,.62,0,mule);neck.rotation.x=-.6;this.box(.22,.24,.5,coat,0,1.32,.88,0,mule);for(const side of [-1,1])this.box(.05,.22,.06,coat,side*.08,1.52,.78,0,mule);const legs=[];for(const [lx,lz] of [[-.15,.42],[.15,.42],[-.15,-.42],[.15,-.42]]){const leg=new THREE.Group();leg.position.set(lx,.62,lz);mule.add(leg);this.box(.1,.6,.1,coat,0,-.3,0,0,leg);legs.push(leg);}cart.userData.legs=legs;this.root.add(cart);this.carts.push(cart);}
 this.physics.cartBodies=this.sim.carts.map(c=>{const body=this.physics.addBox(c.x,this.sim.surfaceHeight(c.x,c.z)+.62,c.z,1.4,1.1,3.4,c.heading);body.type=4;body.obstacle.moving=true;body.obstacle.offset=.85;return body;});}
 buildActors(){const n=this.sim.agents.length,mat=new THREE.MeshStandardMaterial({roughness:.82});this.actorParts={};const part=(name,geo,total=n,material=mat)=>{const mesh=new THREE.InstancedMesh(geo,material,total);mesh.castShadow=mesh.receiveShadow=true;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.userData.actorPart=name;mesh.userData.per=total/n;this.root.add(mesh);this.actorParts[name]=mesh;this.actorTargets.push(mesh);return mesh;};
 const torso=new THREE.BoxGeometry(.4,.46,.26);{const p=torso.attributes.position;for(let i=0;i<p.count;i++)if(p.getY(i)<0){p.setX(i,p.getX(i)*.86);p.setZ(i,p.getZ(i)*.9);}}part('torso',torso);part('skirt',new THREE.CylinderGeometry(.19,.25,.3,8));part('head',new THREE.SphereGeometry(.19,10,8));part('cap',new THREE.SphereGeometry(.205,10,6,0,Math.PI*2,0,Math.PI*.55));part('cone',new THREE.ConeGeometry(.17,.36,8));part('tallcap',new THREE.CylinderGeometry(.12,.17,.44,8));part('brim',new THREE.CylinderGeometry(.31,.31,.03,14));part('crest',new THREE.BoxGeometry(.05,.15,.34));
 part('arms',new THREE.BoxGeometry(.11,.44,.12).translate(0,-.2,0),n*2);part('legs',new THREE.BoxGeometry(.13,.46,.14).translate(0,-.23,0),n*2);part('shield',new THREE.BoxGeometry(.42,.64,.07));part('roundShield',new THREE.CylinderGeometry(.27,.27,.05,16).rotateX(Math.PI/2));part('sword',new THREE.BoxGeometry(.05,.62,.03).translate(0,.25,0));part('spear',mergeGeometries([new THREE.CylinderGeometry(.018,.018,2.1,5).translate(0,.5,0),new THREE.ConeGeometry(.045,.2,5).translate(0,1.65,0)]));part('musket',mergeGeometries([new THREE.BoxGeometry(.045,1.15,.05).translate(0,.3,0),new THREE.BoxGeometry(.07,.32,.09).translate(0,-.35,0)]));part('bow',new THREE.TorusGeometry(.38,.016,4,12,Math.PI*.9).rotateZ(-Math.PI*.45).rotateY(-Math.PI/2));part('basket',new THREE.CylinderGeometry(.21,.15,.29,8));part('tool',mergeGeometries([new THREE.BoxGeometry(.035,.8,.035).translate(0,.2,0),new THREE.BoxGeometry(.24,.06,.06).translate(0,.6,0)]));part('torch',new THREE.CylinderGeometry(.025,.032,.5,5).translate(0,.2,0));
 this.actorRoot=new THREE.Object3D();this.local=new THREE.Object3D();this.m1=new THREE.Matrix4();this.m2=new THREE.Matrix4();this.m3=new THREE.Matrix4();this.zero=new THREE.Matrix4().makeScale(0,0,0);this.colors=new Map();this.looks=this.sim.agents.map(a=>this.look(a));
 const geom=new THREE.TorusGeometry(.42,.03,5,28);geom.rotateX(-Math.PI/2);this.selection=new THREE.Mesh(geom,new THREE.MeshBasicMaterial({color:'#fff6cf',depthWrite:false,transparent:true}));this.selection.visible=false;this.selection.renderOrder=7;this.root.add(this.selection);
 this.projectileMesh=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(.22,0),new THREE.MeshStandardMaterial({color:'#8d8676',roughness:.9}),100);this.projectileMesh.castShadow=true;this.projectileMesh.frustumCulled=false;this.root.add(this.projectileMesh);this.arrowMesh=new THREE.InstancedMesh(mergeGeometries([new THREE.CylinderGeometry(.012,.012,.62,4),new THREE.ConeGeometry(.03,.08,4).translate(0,.33,0),new THREE.BoxGeometry(.06,.1,.005).translate(0,-.27,0)]).rotateX(Math.PI/2),new THREE.MeshStandardMaterial({color:'#6b5a44',roughness:.9}),64);this.arrowMesh.frustumCulled=false;this.root.add(this.arrowMesh);this.ballMesh=new THREE.InstancedMesh(new THREE.SphereGeometry(.06,6,4),new THREE.MeshStandardMaterial({color:'#4c4c4a',roughness:.5,metalness:.4}),64);this.ballMesh.frustumCulled=false;this.root.add(this.ballMesh);}
 // Each figure gets a fixed look from their side's dress: tunic, skin, headgear, shield and weapon.
 look(a){const s=this.sim.config,dress=s.dress||{},kit=dress[a.role==='defender'?'defender':a.role]||dress.soldier||{},pick=(list,k)=>Array.isArray(list)?list[Math.floor(hash(a.id,k)*list.length)%list.length]:list,worker=a.role==='worker',j=a.id-s.workers-s.soldiers,archer=a.role==='defender'&&j%2===(s.kind==='rings'?1:0);let weapon=worker?'none':kit.weapon||'spear';if(archer)weapon=dress.missile==='musket'?'musket':'bow';const officer=a.role==='soldier'&&(a.id-s.workers)%8===0&&!!kit.crest;return{tunic:pick(kit.tunic||['#c7af87'],1),skin:pick(SKIN,2),head:kit.head||'cap',headColor:kit.headColor||'#9b8663',legs:kit.legs||'#675f4d',shield:worker||weapon==='musket'||weapon==='bow'?'none':kit.shield||'none',shieldColor:kit.shieldColor||'#a3402f',weapon,crest:officer?kit.crest:null};}
 color(hex){let c=this.colors.get(hex);if(!c){c=new THREE.Color(hex);this.colors.set(hex,c);}return c;}
 put(name,i,matrix,hex){const mesh=this.actorParts[name];mesh.setMatrixAt(i,matrix);if(hex)mesh.setColorAt(i,this.color(hex));}
 local4(x,y,z,rx=0,ry=0,rz=0,sx=1,sy=sx,sz=sx){const o=this.local;o.position.set(x,y,z);o.rotation.set(rx,ry,rz);o.scale.set(sx,sy,sz);o.updateMatrix();return o.matrix;}
 placed(parent,x,y,z,rx,ry,rz,sx,sy,sz,out){return out.multiplyMatrices(parent,this.local4(x,y,z,rx,ry,rz,sx,sy,sz));}
 updateActors(glows){for(const a of this.sim.agents){const body=this.physics.bodies[a.id],dynamic=body.type===1,L=this.looks[a.id],R=this.actorRoot,i=a.id;if(dynamic){R.quaternion.set(body.quaternion.x,body.quaternion.y,body.quaternion.z,body.quaternion.w);R.position.set(0,-PERSON_ORIGIN,0).applyQuaternion(R.quaternion).add(body.position);R.scale.setScalar(1);}else{const drop=a.pose==='sit'?-.34:a.pose==='crouch'?-.16:0;R.position.set(a.x,a.y+drop,a.z);R.rotation.set(0,a.heading,0);R.scale.setScalar(1);}R.updateMatrix();const root=R.matrix,pose=dynamic?'tumble':a.pose,walk=dynamic||pose==='sit'?0:Math.sin(a.walk)*.55,swing=a.attackSwing>0?Math.sin(a.attackSwing/.4*Math.PI)*1.5:0,building=a.state==='build'&&a.role==='worker',work=building?Math.sin(this.sim.clock*5+a.id)*.7:0,damage=1-a.health,tunic=damage>.05?tmp2.set(L.tunic).multiplyScalar(1-damage*.28).getHexString():null,tunicHex=tunic?'#'+tunic:L.tunic;
 const lean=pose==='crouch'?.38:pose==='sit'?-.1:pose==='brace'?.12:0,torsoM=this.placed(root,0,.8,0,lean,0,0,1,1,1,this.m1);this.put('torso',i,torsoM,tunicHex);this.put('skirt',i,this.placed(root,0,.56,0,lean*.4,0,0,1,1,1,this.m2),tunicHex);const headY=1.2,headZ=lean*.32;this.put('head',i,this.placed(root,0,headY,headZ,0,0,0,1,1,1,this.m2),L.skin);
 const hd=L.head;this.put('cap',i,hd==='cone'?this.zero:this.placed(root,0,headY+.02,headZ,0,0,0,hd==='wrap'?1.1:1,hd==='wrap'?.85:1,hd==='wrap'?1.1:1,this.m2),hd==='hair'?L.headColor:L.headColor);this.put('cone',i,hd==='cone'?this.placed(root,0,headY+.2,headZ,0,0,0,1,1,1,this.m2):this.zero,L.headColor);this.put('tallcap',i,hd==='bork'?this.placed(root,0,headY+.28,headZ-.03,-.15,0,0,1,1,1,this.m2):this.zero,L.headColor);this.put('brim',i,hd==='morion'||hd==='hat'?this.placed(root,0,headY+.08,headZ,0,0,0,1,1,1,this.m2):this.zero,L.headColor);this.put('crest',i,L.crest||hd==='morion'?this.placed(root,0,headY+.23,headZ,0,L.crest?Math.PI/2:0,0,1,1,1,this.m2):this.zero,L.crest||L.headColor);
 // Arms: pose decides the swing of each shoulder.
 let left=-walk*.8,right=walk*.8,leftZ=.1,rightZ=-.1;if(a.carrying){left=right=-1.05;leftZ=.25;rightZ=-.25;}else if(building){right=-1.4+work;left=-1.1+work*.6;}else if(pose==='fight'){right=-1.2-swing;left=-.9;}else if(pose==='aim'){if(L.weapon==='bow'){left=-1.55;right=-1.45;rightZ=.5;}else{left=-1.35;right=-1.5;leftZ=.35;}}else if(pose==='brace'){left=-1.25;right=-.5;}else if(pose==='sit'){left=right=-.55;}else if(pose==='crouch'){left=right=-2.5;leftZ=.4;rightZ=-.4;}else if(pose==='tumble'){left=-2.6;right=-2.2;leftZ=.7;rightZ=-.7;}if(a.torch&&!a.carrying&&!building&&pose!=='aim')right=-1.1;
 const lArm=this.placed(root,-.25,1,headZ*.6,left,0,leftZ,1,1,1,this.m2);this.put('arms',i*2,lArm,tunicHex);const lHand=this.m3.copy(lArm);const rArm=this.placed(root,.25,1,headZ*.6,right,0,rightZ,1,1,1,this.m1);this.put('arms',i*2+1,rArm,tunicHex);
 const legSwing=pose==='sit'?-1.45:pose==='tumble'?.8:walk;this.put('legs',i*2,this.placed(root,-.11,.54,0,legSwing,0,pose==='sit'?.12:0,1,1,1,this.m2),L.legs);this.put('legs',i*2+1,this.placed(root,.11,.54,0,pose==='sit'?-1.45:pose==='tumble'?-.6:-walk,0,pose==='sit'?-.12:0,1,1,1,this.m2),L.legs);
 // Held things follow the hands.
 const hand=(arm,x,y,z,rx,ry,rz,s=1)=>this.placed(arm,x,y,z,rx,ry,rz,s,s,s,this.m2);const showShield=L.shield!=='none'&&pose!=='sit';this.put('shield',i,showShield&&L.shield==='rect'?hand(lHand,-.06,-.32,.12,-left-(pose==='brace'?.1:0),0,0):this.zero,L.shieldColor);this.put('roundShield',i,showShield&&L.shield!=='rect'?this.placed(lHand,-.06,-.32,.12,-left,0,0,L.shield==='oval'?.82:1,L.shield==='oval'?1.3:1,1,this.m2):this.zero,L.shieldColor);
 const armed=a.role!=='worker'&&pose!=='sit',levelled=pose==='brace'||pose==='fight';this.put('sword',i,armed&&L.weapon==='sword'?hand(rArm,0,-.42,.02,pose==='fight'?1.3:2.75,0,0):this.zero,'#9aa09a');this.put('spear',i,armed&&(L.weapon==='spear'||L.weapon==='pike')?this.placed(rArm,0,-.4,.02,-right+(levelled?1.35:.12),0,-rightZ,1,L.weapon==='pike'?2.1:1,1,this.m2):this.zero,'#7a6448');this.put('musket',i,armed&&L.weapon==='musket'?(pose==='aim'?this.placed(root,.12,1.22,.3+headZ,Math.PI/2,0,0,1,1,1,this.m2):hand(rArm,0,-.4,.05,-right+.15,0,-rightZ)):this.zero,'#4f4438');this.put('bow',i,armed&&L.weapon==='bow'?hand(lHand,0,-.42,.05,-left,0,-leftZ):this.zero,'#6b5236');
 this.put('basket',i,a.carrying?this.placed(root,0,.98,.34+headZ,0,0,0,1,1,1,this.m2):this.zero,'#a89069');this.put('tool',i,building?hand(rArm,0,-.4,.05,1.4,0,0):this.zero,palette.wood);const torch=a.torch&&!a.carrying&&!building&&!dynamic&&pose!=='aim'&&pose!=='sit';this.put('torch',i,torch?hand(rArm,0,-.42,.04,-right,0,-rightZ):this.zero,'#5a4630');if(torch&&glows.length<180){const m=this.m2.elements,flicker=.8+.2*Math.sin(this.time*17+i*3.1);glows.push({x:m[12]+m[4]*.5,y:m[13]+m[5]*.5,z:m[14]+m[6]*.5,size:2.4*flicker,opacity:.55*flicker,...glowColor('#ffb05a'),life:0,age:0});}}
 for(const mesh of Object.values(this.actorParts)){mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;}}
 buildDetails(){const s=this.sim.config;
 if(hasWater(s)&&(s.terrain?.sea||s.terrain==='tyre'||s.terrain?.type==='coastline'||s.terrain?.seaStep)){const count=s.id==='tyre'?7:s.id==='carthage'?5:4;for(let i=0;i<count;i++){const boat=new THREE.Group(),hull=this.part(new THREE.SphereGeometry(1,12,6,0,Math.PI*2,0,Math.PI/2),palette.darkWood,0,0,0,0,boat);hull.scale.set(.7,.55,2.3);hull.rotation.z=Math.PI;this.box(1.2,.1,4.2,palette.wood,0,.02,0,0,boat);this.box(.07,3.2,.07,palette.wood,0,1.6,0,0,boat);const sail=new THREE.Mesh(new THREE.PlaneGeometry(1.7,2.1,4,3),new THREE.MeshStandardMaterial({color:i%2?palette.canvas:'#d9c3a0',side:THREE.DoubleSide,roughness:.9}));sail.position.set(0,1.95,.1);sail.rotation.y=Math.PI/2;sail.castShadow=true;boat.add(sail);for(let k=0;k<4;k++)for(const side of [-1,1]){const oar=this.box(1.4,.04,.06,palette.wood,side*.95,-.1,-1.2+k*.8,0,boat);oar.rotation.z=side*.35;}boat.userData.phase=i*1.9;this.root.add(boat);this.boats.push(boat);}this.boatPath=this.findSea();}
 const ringGeo=new THREE.RingGeometry(.45,.52,48);ringGeo.rotateX(-Math.PI/2);this.ripple=new THREE.Mesh(ringGeo,new THREE.MeshBasicMaterial({color:'#fff8e0',transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide}));this.root.add(this.ripple);this.rippleAge=99;
 // Camp fires: a ring of stones, crossed logs and a flame that glows after dark.
 for(const f of this.sim.fires){const y=naturalHeight(s,f.x,f.z);for(let k=0;k<8;k++){const a=k/8*Math.PI*2;this.part(new THREE.DodecahedronGeometry(.16,0),palette.darkStone,f.x+Math.cos(a)*.48,y+.08,f.z+Math.sin(a)*.48,a);}for(const r of [.6,-.6]){const log=this.part(new THREE.CylinderGeometry(.07,.07,.8,6),palette.darkWood,f.x,y+.12,f.z,0,this.root);log.rotation.set(Math.PI/2,r,0);}const flame=new THREE.Mesh(new THREE.ConeGeometry(.24,.6,7),new THREE.MeshBasicMaterial({color:'#ffb040',transparent:true,opacity:.92}));flame.position.set(f.x,y+.38,f.z);this.root.add(flame);this.flames.push({mesh:flame,x:f.x,y:y+.4,z:f.z,phase:f.x});}
 const c=this.sim.fires[1];this.campLight=new THREE.PointLight('#ffa860',0,22,1.6);this.campLight.position.set(c.x,naturalHeight(s,c.x,c.z)+2.2,c.z);this.root.add(this.campLight);
 // Torches burn on the wall towers at night.
 for(const [x,z] of this.outline.filter((_,i)=>i%2===0)){const y=Math.max(...this.outline.map(([px,pz])=>Math.hypot(px-x,pz-z)<.1?wallProfile(s,[px,pz],[px,pz]).top:-Infinity));this.lamps.push({x,y:y+2.2,z});}}
 // Ships keep to water: an oval through the deepest part of the sea or bay.
 findSea(){const s=this.sim.config;if(s.terrain==='tyre')return null;let sx=0,sz=0,n=0,minX=99,maxX=-99,minZ=99,maxZ=-99;for(let x=-58;x<=58;x+=2)for(let z=-40;z<=40;z+=2)if(naturalHeight(s,x,z)<-2.2){sx+=x;sz+=z;n++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minZ=Math.min(minZ,z);maxZ=Math.max(maxZ,z);}return n?{x:sx/n,z:sz/n,rx:Math.max(3,(maxX-minX)*.3),rz:Math.max(3,(maxZ-minZ)*.3)}:null;}
 buildPlinth(){const s=this.sim.config;this.box(124.4,3.4,88.4,'#6e4a32',0,-5.8,0);this.box(125.4,.5,89.4,'#5a3b28',0,-7.6,0);this.box(124.8,.16,88.8,'#e9ddc0',0,-4.1,0);this.flush();
 if(typeof document!=='undefined'){const c=document.createElement('canvas');c.width=1024;c.height=160;const g=c.getContext('2d'),grad=g.createLinearGradient(0,0,0,160);grad.addColorStop(0,'#d9b56a');grad.addColorStop(.5,'#b98d43');grad.addColorStop(1,'#8f6a2e');g.fillStyle=grad;g.fillRect(0,0,1024,160);g.strokeStyle='#6f5022';g.lineWidth=6;g.strokeRect(10,10,1004,140);g.fillStyle='#3d2a12';g.textAlign='center';g.font='600 62px Georgia, serif';g.fillText(s.name.toUpperCase(),512,86);g.font='italic 34px Georgia, serif';g.fillText(s.date+' · '+s.faction+' siege',512,130);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const plate=new THREE.Mesh(new THREE.PlaneGeometry(22,3.4),new THREE.MeshStandardMaterial({map:t,metalness:.55,roughness:.38}));plate.position.set(0,-5.8,44.25);this.root.add(plate);
 const sc=document.createElement('canvas');sc.width=sc.height=128;const sg=sc.getContext('2d'),rg=sg.createRadialGradient(64,64,10,64,64,64);rg.addColorStop(0,'rgba(0,0,0,.55)');rg.addColorStop(1,'rgba(0,0,0,0)');sg.fillStyle=rg;sg.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(190,140),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(sc),transparent:true,depthWrite:false,opacity:.75}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-8.2;this.root.add(shadow);}}

 // ---------- Behaviour of the scene ----------
 pickActor(hit){if(hit?.instanceId===undefined)return null;const key=hit.object.userData.actorPart;return key==='arms'||key==='legs'?Math.floor(hit.instanceId/2):hit.instanceId;}
 burst(x,y,z,strength=3){this.particles.dust(x,y,z,strength);}
 shockwave(x,z){this.ripple.position.set(x,this.sim.heightAt(x,z)+.08,z);this.rippleAge=0;this.particles.dust(x,this.ripple.position.y,z,7);}
 missile(e){if(e.kind==='musket'){const dx=e.to.x-e.from.x,dz=e.to.z-e.from.z,l=Math.hypot(dx,dz)||1;this.particles.muzzle(e.from.x,e.from.y,e.from.z,dx/l,dz/l,.45);}}
 impact(p){const wet=p.y<WATER_LEVEL+.15&&!!this.water;if(wet)this.particles.splash(p.x,WATER_LEVEL,p.z,Math.min(2,.4+p.strength*.08));else{this.particles.dust(p.x,p.y,p.z,Math.min(8,p.strength*.35));if(p.strength>6)this.particles.sparks(p.x,p.y+.2,p.z,4);}}
 enginePosition(){const s=this.sim.config;if(this.engine.userData.static)return workPoint(s,1);return enginePoint(s,this.sim.engine);}
 shot(defender=false){const s=this.sim.config,type=this.engineKind,gun=type==='cannon'||type==='bombard';let from,to;if(defender){const b=this.sim.breach||outlineNearest(s,s.end[0],0),y=this.sim.surfaceHeight(b.x,b.z)+castleHeight(s)+1.5;from={x:b.x,y,z:b.z+(this.random()-.5)*4};const t=s.start[0]+(s.end[0]-s.start[0])*.45;to={x:t,y:this.sim.heightAt(t,0)+.4,z:(this.random()-.5)*6};}else{const p=this.engine.position;from={x:p.x+(gun?this.muzzle||1.5:1),y:p.y+(type==='trebuchet'?7:this.engineTop+.6),z:p.z};const b=this.sim.breach||{x:s.end[0]+4,z:0};to={x:b.x,y:this.sim.surfaceHeight(b.x,b.z)+castleHeight(s)*.6,z:b.z+(this.random()-.5)*8};}this.physics.projectile(from,to,gun?20:14,gun?.28:.2);if(gun&&!defender){this.particles.muzzle(from.x,from.y,from.z,1,0,1.4);this.recoil=1;}else this.particles.dust(from.x,from.y,from.z,1);if(type==='trebuchet'&&!defender)this.armSwing=1;this.throwArm.rotation.x=-1;}
 // Front wall chunks sink as the wall weakens; where the city fell by assault they eventually give way.
 collapseWalls(){const breakable=this.sim.breachable!==false,b=this.sim.breach||{x:this.sim.config.end[0],z:0};for(const wall of this.breakableWalls){const collapse=(1-this.sim.wallHealth)*Math.max(0,1-Math.hypot(wall.group.position.x-b.x,wall.z-b.z)/7);wall.group.scale.y=Math.max(.12,1-collapse*(breakable?1.25:.55));if(!wall.removed)this.physics.resizeBox(wall.body,wall.base,wall.height*wall.group.scale.y);if(breakable&&collapse>.55&&!wall.removed){this.physics.removeBox(wall.body);wall.removed=true;this.particles?.dust(wall.group.position.x,wall.group.position.y+1,wall.group.position.z,4);}}}
 setQuality(quality){this.options.quality=quality;this.renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?2:1.5));this.atmosphere.setQuality(quality);this.resize();}
 setCycle(on){this.options.cycle=on;this.atmosphere.cycle=on;this.sim.dayCycle=on;}
 update(dt,realDt=dt){this.time+=dt;const s=this.sim.config,glows=[];this.updateWorks();this.updateActors(glows);this.collapseWalls();
 const p=this.enginePosition(),floor=Math.max(...this.feet.map(f=>this.sim.surfaceHeight(p.x+f.z,p.z-f.x)),this.sim.surfaceHeight(p.x,p.z));this.engine.position.set(p.x,floor+.1,p.z);if(this.engine.userData.static)this.engine.scale.set(1,.35+.65*Math.min(1,this.sim.engine*1.2+.15),1);for(const w of this.wheels){w.position.y=this.sim.surfaceHeight(p.x+w.position.z,p.z-w.position.x)-this.engine.position.y+w.userData.r;w.rotation.x=this.sim.engine*65;w.userData.axle.position.y=w.position.y;const height=Math.max(.12,1.4-w.position.y);w.userData.support.scale.y=height;w.userData.support.position.y=w.position.y+height/2;}
 if(this.bridge)this.bridge.rotation.x+=((this.sim.engine>.96?1.45:0)-this.bridge.rotation.x)*Math.min(1,dt*1.5);if(this.ramBeam){const strike=this.sim.engine>.96?Math.max(0,Math.sin(this.time*2.2)):0;this.ramBeam.position.z=(this.engineKind==='ram'?1.4:1.6)+strike*.6;}if(this.barrel){this.recoil=Math.max(0,(this.recoil||0)-dt*2.5);this.barrel.position.z=(this.engineKind==='bombard'?0:.2)-this.recoil*.5;}if(this.arm){this.armSwing=Math.max(0,(this.armSwing||0)-dt*.5);const p=1-this.armSwing;this.arm.rotation.x=this.armSwing>0?-.75+2.5*smooth(0,.12,p)-2.5*smooth(.3,1,p):-.75;}this.throwArm.rotation.x+=(-.45-this.throwArm.rotation.x)*Math.min(1,dt*3);
 this.carts.forEach((c,i)=>{const cart=this.sim.carts[i];c.position.set(cart.x,this.sim.surfaceHeight(cart.x,cart.z)+.1,cart.z);c.rotation.y=cart.heading;c.userData.wheels.forEach(w=>w.rotation.x=cart.distance/.34);c.userData.legs.forEach((leg,k)=>leg.rotation.x=Math.sin(cart.distance*3.2+(k%2?Math.PI:0)+(k>1?Math.PI/2:0))*.45);});
 for(const banner of this.banners){const q=banner.geometry.attributes.position;for(let i=0;i<q.count;i++)q.setZ(i,Math.sin(q.getX(i)*2+this.time*3)*.09*(q.getX(i)+1.55)/3.1);q.needsUpdate=true;banner.geometry.computeVertexNormals();}
 if(this.waterTime)this.waterTime.value=this.time;
 this.boats.forEach((b,i)=>{const angle=this.time*.02+b.userData.phase;if(s.terrain==='tyre'){b.position.set(-5+Math.sin(angle)*8,WATER_LEVEL-.03,18+Math.cos(angle)*12*(i%2?-1:1));b.rotation.y=Math.atan2(Math.cos(angle)*8,-Math.sin(angle)*12*(i%2?-1:1));}else if(this.boatPath){const P=this.boatPath,a=angle+i*Math.PI*2/this.boats.length;b.position.set(P.x+Math.cos(a)*P.rx,WATER_LEVEL-.03,P.z+Math.sin(a)*P.rz);b.rotation.y=Math.atan2(-Math.sin(a)*P.rx,Math.cos(a)*P.rz);b.visible=naturalHeight(s,b.position.x,b.position.z)<-1.9;}b.rotation.z=Math.sin(this.time*1.3+i)*.035;if(dt>0&&Math.random()<.15)this.particles.emit('splash',b.position.x-Math.sin(b.rotation.y)*2,WATER_LEVEL+.05,b.position.z-Math.cos(b.rotation.y)*2,{count:1,speed:.2,up:.1,size:.5,life:1.2,gravity:0,grow:1.5,opacity:.4});});
 let stones=0;this.physics.objects.forEach(b=>{this.dummy.position.copy(b.position);this.dummy.quaternion.set(b.quaternion.x,b.quaternion.y,b.quaternion.z,b.quaternion.w);this.dummy.scale.setScalar(b.projectile?b.radius/.22:.8);this.dummy.updateMatrix();if(stones<100)this.projectileMesh.setMatrixAt(stones++,this.dummy.matrix);});this.projectileMesh.count=stones;this.projectileMesh.instanceMatrix.needsUpdate=true;
 let arrows=0,balls=0;const look=new THREE.Vector3();for(const m of this.physics.missiles){this.dummy.position.set(m.position.x,m.position.y,m.position.z);this.dummy.scale.setScalar(1);if(m.arrow){look.set(m.position.x+m.dir.x,m.position.y+m.dir.y,m.position.z+m.dir.z);this.dummy.lookAt(look);this.dummy.updateMatrix();if(arrows<64)this.arrowMesh.setMatrixAt(arrows++,this.dummy.matrix);}else{this.dummy.rotation.set(0,0,0);this.dummy.updateMatrix();if(balls<64)this.ballMesh.setMatrixAt(balls++,this.dummy.matrix);}}this.arrowMesh.count=arrows;this.ballMesh.count=balls;this.arrowMesh.instanceMatrix.needsUpdate=true;this.ballMesh.instanceMatrix.needsUpdate=true;
 // Fire, smoke and night glows.
 const night=this.atmosphere.night;for(const f of this.flames){const k=.85+.25*Math.sin(this.time*13+f.phase)+.1*Math.sin(this.time*29+f.phase*2);f.mesh.scale.set(k,k*(1+.2*Math.sin(this.time*9+f.phase)),k);if(dt>0&&Math.random()<.35)this.particles.fire(f.x,f.y,f.z,.8);if(dt>0&&Math.random()<.08)this.particles.smoke(f.x,f.y+.8,f.z,.45);glows.push({x:f.x,y:f.y+.2,z:f.z,size:(3+4*night)*k,opacity:.35+.5*night,...glowColor('#ff9d4a'),life:0,age:0});}this.campLight.intensity=night*14*(.9+.1*Math.sin(this.time*11));
 if(night>.05)for(const l of this.lamps){const k=.85+.15*Math.sin(this.time*12+l.x);glows.push({x:l.x,y:l.y,z:l.z,size:3.2*k,opacity:.75*night*k,...glowColor('#ffb35a'),life:0,age:0});}
 const weather=s.weather==='rain'?.25+.6*Math.min(1,this.sim.engine*1.1):0;if(weather>0&&dt>0)this.particles.rain(0,0,weather);this.particles.setScale((this.canvas.clientHeight||800)*this.renderer.getPixelRatio());this.particles.update(dt,glows);
 this.rippleAge+=dt;this.ripple.scale.setScalar(1+this.rippleAge*12);this.ripple.material.opacity=Math.max(0,.65-this.rippleAge*.7);this.selection.material.opacity=.7+.3*Math.sin(performance.now()/180);
 if(this.tween){const t=this.tween;t.age+=realDt;const k=smooth(0,1,t.age/t.duration);this.camera.position.lerpVectors(t.fromPos,t.toPos,k);this.controls.target.lerpVectors(t.fromTarget,t.toTarget,k);if(t.age>=t.duration)this.tween=null;}
 if(this.followId!==null){const b=this.physics.bodies[this.followId],a=this.sim.agents[this.followId],pos=a.disabled?b.position:{x:a.x,y:a.y+.72,z:a.z};const target=new THREE.Vector3(pos.x,pos.y,pos.z),delta=target.clone().sub(this.controls.target).multiplyScalar(.08);this.camera.position.add(delta);this.controls.target.add(delta);}
 this.controls.update();this.atmosphere.update(this.sim.clock,this.camera,this.camera.position.distanceTo(this.controls.target),weather);this.atmosphere.render(this.camera);}
 resize(){const w=this.canvas.clientWidth||1,h=this.canvas.clientHeight||1;this.renderer.setSize(w,h,false);this.camera.aspect=w/Math.max(1,h);this.camera.updateProjectionMatrix();this.atmosphere?.resize();}
 view(kind,animate=true){this.followId=null;const s=this.sim.config,c=campLayout(s);let target,pos;if(kind==='works'){const p=s.kind==='rings'?workPoint(s,this.sim.front/(this.sim.built.length-1)):workPoint(s,Math.min(1,this.sim.front/(this.sim.built.length-1)+.05));target=new THREE.Vector3(p.x,this.sim.heightAt(p.x,p.z)+2,p.z);pos=target.clone().add(new THREE.Vector3(-19,15,25));}else if(kind==='city'){const y=naturalHeight(s,s.fort[0],s.fort[1]);target=new THREE.Vector3(s.fort[0],y+1,s.fort[1]);pos=target.clone().add(new THREE.Vector3(-30,27,37));}else if(kind==='camp'){target=new THREE.Vector3(c.x+c.w/2,naturalHeight(s,c.x+c.w/2,c.z+c.d/2)+1,c.z+c.d/2);pos=target.clone().add(new THREE.Vector3(-13,15,21));}else{const y=Math.max(2,naturalHeight(s,s.fort[0],s.fort[1])*.35);target=new THREE.Vector3(2,y,0);pos=new THREE.Vector3(-91,84,103);}
 if(animate){this.tween={fromPos:this.camera.position.clone(),toPos:pos,fromTarget:this.controls.target.clone(),toTarget:target,age:0,duration:1.1};}else{this.camera.position.copy(pos);this.controls.target.copy(target);this.controls.update();}}
 dispose(){this.controls.dispose();this.atmosphere.dispose();this.particles.dispose();this.renderer.dispose();const gs=new Set(),ms=new Set();this.root.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);if(m.map)m.map.dispose();}if(o.isInstancedMesh)o.dispose();});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
}
