import {scenarioById} from './scenarios.js';
import {terrainHeight,cartRoute,cartPoint,insidePolygon} from './collision.js';
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mix=(a,b,t)=>a+(b-a)*t,smooth=t=>{t=clamp(t,0,1);return t*t*(3-2*t);},TAU=Math.PI*2,wrap=v=>((v%1)+1)%1,signed=v=>wrap(v+.5)-.5,angle=v=>Math.atan2(Math.sin(v),Math.cos(v)),hash=(a,b)=>{const x=Math.sin(a*127.1+b*311.7)*43758.5453;return x-Math.floor(x);};
// One miniature day lasts eight minutes at 1× and a new siege opens in mid-morning. Time of day runs 0→1 from sunrise; the sun sets at .62.
export const DAY_LENGTH=480;
export const dayTime=clock=>wrap(clock/DAY_LENGTH+.12);
export function nightAmount(clock){const t=dayTime(clock);return smooth((t-.585)/.09)*(1-smooth((t-.935)/.065));}

// Terrain is data: a landform (rise, hill, mesa, plain, coastline) plus optional sea, river, marsh, ditch, land masses, bumps and ridges.
export const WATER_LEVEL=-1.2;
const bump=(x,z,b)=>b[2]*Math.exp(-((x-b[0])**2+(z-b[1])**2)/(b[3]||150));
function ridge(x,z,[x0,z0,x1,z1,h,w]){const dx=x1-x0,dz=z1-z0,f=clamp(((x-x0)*dx+(z-z0)*dz)/(dx*dx+dz*dz||1),0,1);return h*(1-smooth(Math.hypot(x-x0-dx*f,z-z0-dz*f)/w));}
function landform(s,t,x,z){const [cx,cz]=t.center||s.fort,rx=t.r?.[0]||16,rz=t.r?.[1]||14;let h=0;
 if(t.type==='rise')h=t.h*smooth((x-(t.at??-1))/(t.width??14));
 else if(t.type==='hill'){const r=Math.hypot((x-cx)/rx,(z-cz)/rz);h=t.h*(1-smooth((r-(t.top??.7))/(t.edge??.55)));}
 else if(t.type==='mesa'){const r=Math.abs((x-cx)/rx)**(t.power??4)+Math.abs((z-cz)/rz)**(t.power??4);h=t.h*(1-smooth((r-.8)/(t.edge??.5)));}
 else h=t.h||0;
 if(t.spur){const [from,to,height,half=2]=t.spur,f=clamp((x-from)/(to-from),0,1);if(x>from&&x<to)h=Math.max(h,height*f*(1-smooth((Math.abs(z-cz)-half)/10)));}
 for(const b of t.bumps||[])h+=bump(x,z,b);for(const r of t.ridges||[])h+=ridge(x,z,r);
 if(t.ditch){const [dx,dz,drx,drz,depth,width]=t.ditch,d=Math.abs(Math.hypot((x-dx)/drx,(z-dz)/drz)-1)*Math.min(drx,drz);if(d<width)h-=depth*(1-smooth(d/width));}
 return h;}
function waterBed(t,x,z){let w=Infinity;const shore=(d,depth=-3,width=3)=>d<=0?Infinity:mix(0,depth,smooth(d/width));
 if(t.sea){const [side,at]=t.sea,d=side==='south'?z-at:side==='north'?-z-at:side==='east'?x-at:-x-at;w=Math.min(w,shore(d));}
 if(t.river){const [axis,at,width]=t.river;w=Math.min(w,shore(width/2-Math.abs((axis==='x'?x:z)-at),-2.6,2.2));}
 if(t.marsh){const [cx,cz,rx,rz,gap,depth=-1.75]=t.marsh,r=Math.hypot((x-cx)/rx,(z-cz)/rz);if(!(x<cx&&Math.abs(z-cz)<gap))w=Math.min(w,shore(Math.min(r-1,1.45-r)*Math.min(rx,rz),depth,2.5));}
 return w;}
export function naturalHeight(s,x,z){
 if(Math.abs(x)>62||Math.abs(z)>44)return -4;
 const noise=.16*Math.sin(x*.23+z*.11)+.12*Math.cos(z*.28-x*.13),t=s.terrain||{type:'rise',h:s.height};
 if(t==='masada'){const r=((x-18)/16)**4+(z/28)**4,mesa=24*(1-smooth((r-.8)/.5));const f=clamp((x+41)/43,0,1),spur=x<2&&x>-43?17*f*(1-smooth((Math.abs(z)-2)/10)):0;return Math.max(mesa,spur)+noise;}
 if(t==='alesia'){const r=Math.hypot(x/16,z/13);return 9*(1-smooth((r-.7)/.55))+noise+1.5*Math.exp(-((x+46)**2+(z-20)**2)/180);}
 if(t==='tyre'){const shore=-32+7*smooth((-2-z)/4),land=x<shore?.5+noise:mix(.5,-3,smooth((x-shore)/3)),r=Math.hypot((x-24)/17,z/23);return Math.max(land,r<.92?2+noise:r<1.05?mix(2,-3,(r-.92)/.13):-3);}
 if(t==='jerusalem')return 7*smooth((x+3)/14)+noise+1.3*Math.exp(-((x-34)**2+(z+14)**2)/150);
 if(t.seaStep&&z>t.seaStep)return -3;
 let h=landform(s,t,x,z)+noise*(t.rough??1);
 if(t.type==='coastline'){const [s0,s1]=t.shore,edge=s0+s1*smooth((-2-z)/4);if(x>edge)h=mix(h,-3,smooth((x-edge)/3));}
 for(const [lx,lz,rx,rz,lh] of t.land||[]){const r=Math.hypot((x-lx)/rx,(z-lz)/rz);if(r<1.05)h=Math.max(h,r<.92?lh+noise+(t.bumps||[]).reduce((v,b)=>v+bump(x,z,b),0):mix(lh,-3,(r-.92)/.13));}
 return Math.min(h,waterBed(t,x,z));
}
const waterCache=new WeakMap();
export function hasWater(s){if(!waterCache.has(s)){let wet=false;for(let x=-60;x<=60&&!wet;x+=2)for(let z=-42;z<=42;z+=2)if(naturalHeight(s,x,z)<WATER_LEVEL+.1){wet=true;break;}waterCache.set(s,wet);}return waterCache.get(s);}

// Siege lines are ellipses (or arcs of them) around a centre; a single ring is one continuous wall.
export function ringSpec(s){const r=s.rings||{},a0=r.arc?.[0]??0,a1=r.arc?.[1]??TAU;return{cx:r.center?.[0]??0,cz:r.center?.[1]??0,inner:r.inner||[30,22],outer:r.single?(r.inner||[30,22]):(r.outer||[47,33]),a0,a1,single:!!r.single,full:a1-a0>=TAU-1e-6};}
export const ringPoint=(s,ring,a,f=1)=>{const r=ringSpec(s),[rx,rz]=ring?r.outer:r.inner;return{x:r.cx+Math.cos(a)*rx*f,z:r.cz+Math.sin(a)*rz*f};};
export function workPoint(s,t){if(s.kind==='rings'){const r=ringSpec(s),ring=r.single||t<.5?0:1,u=r.single?t:(t% .5)*2;return{...ringPoint(s,ring,r.a0+(r.a1-r.a0)*u),ring};}const x=mix(s.start[0],s.end[0],t);const phase=t*5%1;return{x,z:s.kind==='trenches'?(phase<.5?phase*2:2-phase*2)*6-3:0};}

export function fortressOutline(s){const w=s.walls||{},[sx,sz]=w.scale||[1,1];let outline;if(w.shape==='poly')outline=w.points;else if(w.shape==='star'){const n=w.n||14,[r1,r2]=w.r||[24,17];outline=Array.from({length:n},(_,i)=>{const a=i/n*Math.PI*2,r=i%2?r2:r1;return[Math.cos(a)*r,Math.sin(a)*r];});}else if(w.shape==='round'){const n=w.n||18,[rx,rz]=w.r||[18,18];outline=Array.from({length:n},(_,i)=>{const a=-i/n*Math.PI*2+Math.PI;return[Math.cos(a)*rx,Math.sin(a)*rz];});}else outline=[[-16,-21],[14,-21],[17,-13],[17,17],[10,22],[-16,20]];const points=outline.map(([x,z])=>[x*sx+s.fort[0],z*sz+s.fort[1]]);
 // Every circuit winds the same way, so (dz,-dx) along an edge always points outward.
 return points.reduce((t,[x,z],i)=>{const [u,v]=points[(i+1)%points.length];return t+x*v-u*z;},0)<0?points.reverse():points;}
export const castleHeight=s=>s.walls?.height??2.7;
export function wallProfile(s,a,b,h=castleHeight(s)){let floor=Infinity,high=-Infinity;const n=Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])*2);for(let i=0;i<=n;i++){const y=naturalHeight(s,mix(a[0],b[0],i/(n||1)),mix(a[1],b[1],i/(n||1)));floor=Math.min(floor,y);high=Math.max(high,y);}return{floor,top:high+h};}
// The circuit, its wall tops and its towers are worked out once per siege; patrols ask for them every step.
const circuits=new WeakMap();
function circuit(s){let c=circuits.get(s);if(!c){const poly=fortressOutline(s),n=poly.length,breach=s.kind!=='rings'&&s.breach!==false?breachPoint(s).segment:undefined;c={poly,n,tops:poly.map((a,i)=>wallProfile(s,a,poly[(i+1)%n]).top),towers:poly.map((_,i)=>breach===undefined||(i!==breach&&i!==(breach+1)%n))};circuits.set(s,c);}return c;}
// Corner towers stand at every vertex except the two that flank a breach, so the gap stays open.
export const hasTower=(s,i)=>{const c=circuit(s);return c.towers[((i%c.n)+c.n)%c.n];};
// side=1 is outside the circuit, side=-1 inside.
export function patrolPoint(s,t,onWall=true,side=1){const {poly,n,tops,towers}=circuit(s),q=((t%1)+1)%1*n,i=Math.floor(q),f=q-i,a=poly[i],b=poly[(i+1)%n],p={x:mix(a[0],b[0],f),z:mix(a[1],b[1],f)};if(!onWall){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);p.x+=dz/len*1.8*side;p.z-=dx/len*1.8*side;return p;}p.y=tops[i]+.14;for(let j=0;j<n;j++){const v=poly[j];if(towers[j]&&Math.abs(p.x-v[0])<1.8&&Math.abs(p.z-v[1])<1.8)p.y=Math.max(p.y,Math.max(tops[j],tops[(j+n-1)%n])+1.51);}return p;}
// Closest point on the circuit, its patrol parameter, and the outward normal there.
export function outlineNearest(s,x,z){const {poly,n}=circuit(s),normal=i=>{const a=poly[i],b=poly[(i+1)%n],len=Math.hypot(b[0]-a[0],b[1]-a[1]);return[(b[1]-a[1])/len,-(b[0]-a[0])/len];};let best={d:Infinity};for(let i=0;i<n;i++){const a=poly[i],b=poly[(i+1)%n],dx=b[0]-a[0],dz=b[1]-a[1],f=clamp(((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz),0,1),px=a[0]+dx*f,pz=a[1]+dz*f,d=Math.hypot(x-px,z-pz);if(d<best.d-1e-9)best={d,i,f,t:(i+f)/n,x:px,z:pz};}let [nx,nz]=normal(best.i);if(best.f>.999||best.f<.001){const [mx,mz]=normal(best.f>.5?(best.i+1)%n:(best.i+n-1)%n),len=Math.hypot(nx+mx,nz+mz)||1;nx=(nx+mx)/len;nz=(nz+mz)/len;}return{...best,nx,nz};}
// The breach opens mid-way along the wall segment that faces the works, away from corner towers.
export function breachPoint(s){const poly=fortressOutline(s),n=poly.length;let best=null;for(let i=0;i<n;i++){const a=poly[i],b=poly[(i+1)%n],dx=b[0]-a[0],dz=b[1]-a[1],mx=(a[0]+b[0])/2,mz=(a[1]+b[1])/2,len=Math.hypot(dx,dz);if(Math.abs(mx-s.end[0])>=10||Math.abs(dx)>=Math.abs(dz)*.65)continue;const d=Math.hypot(mx-s.end[0],mz-s.end[1]);if(!best||d<best.d)best={d,x:mx,z:mz,nx:dz/len,nz:-dx/len,t:(i+.5)/n,segment:i};}return best||outlineNearest(s,s.end[0],s.end[1]);}
export const enginePoint=(s,engine)=>workPoint(s,engine*(s.kind==='battery'||s.kind==='trenches'?.52:1));
export const breachable=s=>s.kind!=='rings'&&s.breach!==false;
// The phases a siege moves through, ending in its own finale.
export function phases(s){return s.kind==='rings'?['Building','Holding the lines',s.finale]:['Building',s.kind==='battery'||s.kind==='trenches'?'Guns forward':'Advancing','Bombardment',s.finale];}
// Tents sit on a grid; fires, sentries and the drill ground go on the side facing the board.
export function campLayout(s){const [x,z]=s.camp,cols=s.campCols||6,rows=s.campRows||4,w=(cols-1)*3.6,d=(rows-1)*4.2,side=z<-36?1:-1,front=side<0?z-4.2:z+d+4.2;return{x,z,cols,rows,w,d,side,
 fires:[.15,.5,.85].map((f,i)=>({x:x+w*f,z:front+(i===1?side*.4:0)})),
 posts:[[x-3.2,z-2.4,-1],[x+w+3.6,z-2.4,1],[x-3.2,z+d+1,-1],[x+w+3.6,z+d+1,1],[s.start[0]-3,4.6,1],[s.start[0]-3,-4.6,1]].map(([px,pz,dir])=>[clamp(px,-59,59),clamp(pz,-41,41),dir]),
 drill:side<0?{x0:x+2,x1:Math.max(x+10,x+w-2),z0:z-11,z1:z-7}:{x0:x+2,x1:Math.max(x+10,x+w-2),z0:z+d+8,z1:z+d+12},
 supply:i=>({x:x+1.8+(i%cols)*3.6,z:z+1.9}),spawn:i=>({x:x+1.8+(i%cols)*3.6,z:z+1.9+Math.floor(i/cols)*.72})};}
export const campFires=s=>campLayout(s).fires;

export class SiegeSimulation{
 constructor(id='masada'){this.config=scenarioById(id);this.clock=0;this.seed=this.config.seed;this.completedLoads=0;this.engine=0;this.stage='Building';this.wallHealth=1;this.built=new Float64Array(this.config.kind==='rings'?160:48);this.capacity=new Float64Array(this.built.length);this.base=new Float64Array(this.built.length);this.reserved=new Float64Array(this.built.length);this.revision=0;this.agents=[];this.events=[];this.shotClock=0;this.shots=0;this.supplyPause=0;this.cartRoute=cartRoute(this.config);this.carts=Array.from({length:5},(_,id)=>({id,distance:id*this.cartRoute.total/5,...cartPoint(this.cartRoute,id*this.cartRoute.total/5)}));
 const s=this.config;this.dayCycle=true;this.loadSize=({battery:.85,trenches:.45,terraces:2.8}[s.kind]??2.2)/(s.effort||1);this.night=false;this.breached=false;this.breachable=breachable(s);this.wallFloor=this.breachable?0:.3;this.grid=new Map();this.camp=campLayout(s);this.fires=this.camp.fires;this.posts=this.camp.posts;this.outline=fortressOutline(s);this.rings=s.kind==='rings'?ringSpec(s):null;
 for(let i=0;i<this.built.length;i++){const t=i/(this.built.length-1),p=workPoint(s,t);this.base[i]=naturalHeight(s,p.x,p.z);const target=s.kind==='ramp'?mix(this.base[0]+.35,s.height+.15,t):s.kind==='causeway'?1.05:s.kind==='terraces'?mix(.45,s.height+.1,t):this.base[i]+(s.kind==='rings'?1.7:s.kind==='battery'?1.5:.8);this.capacity[i]=Math.max(.25,target-this.base[i])*5;}
 this.reliefFrom=s.reliefFrom||[-55,16];
 if(s.kind!=='rings'){const p=breachPoint(s);this.threat=p;this.breach={x:p.x,z:p.z,nx:p.nx,nz:p.nz,inner:{x:p.x-p.nx*3,z:p.z-p.nz*3}};}
 else{const r=this.rings,[ox,oz]=r.outer,toward=s.relief?Math.atan2((this.reliefFrom[1]-r.cz)/oz,(this.reliefFrom[0]-r.cx)/ox):s.sortieAngle??2.4,from=r.a0+wrap((toward-r.a0)/TAU)*TAU;this.lineAngle=r.full?toward:clamp(from,r.a0+.3,r.a1-.3);}
 for(let id=0;id<s.workers+s.soldiers+s.defenders+(s.relief||0);id++){const role=id<s.workers?'worker':id<s.workers+s.soldiers?'soldier':id<s.workers+s.soldiers+s.defenders?'defender':'relief',spawn=this.camp.spawn(id);const a={id,role,job:role==='worker'?'Loading supplies':'Patrolling',x:spawn.x,z:spawn.z,y:0,heading:0,walk:0,state:'load',timer:this.random()*3,carrying:false,loads:0,disabled:false,panic:0,health:1,recovery:0,target:0,wallPatrol:role==='defender',combatTarget:-1,combatCooldown:0,attackSwing:0,fightTime:0,fatigue:hash(id,3)*.3,pose:'stand',torch:false,patrolT:0,shootCooldown:2+hash(id,7)*8,aim:0,fights:0,tumbles:0,arrowHits:0,stuck:0,avoid:-1};if(role==='defender'){a.patrolT=(id-s.workers-s.soldiers)/s.defenders;const p=patrolPoint(s,a.patrolT);a.x=p.x;a.z=p.z;}if(role==='relief'){const p=this.reliefWait(id-s.workers-s.soldiers-s.defenders);a.x=p.x;a.z=p.z;a.heading=Math.PI/2;}a.y=role==='defender'?patrolPoint(s,a.patrolT).y:this.surfaceHeight(a.x,a.z);this.agents.push(a);}
 }
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 get progress(){return this.built.reduce((a,b)=>a+b,0)/this.capacity.reduce((a,b)=>a+b,0);}
 get front(){let i=this.built.findIndex((h,i)=>h<this.capacity[i]-.001);return i<0?this.built.length-1:i;}
 heightAt(x,z){const s=this.config,N=this.built.length;let h=naturalHeight(s,x,z);if(s.kind==='rings'){const r=this.rings||ringSpec(s);for(let ring=0;ring<(r.single?1:2);ring++){const [rx,rz]=ring?r.outer:r.inner,a=Math.atan2((z-r.cz)/rz,(x-r.cx)/rx),u=Math.min(1,wrap((a-r.a0)/TAU)*TAU/(r.a1-r.a0)),t=r.single?u:Math.min(u,.9999)*.5+ring*.5,i=clamp(Math.round(t*(N-1)),0,N-1),p=workPoint(s,i/(N-1)),distance=Math.hypot(x-p.x,z-p.z);if(distance<1.35)h=Math.max(h,this.base[i]+this.built[i]/5*(1-smooth((distance-.45)/.9)));}return h;}const t=(x-s.start[0])/(s.end[0]-s.start[0]);if(t>=0&&t<=1){const p=workPoint(s,t),side=Math.abs(z-p.z),i=clamp(Math.round(t*(N-1)),0,N-1);if(s.kind==='trenches'&&side<1.5)h=this.base[i]-.85*Math.min(1,this.built[i]/this.capacity[i]);else if(side<4.1&&s.kind!=='trenches')h=Math.max(h,this.base[i]+this.built[i]/5*(1-smooth((side-2.6)/1.5)));}return h;}
 surfaceHeight(x,z){return terrainHeight((px,pz)=>this.heightAt(px,pz),x,z);}
 face(a,heading,dt){a.heading=angle(a.heading+angle(heading-a.heading)*Math.min(1,dt*8));}
 // Neighbours push each other apart so crowds walk in lanes instead of through one another.
 separation(a){let x=0,z=0;const ix=Math.floor(a.x),iz=Math.floor(a.z);for(let i=-1;i<=1;i++)for(let j=-1;j<=1;j++){const list=this.grid.get((ix+i)*4096+iz+j);if(list)for(const b of list){if(b===a||Math.abs(a.y-b.y)>1)continue;const dx=a.x-b.x,dz=a.z-b.z,d=Math.hypot(dx,dz);if(d>=.62)continue;if(d<1e-4){x+=hash(a.id,b.id)-.5;z+=hash(b.id,a.id)-.5;continue;}const f=(.62-d)/(.62*d);x+=dx*f;z+=dz*f;}}return{x,z};}
 move(a,x,z,dt,speed=2.1){const open=this.reach?.(a,x,z);if(open){x=open.x;z=open.z;}const goal={x,z},target=this.navigate?.(a,goal)||goal,dx=target.x-a.x,dz=target.z-a.z,d=Math.hypot(dx,dz),step=Math.min(d,dt*speed);let next={x:a.x+dx/(d||1)*step,z:a.z+dz/(d||1)*step};if(d>.02)this.face(a,Math.atan2(dx,dz),dt);if(target===goal&&this.grid.size){const push=this.separation(a),scale=Math.min(1,Math.hypot(x-a.x,z-a.z)/1.2)*dt*3;if(push.x||push.z){const nudged={x:next.x+clamp(push.x,-1.5,1.5)*scale,z:next.z+clamp(push.z,-1.5,1.5)*scale};if(!this.blocked?.(a,nudged))next=nudged;}}if(!this.blocked?.(a,next)){a.walk+=Math.hypot(next.x-a.x,next.z-a.z)*3.4;a.x=next.x;a.z=next.z;}a.y=this.surfaceHeight(a.x,a.z);return Math.hypot(x-a.x,z-a.z)<.4;}
 // Arrive and hold: standing figures stop jostling and turn to face their post.
 hold(a,x,z,dt,speed,heading=null){const open=this.reach?.(a,x,z);if(open){x=open.x;z=open.z;}if(Math.hypot(x-a.x,z-a.z)<.3){a.y=this.surfaceHeight(a.x,a.z);if(heading!==null)this.face(a,heading,dt);return true;}return this.move(a,x,z,dt,speed);}
 deposit(index,amount=this.loadSize){if(!Number.isInteger(index)||index<0||index>=this.built.length)return 0;const used=Math.min(amount,this.capacity[index]-this.built[index]);this.built[index]+=used;this.revision++;return used;}
 react(x,z,r=9,duration=3){for(const a of this.agents)if(!a.disabled&&Math.hypot(a.x-x,a.z-z)<r)a.panic=Math.max(a.panic,duration+this.random()*duration*.65);}
 engage(a,b){if(!a||!b||a.role==='worker'||b.role==='worker')return false;const side=p=>p.role==='soldier'?'attacker':'defender';if(side(a)===side(b)||a.health<=.23||b.health<=.23)return false;if(a.combatTarget!==b.id){a.fights++;b.fights++;}a.combatTarget=b.id;b.combatTarget=a.id;a.fightTime=b.fightTime=12;a.panic=b.panic=0;return true;}
 combat(a,dt){const b=this.agents[a.combatTarget];a.attackSwing=Math.max(0,a.attackSwing-dt);a.combatCooldown=Math.max(0,a.combatCooldown-dt);a.fightTime-=dt;if(!b||b.health<=.23||a.health<=.23||a.fightTime<=0){a.combatTarget=-1;a.recovery=2.5;a.job='Regrouping';return false;}const target=this.agentPosition?.(b)||b,distance=Math.hypot(a.x-target.x,a.z-target.z);if(distance>12||Math.abs(a.y-target.y)>3){a.combatTarget=-1;return false;}a.heading=Math.atan2(target.x-a.x,target.z-a.z);a.job='Fighting';if(distance>1.5){const height=a.y;this.move(a,target.x,target.z,dt,2.2);if(a.wallPatrol)a.y=height;return true;}if(a.combatCooldown<=0){a.attackSwing=.4;a.combatCooldown=.8+(a.id%4)*.08;b.health=clamp(b.health-.065,.2,1);a.fightTime=12;this.events.push({type:'hit',x:target.x,y:target.y+.8,z:target.z,amount:.065});if(b.health<=.23){b.combatTarget=-1;b.recovery=4;b.job='Regrouping';}}return true;}
 canFight(a){return!a.disabled&&!a.wallPatrol&&a.role!=='worker'&&a.combatTarget<0&&a.recovery<=0&&a.panic<=0&&a.health>.4;}
 // Opponents who meet on the ground close to melee range without needing a physical collision.
 engageNearby(){for(const a of this.agents){if(a.role!=='soldier'||!this.canFight(a))continue;let best=null,distance=1.35;const ix=Math.floor(a.x),iz=Math.floor(a.z);for(let i=-1;i<=1;i++)for(let j=-1;j<=1;j++)for(const b of this.grid.get((ix+i)*4096+iz+j)||[]){if(b.role==='soldier'||!this.canFight(b)||Math.abs(a.y-b.y)>1.5)continue;const d=Math.hypot(a.x-b.x,a.z-b.z);if(d<distance){distance=d;best=b;}}if(best)this.engage(a,best);}}
 indexAgents(){this.grid.clear();this.reserved.fill(0);for(const a of this.agents){if(a.disabled)continue;if(a.role==='worker'&&(a.state==='out'||a.state==='build'))this.reserved[a.target]++;if(a.wallPatrol)continue;const key=Math.floor(a.x)*4096+Math.floor(a.z),list=this.grid.get(key);if(list)list.push(a);else this.grid.set(key,[a]);}}
 // Workers pick the open cell with the most unclaimed work near the front, so trips are not wasted on finished ground.
 assign(a){const s=this.config,N=this.built.length,open=i=>this.capacity[i]-this.built[i]-this.reserved[i]*this.loadSize;let best=-1,score=-Infinity;if(s.kind==='rings'){for(let i=0;i<N;i++){const need=open(i);if(need<=.01||i===a.avoid)continue;const p=workPoint(s,i/(N-1)),v=Math.min(need,6)*.5-Math.hypot(p.x-a.x,p.z-a.z)*.06+hash(a.id,i)*.6;if(v>score){score=v;best=i;}}}else{const f=this.front;for(let i=f;i<Math.min(N,f+14);i++){const need=open(i);if(need<=.01||i===a.avoid)continue;const v=Math.min(need,6)-(i-f)*.9+hash(a.id,i)*.5;if(v>score){score=v;best=i;}}}// When every nearby cell is spoken for, join the least oversubscribed one still open.
 if(best<0){let most=-Infinity;for(let i=this.front;i<N;i++){if(this.capacity[i]-this.built[i]<=.001)continue;const v=open(i)-(i-this.front)*.05;if(v>most){most=v;best=i;}}}return best<0?this.front:best;}
 workSpot(a,i){const s=this.config,p=workPoint(s,i/(this.built.length-1));if(s.kind==='rings'){const r=this.rings,dx=p.x-r.cx,dz=p.z-r.cz,d=Math.hypot(dx,dz)||1,o=((a.id%3)-1)*.45;p.x+=dx/d*o;p.z+=dz/d*o;}else p.z+=((a.id%5)-2)*(s.kind==='trenches'?.42:.7);return p;}
 restSpot(a){const fire=this.fires[a.id%this.fires.length],w=a.id*2.39996,r=1.25+(Math.floor(a.id/3)%3)*.45;return{x:fire.x+Math.cos(w)*r,z:fire.z+Math.sin(w)*r,fx:fire.x,fz:fire.z};}
 rest(a,dt,job){const spot=this.restSpot(a);if(this.hold(a,spot.x,spot.z,dt,2,Math.atan2(spot.fx-spot.x,spot.fz-spot.z))&&Math.hypot(spot.x-a.x,spot.z-a.z)<.45)a.pose='sit';a.job=job;}
 worker(a,dt){const s=this.config,offShift=this.night&&a.id%2===0;
 if(a.state==='rest'){a.fatigue=Math.max(0,a.fatigue-dt*(this.night?.02:.045));this.rest(a,dt,this.night?'Sleeping by the fire':'Resting by the fire');if(!offShift&&a.fatigue<.15){a.state='load';a.timer=1+this.random()*1.5;}return;}
 a.torch=this.night;const supply=this.camp.supply(a.id),lane=((a.id%5)-2)*.75;
 if(a.state==='load'){if(offShift||a.fatigue>=1){a.state='rest';a.carrying=false;return;}a.job='Loading supplies';a.timer-=dt;if(a.timer<=0){a.target=this.assign(a);a.carrying=true;a.state='out';}}
 else if(a.state==='out'){a.job=s.kind==='trenches'?'Bringing tools':this.night?'Hauling by torchlight':'Hauling material';if(this.capacity[a.target]-this.built[a.target]<=.001){const next=this.assign(a);if(this.capacity[next]-this.built[next]>.001)a.target=next;}const p=this.workSpot(a,a.target),waypoint=a.x<s.start[0]-1&&s.kind!=='rings'?{x:s.start[0]-1,z:lane}:p,walked=a.walk,arrived=this.move(a,waypoint.x,waypoint.z,dt,2.25);a.stuck=a.walk-walked<dt*.3?a.stuck+dt:0;
 // A blocked figure builds from close by, or gives the cell up and takes another.
 if(waypoint===p&&(arrived||a.stuck>2.5&&Math.hypot(p.x-a.x,p.z-a.z)<3.5)){a.state='build';a.timer=1.8;a.stuck=0;}else if(a.stuck>2.5){a.avoid=a.target;a.target=this.assign(a);a.stuck=0;}}
 else if(a.state==='build'){a.job=s.kind==='trenches'?'Digging approach':s.kind==='rings'?'Setting stakes':'Laying material';a.y=this.surfaceHeight(a.x,a.z);a.timer-=dt;if(a.timer<=0){const used=this.deposit(a.target);if(used>0){this.completedLoads++;a.loads++;a.fatigue=Math.min(1,a.fatigue+.09);this.events.push({type:'deposit',x:a.x,z:a.z,y:a.y,amount:used});}else{// Someone filled this spot first: carry the load on to the next open one.
 const next=this.assign(a);if(next!==a.target&&this.capacity[next]-this.built[next]>.001){a.target=next;a.state='out';return;}}a.carrying=false;a.state='back';}}
 else{a.job='Returning to camp';const waypoint=a.x>s.start[0]+1&&s.kind!=='rings'?{x:s.start[0],z:lane*1.5+(lane>=0?.4:-.4)}:supply;if(this.move(a,waypoint.x,waypoint.z,dt,2.8)&&waypoint===supply){a.state=offShift||a.fatigue>=1?'rest':'load';a.timer=1+this.random()*2;}}
 }
 drillPoint(d,side){const {x0,x1,z0,z1}=this.camp.drill,w=x1-x0,h=z1-z0,P=2*(w+h);d=((d%P)+P)%P;let p,n;if(d<w){p=[x0+d,z0];n=[0,-1];}else if(d<w+h){p=[x1,z0+d-w];n=[1,0];}else if(d<2*w+h){p=[x1-(d-w-h),z1];n=[0,1];}else{p=[x0,z1-(d-2*w-h)];n=[-1,0];}return{x:p[0]+n[0]*side,z:p[1]+n[1]*side};}
 // A relief army waits in a block, then attacks the besiegers' line.
 reliefWait(k){const [x,z]=this.reliefFrom;return{x:x+(k%5)*1.05,z:z+Math.floor(k/5)*1.3*(z>0?1:-1)};}
 reliefSlot(k){if(this.config.kind==='rings')return this.lineSlot('outer',k);const [lx,lz]=this.config.reliefLine,[fx,fz]=this.reliefFrom,len=Math.hypot(fx-lx,fz-lz)||1,dx=(fx-lx)/len,dz=(fz-lz)/len,col=(k%8)-3.5,row=Math.floor(k/8);return{x:lx-dz*col-dx*row*.9,z:lz+dx*col-dz*row*.9,heading:Math.atan2(dx,dz)};}
 // Attackers: a shield screen at the works, a drilling reserve, and sentries; later an assault column and the storming of a breach.
 soldier(a,dt){const s=this.config,n=s.soldiers,i=a.id-s.workers;if(s.kind==='rings')return this.lines(a,i,dt);const sentries=6,escort=Math.min(8,n-sentries-4),N=this.built.length;
 if(i>=n-sentries){const [x,z,dir]=this.posts[(i-n+sentries)%this.posts.length],sway=Math.sin(this.clock*.22+i*1.3)*1.6;this.move(a,x,z+sway*dir,dt,1);a.torch=this.night;a.job='Standing watch';return;}
 if(this.breached){const b=this.breach,tx=-b.nz,tz=b.nx,row=Math.floor(i/5),col=(i%5)-2;this.move(a,b.inner.x+tx*col*.85-b.nx*row*.9,b.inner.z+tz*col*.85-b.nz*row*.9,dt,2.4);a.job='Storming the breach';return;}
 if(s.relief&&this.engine>.7&&i>=escort){const p=this.reliefSlot(i-escort);if(this.hold(a,p.x,p.z,dt,2.4,p.heading))a.pose='brace';a.torch=this.night&&i%4===0;a.job='Facing the relief army';return;}
 if(this.engine>0){const p=enginePoint(s,this.engine),tower=s.kind!=='battery'&&s.kind!=='trenches',row=Math.floor(i/4),col=(i%4)-1.5,x=p.x-(tower?3.4:3)-row,z=p.z+(tower?-col*.9:6.5+col*.9);if(this.hold(a,x,z,dt,2.2,Math.PI/2))a.pose='brace';a.torch=this.night&&i%4===0;a.job=tower?'Advancing behind the tower':this.breachable?'Waiting for a breach':'Guarding the batteries';return;}
 if(i<escort){const p=workPoint(s,Math.min(N-1,this.front+4)/(N-1));if(this.hold(a,p.x+1.6,p.z+(i-(escort-1)/2)*.95,dt,2.2,Math.PI/2))a.pose='brace';a.torch=this.night&&i%3===0;a.job='Shielding the work crews';return;}
 if(this.night){this.rest(a,dt,'Resting by the fire');return;}
 const k=i-escort,p=this.drillPoint(this.clock*1.25-Math.floor(k/2)*1.05,(k%2-.5)*.9);this.move(a,p.x,p.z,dt,2.1);a.job='Drilling in camp';}
 // Positions along the siege lines facing the relief (outer) or the town (inner).
 lineSlot(side,k){const r=this.rings,outer=side==='outer'&&!r.single,[rx,rz]=outer?r.outer:r.inner,rank=Math.floor(k/7),w=this.lineAngle+((k%7)-3)*1.15/rx,f=outer?.955-rank*.035:1.07+rank*.04,dir=outer?1:-1;return{x:r.cx+Math.cos(w)*rx*f,z:r.cz+Math.sin(w)*rz*f,heading:Math.atan2(Math.cos(w)*dir,Math.sin(w)*dir)};}
 arcAngle(u){const r=this.rings;return r.full?r.a0+wrap(u)*TAU:r.a0+(r.a1-r.a0)*(.5-.5*Math.cos(u*TAU));}
 lines(a,i,dt){const s=this.config,r=this.rings;if(this.engine>.7&&i<28){const side=s.relief&&i%2===0?'outer':'inner',p=this.lineSlot(side,s.relief?i>>1:i);if(this.hold(a,p.x,p.z,dt,2.4,p.heading))a.pose='brace';a.torch=this.night&&i%4<2;a.job=side==='outer'?'Holding the outer line':'Holding the inner line';return;}
 const [ix,iz]=r.inner,[ox,oz]=r.outer,mx=r.single?ix*1.13:(ix+ox)/2,mz=r.single?iz*1.13:(iz+oz)/2;
 if(i<16){const squad=i>>2,w=this.arcAngle(this.clock*.0045+squad/4-(i%4)*.0048);this.move(a,r.cx+Math.cos(w)*mx,r.cz+Math.sin(w)*mz,dt,1.9);a.torch=this.night&&i%4===0;a.job=r.single?'Patrolling the siege wall':'Patrolling between the lines';return;}
 const k=i-16,w=r.a0+(r.a1-r.a0)*(r.full?k/Math.max(1,s.soldiers-16):(k+.5)/Math.max(1,s.soldiers-16))+(r.full?.2:0),inner=r.single||k%2===0,f=(inner?1.08:.94)+Math.sin(this.clock*.2+k)*.01;this.move(a,r.cx+Math.cos(w)*(inner?ix:ox)*f,r.cz+Math.sin(w)*(inner?iz:oz)*f,dt,1.2);a.torch=this.night;a.job='Guarding the works';}
 relief(a,dt){const s=this.config,k=a.id-s.workers-s.soldiers-s.defenders;if(this.engine>.7){const p=this.reliefSlot(k);this.move(a,p.x,p.z,dt,1.9);a.torch=this.night&&k%5===0;a.job=s.kind==='rings'?'Attacking the outer line':'Attacking the siege lines';}else{const p=this.reliefWait(k);this.hold(a,p.x,p.z,dt,1.4,Math.PI/2);a.job='Waiting beyond the lines';}}
 // Wall stations concentrate on the threatened sector as the works approach it.
 stations(k){if(this.stationKey===k)return this.stationPlan;const m=this.config.defenders,tf=this.threat.t,w=.06,offset=j=>signed(j/m-tf),order=[...Array(m).keys()].sort((p,q)=>Math.abs(offset(p))-Math.abs(offset(q))||p-q),near=order.slice(0,k).sort((p,q)=>offset(p)-offset(q)),far=order.slice(k).sort((p,q)=>wrap(p/m-tf-w)-wrap(q/m-tf-w)),plan=new Float64Array(m),guard=new Uint8Array(m);near.forEach((j,r)=>{plan[j]=tf+w*(k>1?2*r/(k-1)-1:0);});far.forEach((j,r)=>{plan[j]=tf+w+(1-2*w)*(r+.5)/far.length;});order.slice(0,Math.min(10,k)).forEach(j=>guard[j]=1);this.stationKey=k;this.stationPlan={plan,guard};return this.stationPlan;}
 walkWall(a,station,dt){const n=this.outline.length,i=Math.floor(wrap(a.patrolT)*n),p=this.outline[i],q=this.outline[(i+1)%n],delta=signed(station-a.patrolT),step=Math.min(Math.abs(delta),dt*1.1/(n*Math.hypot(q[0]-p[0],q[1]-p[1])));a.patrolT=wrap(a.patrolT+Math.sign(delta)*step);const point=patrolPoint(this.config,a.patrolT);a.walk+=Math.hypot(point.x-a.x,point.z-a.z)*3.4;if(Math.abs(delta)>.002)this.face(a,Math.atan2(point.x-a.x,point.z-a.z),.1);else if(a.aim<=0){const o=outlineNearest(this.config,point.x,point.z);this.face(a,Math.atan2(o.nx,o.nz),dt);}a.x=point.x;a.z=point.z;a.y=point.y;return Math.abs(delta)<=.002;}
 shoot(a,dt){a.shootCooldown-=dt*(this.night?.6:1);if(a.shootCooldown>0)return;let best=null,distance=22;for(const b of this.agents){if(b.disabled||(b.role!=='worker'&&b.role!=='soldier'))continue;const d=Math.hypot(b.x-a.x,b.z-a.z);if(d>3&&d<distance){distance=d;best=b;}}if(!best){a.shootCooldown=1.5;return;}a.aim=.7;a.shootCooldown=6+this.random()*5;a.heading=Math.atan2(best.x-a.x,best.z-a.z);const spread=1+distance*.06;this.events.push({type:'missile',kind:this.config.dress?.missile||'arrow',id:a.id,from:{x:a.x+Math.sin(a.heading)*.3,y:a.y+1.3,z:a.z+Math.cos(a.heading)*.3},to:{x:best.x+(this.random()-.5)*spread,y:best.y+.7,z:best.z+(this.random()-.5)*spread}});}
 defender(a,dt){const s=this.config,m=s.defenders,j=a.id-s.workers-s.soldiers,rings=s.kind==='rings',inside=insidePolygon(this.outline,a.x,a.z),missile=s.dress?.missile;
 if(a.wallPatrol){if(rings&&this.engine>.85&&j%2===0){const p=patrolPoint(s,a.patrolT,false,1);a.wallPatrol=false;a.x=p.x;a.z=p.z;a.y=this.surfaceHeight(p.x,p.z);return;}
 let station;if(rings)station=j/m+this.clock*.0025;else{const k=Math.round(m*(.35+.45*this.progress)),{plan,guard}=this.stations(k);if(this.breached&&guard[j]){const p=patrolPoint(s,a.patrolT,false,-1);a.wallPatrol=false;a.x=p.x;a.z=p.z;a.y=this.surfaceHeight(p.x,p.z);return;}station=plan[j]+Math.sin(this.clock*.2+j*1.7)*.004;}
 this.walkWall(a,station,dt);a.torch=this.night&&j%3===0;if(a.aim>0)a.pose='aim';if(j%2===(rings?1:0)&&a.panic<=0)this.shoot(a,dt);a.panic=Math.max(0,a.panic-dt);a.job=a.aim>0?(missile==='musket'?'Firing from the wall':missile==='sling'?'Slinging from the wall':'Shooting from the wall'):rings?'Watching the siege lines':Math.abs(signed(a.patrolT-this.threat.t))<.08?'Manning the threatened wall':'Watching the approach';return;}
 if(rings&&this.engine>.85&&!inside){const p=this.lineSlot('inner',j>>1);this.move(a,p.x,p.z,dt,1.9);a.job='Breaking out toward the lines';return;}
 if(this.breached&&inside){const b=this.breach,guard=this.stationPlan?.guard||new Uint8Array(m),g=guard.slice(0,j).reduce((t,v)=>t+v,0)%10,row=Math.floor(g/5),col=(g%5)-2;if(this.hold(a,b.inner.x-b.nz*col*.85-b.nx*row*.9,b.inner.z+b.nx*col*.85-b.nz*row*.9,dt,2.2,Math.atan2(b.nx,b.nz)))a.pose='brace';a.job='Holding the breach';return;}
 if(inside){const o=outlineNearest(s,a.x,a.z),x=o.x-o.nx*1.3,z=o.z-o.nz*1.3;a.job='Returning to the wall';this.move(a,x,z,dt,1.6);if(Math.hypot(x-a.x,z-a.z)<1.2){a.wallPatrol=true;a.patrolT=o.t;}return;}
 const p=patrolPoint(s,j/m+this.clock*.0025,false);this.move(a,p.x,p.z,dt,1.1);a.job='Patrolling outside the walls';}
 update(dt){if(!Number.isFinite(dt)||dt<=0)return;dt=Math.min(.1,dt);this.clock+=dt;this.events=[];const s=this.config;this.night=this.dayCycle&&nightAmount(this.clock)>.5;this.breached=this.breachable&&this.wallHealth<.22;this.indexAgents();
 for(const a of this.agents){if(a.disabled)continue;a.pose='stand';a.torch=false;a.aim=Math.max(0,a.aim-dt);if(a.combatTarget>=0&&this.combat(a,dt)){a.pose='fight';continue;}if(a.recovery>0){a.recovery-=dt;a.health=Math.min(1,a.health+dt*.06);a.job='Recovering';continue;}if(a.panic>0&&!a.wallPatrol){a.panic-=dt;a.job='Taking cover';a.pose='crouch';const awayX=a.x+(a.x-s.end[0])* .1,awayZ=a.z+(a.z>=0?2:-2);this.move(a,clamp(awayX,-56,56),clamp(awayZ,-37,37),dt,3);continue;}
 a.health=Math.min(1,a.health+dt*(a.role==='worker'?.01:.02));if(a.role==='worker')this.worker(a,dt);else if(a.role==='soldier')this.soldier(a,dt);else if(a.role==='relief')this.relief(a,dt);else this.defender(a,dt);}
 this.engageNearby();
 for(const cart of this.carts){cart.distance=(cart.distance+dt*1.65)%this.cartRoute.total;Object.assign(cart,cartPoint(this.cartRoute,cart.distance));}
 const finale=s.finale||(s.kind==='rings'?'Relief force approaching':'Breach opened');
 if(this.progress>.985){this.stage=s.kind==='rings'?'Holding the lines':phases(s)[1];if(s.kind==='ramp'||s.kind==='terraces'||s.kind==='causeway')this.engine=Math.min(1,this.engine+dt*.012);else this.engine=Math.min(1,this.engine+dt*.04);}
 if(this.engine>.96){this.stage=s.kind==='rings'?finale:!this.breachable&&this.shots>=8?finale:'Bombardment';this.shotClock+=dt;if(this.shotClock>(s.kind==='battery'||s.kind==='trenches'?3.2:5.5)){this.shotClock=0;this.shots++;this.events.push({type:s.kind==='rings'?'relief':'shot'});}}
 if(this.breached)this.stage=finale;
 if(this.lastStage!==undefined&&this.lastStage!==this.stage)this.events.push({type:'stage',stage:this.stage});this.lastStage=this.stage;
 }
 finishWorks(){for(let i=0;i<this.built.length;i++)this.built[i]=this.capacity[i];this.revision++;}
 exportState(){return{version:1,scenario:this.config.id,clock:this.clock,seed:this.seed,built:[...this.built],completedLoads:this.completedLoads,engine:this.engine,wallHealth:this.wallHealth,shotClock:this.shotClock,shots:this.shots,agents:this.agents.map(a=>({...a,disabled:false}))};}
 restoreState(save){if(save?.version!==1||save.scenario!==this.config.id||save.built?.length!==this.built.length||save.agents?.length!==this.agents.length||!save.built.every((v,i)=>Number.isFinite(v)&&v>=0&&v<=this.capacity[i]+.001))return false;for(const a of save.agents)if(!['x','y','z','health','timer','loads'].every(k=>Number.isFinite(a[k]))||Object.values(a).some(v=>typeof v==='number'&&!Number.isFinite(v))||Math.abs(a.x)>100||Math.abs(a.z)>100||a.health<0||a.health>1||!['load','out','build','back','rest'].includes(a.state))return false;this.built.set(save.built);for(const k of ['clock','seed','completedLoads','engine','wallHealth','shotClock','shots'])if(Number.isFinite(save[k])&&save[k]>=0)this[k]=save[k];this.engine=clamp(this.engine,0,1);this.wallHealth=clamp(this.wallHealth,this.wallFloor,1);this.agents.forEach((a,i)=>{for(const k of Object.keys(a))if(k!=='id'&&k!=='role'&&k!=='disabled'&&typeof save.agents[i][k]===typeof a[k])a[k]=save.agents[i][k];a.disabled=false;a.target=clamp(Math.round(a.target),0,this.built.length-1);if(!(a.patrolT>=0&&a.patrolT<1))a.patrolT=wrap(a.patrolT);a.fatigue=clamp(a.fatigue,0,1);});this.carts.forEach((c,i)=>{c.distance=(this.clock*1.65+i*this.cartRoute.total/5)%this.cartRoute.total;Object.assign(c,cartPoint(this.cartRoute,c.distance));});this.lastStage=undefined;this.revision++;return true;}
}
