import assert from 'node:assert/strict';
import * as THREE from 'three';
import {SCENARIOS} from '../scenarios.js';
import {SiegeSimulation,patrolPoint} from '../simulation.js';
import {SiegePhysics} from '../physics.js';
import {MiniatureScene} from '../scene.js';
import {TERRAIN,terrainIndices,containsPoint,cartPoint,cartRoute} from '../collision.js';
function architecture(sim,p){const scene=Object.create(MiniatureScene.prototype);Object.assign(scene,{sim,physics:p,root:new THREE.Group(),breakableWalls:[],banners:[],mats:new Map(),randSeed:sim.config.seed});scene.box=()=>{};scene.part=()=>{};scene.buildArchitecture();return scene;}
for(const s of SCENARIOS){const sim=new SiegeSimulation(s.id),p=new SiegePhysics(sim),v=architecture(sim,p);const geo=new THREE.PlaneGeometry(124,88,TERRAIN.cols,TERRAIN.rows);geo.rotateX(-Math.PI/2);geo.setIndex(terrainIndices());for(const complete of [false,true]){if(complete)sim.finishWorks();p.refreshTerrain();const pos=geo.attributes.position;for(let i=0;i<pos.count;i++)pos.setY(i,sim.heightAt(pos.getX(i),pos.getZ(i)));const mesh=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({side:THREE.DoubleSide}));mesh.updateMatrixWorld();for(let i=0;i<40;i++){const x=-58+(i*13.713)%116,z=-40+(i*7.171)%80,ray=new THREE.Raycaster(new THREE.Vector3(x,60,z),new THREE.Vector3(0,-1,0)),hit=ray.intersectObject(mesh)[0];assert(hit);assert(Math.abs(hit.point.y-p.floorAt(x,z))<.00001,`${s.id} rendered terrain and collider must coincide`);assert(Math.abs(sim.surfaceHeight(x,z)-p.floorAt(x,z))<.000001);}}
 for(const [x,z] of [[s.camp[0]+4,s.camp[1]+2],[s.end[0]-4,3],[s.fort[0],25]]){const b=p.makeDynamic(0);b.position.set(x,p.floorAt(x,z)+12,z);b.velocity.set(7,-65,3);b.quaternion.setFromEuler(1.4,.6,.8);for(let i=0;i<150;i++){p.update(1/60);assert(p.terrainPenetration(b)<.02,`${s.id} fast falling/tumbling body must stay above terrain`);}}
 for(let i=0;i<200;i++){const point=patrolPoint(s,i/200);assert(point.y>=p.floorAt(point.x,point.z));}
 // Construction must still work with the actual city/wall navigation obstacles.
 sim.built.fill(0);sim.revision++;sim.completedLoads=0;p.refreshTerrain();let violations=0;for(let i=0;i<3600;i++){sim.update(1/30);for(const a of sim.agents.filter(a=>!a.disabled&&!a.wallPatrol)){if(p.boxes.some(b=>b.active&&b.top>a.y+.12&&b.bottom<a.y+1.65&&containsPoint(b,a.x,a.z,.5)))violations++;}}
 assert.equal(violations,0,s.id+' controlled crews stay outside walls and buildings');assert(sim.completedLoads>0,s.id+' crews still reach their jobs');
 const route=cartRoute(s);let minDistance=Infinity;for(let t=0;t<route.total;t+=.07){const points=Array.from({length:5},(_,i)=>cartPoint(route,t+i*route.total/5));for(let i=0;i<5;i++)for(let j=i+1;j<5;j++)minDistance=Math.min(minDistance,Math.hypot(points[i].x-points[j].x,points[i].z-points[j].z));}assert(minDistance>2.3,s.id+' carts stay separated through the turns');
 console.log(s.id,'terrain match, fast drops, solid architecture, construction and cart lanes passed.',sim.completedLoads,'loads.');}
{
 const sim=new SiegeSimulation('alesia'),p=new SiegePhysics(sim),wall=p.addBox(-30,4,-30,.45,10,12),a=sim.agents[0];Object.assign(a,{x:-35,z:-30,y:p.floorAt(-35,-30)});p.update(1/60);const b=p.makeDynamic(0);b.position.set(-34,1,-30);b.velocity.set(35,0,0);for(let i=0;i<100;i++){p.update(1/60);assert(b.position.x<-30.35,'fast throw cannot tunnel through a thin wall');}
 b.type=4;a.disabled=false;Object.assign(a,{x:-35,z:-30,y:p.floorAt(-35,-30)});b.position.set(a.x,a.y+.72,a.z);for(let i=0;i<700;i++){sim.move(a,-25,-30,1/30,2.4);p.update(1/30);assert(!containsPoint(wall.obstacle,a.x,a.z,.5));}assert(Math.hypot(a.x+25,a.z+30)<.5,'ground navigation goes around the wall');
 p.removeBox(wall);Object.assign(a,{x:-35,z:-30,y:p.floorAt(-35,-30)});for(let i=0;i<140;i++)sim.move(a,-25,-30,1/30,2.4);assert(a.x>-26,'a breached wall opens its route');
}
{
 const sim=new SiegeSimulation('alesia'),p=new SiegePhysics(sim),a=sim.agents.find(a=>a.role==='soldier'),enemy=sim.agents.find(a=>a.role==='defender');Object.assign(a,{x:-35,z:-32,y:p.floorAt(-35,-32),wallPatrol:false});Object.assign(enemy,{x:-32,z:-32,y:p.floorAt(-32,-32),wallPatrol:false});p.update(1/60);const b=p.makeDynamic(a.id);b.velocity.set(8,0,0);let engaged=false,hits=0;for(let i=0;i<600;i++){sim.update(1/60);p.update(1/60);engaged ||= a.combatTarget===enemy.id;hits+=sim.events.filter(e=>e.type==='hit').length;}assert(engaged,'physical contact between enemies starts combat');assert(hits>2,'combat produces repeated melee actions');assert(a.health<1&&enemy.health<1,'both opposing soldiers take damage');assert(a.health>=.2&&enemy.health>=.2,'figures survive the schematic combat');const save=sim.exportState(),copy=new SiegeSimulation('alesia');assert(copy.restoreState(save));assert.deepEqual(copy.exportState(),save);console.log('Fast wall impacts, navigation around intact walls, breach traversal, enemy contact, fighting and persistence passed.',hits,'hits.');
}
